<?php

namespace Database\Seeders;

use App\Models\BluffQuestion;
use Illuminate\Database\Seeder;

class BluffQuestionSeeder extends Seeder
{
    public function run(): void
    {
        $questions = [
            ['question_text' => 'ما هي أكبر قارة في العالم؟', 'correct_answer' => 'آسيا'],
            ['question_text' => 'ما هو أطول نهر في العالم؟', 'correct_answer' => 'نهر النيل'],
            ['question_text' => 'ما هي عاصمة فرنسا؟', 'correct_answer' => 'باريس'],
            ['question_text' => 'كم عدد ألوان قوس قزح؟', 'correct_answer' => '7'],
            ['question_text' => 'ما هو الكوكب الأقرب إلى الشمس؟', 'correct_answer' => 'عطارد'],
            ['question_text' => 'ما هي أكبر دولة في العالم من حيث المساحة؟', 'correct_answer' => 'روسيا'],
            ['question_text' => 'ما هو الحيوان الأسرع في العالم؟', 'correct_answer' => 'الفهد'],
            ['question_text' => 'كم عدد عظام جسم الإنسان البالغ؟', 'correct_answer' => '206'],
            ['question_text' => 'ما هي اللغة الأكثر تحدثاً في العالم؟', 'correct_answer' => 'الإنجليزية'],
            ['question_text' => 'ما هو أطول مبنى في العالم؟', 'correct_answer' => 'برج خليفة'],
            ['question_text' => 'ما هو العنصر الكيميائي الذي رمزه O؟', 'correct_answer' => 'أكسجين'],
            ['question_text' => 'ما هو أكبر محيط في العالم؟', 'correct_answer' => 'المحيط الهادئ'],
            ['question_text' => 'كم عدد أيام السنة الكبيسة؟', 'correct_answer' => '366'],
            ['question_text' => 'ما هو أسرع طائر في العالم؟', 'correct_answer' => 'الصقر'],
            ['question_text' => 'في أي عام هبط الإنسان على القمر؟', 'correct_answer' => '1969'],
            ['question_text' => 'ما هي أكبر صحراء في العالم؟', 'correct_answer' => 'الصحراء الكبرى'],
            ['question_text' => 'ما هو أعمق مكان في المحيط؟', 'correct_answer' => 'خندق ماريانا'],
            ['question_text' => 'كم عدد سور القرآن الكريم؟', 'correct_answer' => '114'],
            ['question_text' => 'ما هي عروس البحر الأحمر؟', 'correct_answer' => 'جدة'],
            ['question_text' => 'ما هو أكبر عضو في جسم الإنسان؟', 'correct_answer' => 'الجلد'],
            ['question_text' => 'ما هو الغاز الذي يمتص الأشعة فوق البنفسجية؟', 'correct_answer' => 'الأوزون'],
            ['question_text' => 'ما هي العملة الرسمية لليابان؟', 'correct_answer' => 'الين'],
            ['question_text' => 'من اخترع المصباح الكهربائي؟', 'correct_answer' => 'إديسون'],
            ['question_text' => 'ما هو أطول جسر بحري في العالم؟', 'correct_answer' => 'جسر هونغ كونغ'],
            ['question_text' => 'كم عدد سكان الصين تقريباً؟', 'correct_answer' => '1.4 مليار'],
            ['question_text' => 'ما هي عاصمة كندا؟', 'correct_answer' => 'أوتاوا'],
            ['question_text' => 'ما هو العنصر الأكثر وفرة في القشرة الأرضية؟', 'correct_answer' => 'الأكسجين'],
            ['question_text' => 'كم عدد الصلوات المفروضة في الإسلام؟', 'correct_answer' => '5'],
            ['question_text' => 'ما هي أول عاصمة للدولة الإسلامية؟', 'correct_answer' => 'المدينة المنورة'],
            ['question_text' => 'ما هو أكبر نهر في أفريقيا؟', 'correct_answer' => 'نهر النيل'],
            ['question_text' => 'ما هو المعدن الذي رمزه Au؟', 'correct_answer' => 'الذهب'],
            ['question_text' => 'ما هي أكبر جزيرة في العالم؟', 'correct_answer' => 'غرينلاند'],
            ['question_text' => 'كم عدد أسنان الإنسان البالغ؟', 'correct_answer' => '32'],
            ['question_text' => 'ما هي عاصمة أستراليا؟', 'correct_answer' => 'كانبرا'],
            ['question_text' => 'من هو مؤسس علم الجبر؟', 'correct_answer' => 'الخوارزمي'],
            ['question_text' => 'ما هو أسرع كوكب في الدوران حول الشمس؟', 'correct_answer' => 'عطارد'],
            ['question_text' => 'في أي عام سقط جدار برلين؟', 'correct_answer' => '1989'],
            ['question_text' => 'ما هو أطول حيوان في العالم؟', 'correct_answer' => 'الزرافة'],
            ['question_text' => 'كم عدد أبواب الجنة في الإسلام؟', 'correct_answer' => '8'],
            ['question_text' => 'ما هي أكبر سلسلة جبلية في العالم؟', 'correct_answer' => 'جبال الأنديز'],
            ['question_text' => 'ما هي عاصمة مصر؟', 'correct_answer' => 'القاهرة'],
            ['question_text' => 'ما هو الكوكب الأحمر؟', 'correct_answer' => 'المريخ'],
            ['question_text' => 'كم عدد حروف اللغة العربية؟', 'correct_answer' => '28'],
            ['question_text' => 'ما هو أكبر خليج في العالم؟', 'correct_answer' => 'خليج المكسيك'],
            ['question_text' => 'من هو أول من اخترع الهاتف؟', 'correct_answer' => 'غراهام بيل'],
            ['question_text' => 'ما هي عاصمة المغرب؟', 'correct_answer' => 'الرباط'],
            ['question_text' => 'كم عدد أعضاء مجلس الأمن الدائمين؟', 'correct_answer' => '5'],
            ['question_text' => 'ما هو أقدم ديانة في العالم؟', 'correct_answer' => 'الهندوسية'],
            ['question_text' => 'ما هي أكبر مدينة في أوروبا؟', 'correct_answer' => 'لندن'],
            ['question_text' => 'من هو النبي الذي ابتلعه الحوت؟', 'correct_answer' => 'يونس'],
            ['question_text' => 'ما هي عاصمة العراق؟', 'correct_answer' => 'بغداد'],
            ['question_text' => 'ما هي أكبر بحيرة في العالم؟', 'correct_answer' => 'بحيرة قزوين'],
            ['question_text' => 'ما هو أغلى معدن في العالم؟', 'correct_answer' => 'الروديوم'],
            ['question_text' => 'كم عدد أضلاع جسم الإنسان؟', 'correct_answer' => '24'],
            ['question_text' => 'ما هي عاصمة تركيا؟', 'correct_answer' => 'أنقرة'],
            ['question_text' => 'في أي عام تأسست الأمم المتحدة؟', 'correct_answer' => '1945'],
            ['question_text' => 'ما هو أطول نهر في أوروبا؟', 'correct_answer' => 'نهر الفولغا'],
            ['question_text' => 'ما هي أصغر دولة في العالم من حيث المساحة؟', 'correct_answer' => 'الفاتيكان'],
            ['question_text' => 'ما هي أكبر جزيرة في العالم العربي؟', 'correct_answer' => 'سقطرى'],
            ['question_text' => 'كم عدد خلفاء الدولة العباسية؟', 'correct_answer' => '37'],
            ['question_text' => 'ما هي عاصمة النمسا؟', 'correct_answer' => 'فيينا'],
            ['question_text' => 'من هو مخترع الطباعة؟', 'correct_answer' => 'جوتنبرج'],
            ['question_text' => 'كم عدد أحرف الأبجدية الإنجليزية؟', 'correct_answer' => '26'],
            ['question_text' => 'ما هي عاصمة الهند؟', 'correct_answer' => 'نيودلهي'],
            ['question_text' => 'ما هو أكبر حيوان بري؟', 'correct_answer' => 'الفيل الأفريقي'],
            ['question_text' => 'ما هي عاصمة البرازيل؟', 'correct_answer' => 'برازيليا'],
            ['question_text' => 'كم عدد السور المكية في القرآن؟', 'correct_answer' => '86'],
            ['question_text' => 'ما هي عاصمة هولندا؟', 'correct_answer' => 'أمستردام'],
            ['question_text' => 'ما هي أكبر حديقة حيوانات في العالم؟', 'correct_answer' => 'حديقة حيوان برلين'],
            ['question_text' => 'ما هي عاصمة ماليزيا؟', 'correct_answer' => 'كوالالمبور'],
            ['question_text' => 'ما هو العنصر الكيميائي الذي رمزه Fe؟', 'correct_answer' => 'الحديد'],
            ['question_text' => 'من هو النبي الذي بنى سفينة؟', 'correct_answer' => 'نوح'],
            ['question_text' => 'من هو النبي الذي كلمه الله مباشرة؟', 'correct_answer' => 'موسى'],
            ['question_text' => 'ما هو أسرع حيوان بحري؟', 'correct_answer' => 'سمكة الزعنفة الشراعية'],
            ['question_text' => 'ما هو أطول جبل في العالم؟', 'correct_answer' => 'إيفرست'],
            ['question_text' => 'من هو أول من صام من الأنبياء؟', 'correct_answer' => 'آدم'],
            ['question_text' => 'كم عدد الكواكب في المجموعة الشمسية؟', 'correct_answer' => '8'],

            ['question_text' => 'من هو قائل "أنا الذي نظر الأعمى إلى أدبي"؟', 'correct_answer' => 'المتنبي', 'category_id' => 19],
            ['question_text' => 'من هو مؤلف رواية "البؤساء"؟', 'correct_answer' => 'فيكتور هوجو', 'category_id' => 19],
            ['question_text' => 'ما هي أشهر معلقات الشعر الجاهلي؟', 'correct_answer' => 'المعلقات السبع', 'category_id' => 19],
            ['question_text' => 'من هو صاحب ديوان "الشعر والشعراء"؟', 'correct_answer' => 'ابن قتيبة', 'category_id' => 19],
            ['question_text' => 'من هو مؤلف "كليلة ودمنة"؟', 'correct_answer' => 'ابن المقفع', 'category_id' => 19],
            ['question_text' => 'من هو شاعر "دع الأيام تفعل ما تشاء"؟', 'correct_answer' => 'الشافعي', 'category_id' => 19],
            ['question_text' => 'من هو مؤلف "ألف ليلة وليلة"؟', 'correct_answer' => 'مجهول', 'category_id' => 19],
            ['question_text' => 'من هو مؤلف مسرحية "روميو وجولييت"؟', 'correct_answer' => 'شكسبير', 'category_id' => 19],
            ['question_text' => 'من هو مؤلف "ثلاثية غرناطة"؟', 'correct_answer' => 'رضوى عاشور', 'category_id' => 19],
            ['question_text' => 'من هو قائل "إذا أنت أكرمت الكريم ملكته"؟', 'correct_answer' => 'المتنبي', 'category_id' => 19],
            ['question_text' => 'من هو الشاعر الملقب بـ "شاعر النيل"؟', 'correct_answer' => 'حافظ إبراهيم', 'category_id' => 19],
            ['question_text' => 'من هو مؤلف "موسم الهجرة إلى الشمال"؟', 'correct_answer' => 'الطيب صالح', 'category_id' => 19],
            ['question_text' => 'من هو صاحب "العبرات"؟', 'correct_answer' => 'المنفلوطي', 'category_id' => 19],
            ['question_text' => 'من هو قائل "ولم أر في عيوب الناس عيباً"؟', 'correct_answer' => 'الإمام الشافعي', 'category_id' => 19],
            ['question_text' => 'من هو مؤلف "الأيام"؟', 'correct_answer' => 'طه حسين', 'category_id' => 19],
            ['question_text' => 'من هي أشهر شاعرات العرب؟', 'correct_answer' => 'الخنساء', 'category_id' => 19],
            ['question_text' => 'من هو مؤلف "حي بن يقظان"؟', 'correct_answer' => 'ابن طفيل', 'category_id' => 19],
            ['question_text' => 'من هو الشاعر صاحب "نهج البردة"؟', 'correct_answer' => 'أحمد شوقي', 'category_id' => 19],
            ['question_text' => 'من هو مؤلف "زقاق المدق"؟', 'correct_answer' => 'نجيب محفوظ', 'category_id' => 19],
            ['question_text' => 'من هو شاعر "أراك عصي الدمع"؟', 'correct_answer' => 'أبو فراس الحمداني', 'category_id' => 19],
            ['question_text' => 'من هو مؤلف "عالم صوفي"؟', 'correct_answer' => 'جوستاين غاردر', 'category_id' => 19],
            ['question_text' => 'من هو قائل "وما نيل المطلب بالتمني"؟', 'correct_answer' => 'المتنبي', 'category_id' => 19],
            ['question_text' => 'من هو الشاعر الملقب بـ "المعري"؟', 'correct_answer' => 'أبو العلاء المعري', 'category_id' => 19],
            ['question_text' => 'من هو مؤلف "الكوميديا الإلهية"؟', 'correct_answer' => 'دانتي أليغييري', 'category_id' => 19],
            ['question_text' => 'من هو صاحب مقولة "أنا أفكر إذا أنا موجود"؟', 'correct_answer' => 'ديكارت', 'category_id' => 19],
            ['question_text' => 'من هو مؤلف "عداء الطائرة الورقية"؟', 'correct_answer' => 'خالد حسيني', 'category_id' => 19],
            ['question_text' => 'من هو مؤلف "أولاد حارتنا"؟', 'correct_answer' => 'نجيب محفوظ', 'category_id' => 19],
            ['question_text' => 'من هو مؤلف "النظرات"؟', 'correct_answer' => 'المنفلوطي', 'category_id' => 19],
            ['question_text' => 'من هو قائل "لا تسألن بني آدم حاجة"؟', 'correct_answer' => 'الإمام الشافعي', 'category_id' => 19],
            ['question_text' => 'من هو قائل "إذا الشعب يوماً أراد الحياة"؟', 'correct_answer' => 'أبو القاسم الشابي', 'category_id' => 19],
            ['question_text' => 'من هو الشاعر الملقب بـ "شاعر القطرين"؟', 'correct_answer' => 'خليل مطران', 'category_id' => 19],
            ['question_text' => 'من هو مؤلف "الحرب والسلم"؟', 'correct_answer' => 'ليو تولستوي', 'category_id' => 19],
            ['question_text' => 'أين وُلد الشاعر أحمد شوقي؟', 'correct_answer' => 'القاهرة', 'category_id' => 19],
            ['question_text' => 'من هو مؤلف "بين القصرين"؟', 'correct_answer' => 'نجيب محفوظ', 'category_id' => 19],
            ['question_text' => 'من هو قائل "كفى بك داءاً أن ترى الموت شافيا"؟', 'correct_answer' => 'المتنبي', 'category_id' => 19],
            ['question_text' => 'من هو مؤلف "جميل وبثينة"؟', 'correct_answer' => 'جميل بن معمر', 'category_id' => 19],
            ['question_text' => 'ما هي أشهر روايات جين أوستن؟', 'correct_answer' => 'كبرياء وهوى', 'category_id' => 19],
            ['question_text' => 'من هو الشاعر الملقب بـ "رائد الشعر الحر"؟', 'correct_answer' => 'نازك الملائكة', 'category_id' => 19],
            ['question_text' => 'من هو مؤلف "الشيخ والبحر"؟', 'correct_answer' => 'إرنست همنغواي', 'category_id' => 19],
            ['question_text' => 'من هو الشاعر الملقب بـ "الأمير" في الشعر العربي؟', 'correct_answer' => 'أحمد شوقي', 'category_id' => 19],
            ['question_text' => 'من هو مؤلف "السامر"؟', 'correct_answer' => 'عبد الله البردوني', 'category_id' => 19],
            ['question_text' => 'من هو صاحب ديوان "لزوم ما لا يلزم"؟', 'correct_answer' => 'أبو العلاء المعري', 'category_id' => 19],
            ['question_text' => 'من هو مؤلف "مدينة الشمس"؟', 'correct_answer' => 'علي أحمد باكثير', 'category_id' => 19],
            ['question_text' => 'من هو الشاعر الذي قتله شعره؟', 'correct_answer' => 'المتنبي', 'category_id' => 19],
            ['question_text' => 'من هي صاحبة ديوان "ليالي"؟', 'correct_answer' => 'إيليا أبو ماضي', 'category_id' => 19],
            ['question_text' => 'من هو مؤلف "لعبة الأمم"؟', 'correct_answer' => 'علي عزت بيغوفتش', 'category_id' => 19],
            ['question_text' => 'من هو الشاعر الملقب بـ "شاعر الشباب"؟', 'correct_answer' => 'علي محمود طه', 'category_id' => 19],
            ['question_text' => 'من هو مؤلف "الحرافيش"؟', 'correct_answer' => 'نجيب محفوظ', 'category_id' => 19],
            ['question_text' => 'من هو صاحب كتاب "الأغاني"؟', 'correct_answer' => 'أبو الفرج الأصفهاني', 'category_id' => 19],
            ['question_text' => 'من هو الشاعر الملقب بـ "شاعر الثورة"؟', 'correct_answer' => 'عبد الرحمن الأبنودي', 'category_id' => 19],

            ['question_text' => 'ما هو أكبر حيوان بري في أفريقيا؟', 'correct_answer' => 'الفيل الأفريقي', 'category_id' => 20],
            ['question_text' => 'كم عدد قلوب الأخطبوط؟', 'correct_answer' => '3', 'category_id' => 20],
            ['question_text' => 'ما هي أسرع الأسماك في المحيط؟', 'correct_answer' => 'سمكة الزعنفة الشراعية', 'category_id' => 20],
            ['question_text' => 'كم سنة تعيش السلحفاة البحرية؟', 'correct_answer' => '80', 'category_id' => 20],
            ['question_text' => 'ما هو الطائر الوحيد الذي يطير إلى الخلف؟', 'correct_answer' => 'الطائر الطنان', 'category_id' => 20],
            ['question_text' => 'ما هي أطول ثعبان في العالم؟', 'correct_answer' => 'الأناكوندا', 'category_id' => 20],
            ['question_text' => 'كم عدد أجنحة النحلة؟', 'correct_answer' => '4', 'category_id' => 20],
            ['question_text' => 'ما هو الحيوان الذي لا ينام أبداً؟', 'correct_answer' => 'السمك القرش', 'category_id' => 20],
            ['question_text' => 'ما هو أذكى الحيوانات البحرية؟', 'correct_answer' => 'الدولفين', 'category_id' => 20],
            ['question_text' => 'كم عدد عيون العنكبوت؟', 'correct_answer' => '8', 'category_id' => 20],
            ['question_text' => 'ما هي أكبر شجرة في العالم؟', 'correct_answer' => 'السكويا العملاقة', 'category_id' => 20],
            ['question_text' => 'ما هو الحيوان الذي يعيش أطول فترة؟', 'correct_answer' => 'الحوت مقوس الرأس', 'category_id' => 20],
            ['question_text' => 'ما هي أكبر زهرة في العالم؟', 'correct_answer' => 'الرافليسيا', 'category_id' => 20],
            ['question_text' => 'كم يوماً تفقس بيضة الدجاج؟', 'correct_answer' => '21', 'category_id' => 20],
            ['question_text' => 'ما هو الحيوان الذي يغير لونه؟', 'correct_answer' => 'الحرباء', 'category_id' => 20],
            ['question_text' => 'كم عدد الأرجل عند النملة؟', 'correct_answer' => '6', 'category_id' => 20],
            ['question_text' => 'ما هي أصغر طيور العالم؟', 'correct_answer' => 'الطائر الطنان', 'category_id' => 20],
            ['question_text' => 'ما هو الحيوان الذي لديه 3 جفون؟', 'correct_answer' => 'التمساح', 'category_id' => 20],
            ['question_text' => 'كم سنة يعيش الفيل الأفريقي؟', 'correct_answer' => '70', 'category_id' => 20],
            ['question_text' => 'ما هو الحيوان الوحيد الذي يستطيع تحريك فكه العلوي؟', 'correct_answer' => 'الأفعى', 'category_id' => 20],
            ['question_text' => 'ما هي أسرع طيور العالم في الطيران؟', 'correct_answer' => 'الصقر', 'category_id' => 20],
            ['question_text' => 'كم عدد فقرات الزرافة في رقبتها؟', 'correct_answer' => '7', 'category_id' => 20],
            ['question_text' => 'ما هو الحيوان الذي يتنفس من جلده؟', 'correct_answer' => 'الضفدع', 'category_id' => 20],
            ['question_text' => 'ما هي أكبر قطة في العالم؟', 'correct_answer' => 'النمر السيبيري', 'category_id' => 20],
            ['question_text' => 'كم معدة للبقرة؟', 'correct_answer' => '4', 'category_id' => 20],
            ['question_text' => 'ما هي أخطر سمكة في العالم؟', 'correct_answer' => 'السمكة الحجرية', 'category_id' => 20],
            ['question_text' => 'كم عدد أسنان الحلزون؟', 'correct_answer' => '25000', 'category_id' => 20],
            ['question_text' => 'ما هو الحيوان الوحيد الذي يمتلك بصمة أنف فريدة؟', 'correct_answer' => 'الكلب', 'category_id' => 20],
            ['question_text' => 'ما هي أعمق نقطة في المحيط؟', 'correct_answer' => 'خندق ماريانا', 'category_id' => 20],
            ['question_text' => 'كم كيلوغراماً يزن الفيل حديث الولادة؟', 'correct_answer' => '100', 'category_id' => 20],
            ['question_text' => 'ما هو أعلى جبل في أفريقيا؟', 'correct_answer' => 'كيليمانجارو', 'category_id' => 20],
            ['question_text' => 'ما هو أكبر حيوان في العالم؟', 'correct_answer' => 'الحوت الأزرق', 'category_id' => 20],
            ['question_text' => 'ما هو الحيوان الذي يشرب الماء عن طريق جلده؟', 'correct_answer' => 'الضفدع', 'category_id' => 20],
            ['question_text' => 'كم عدد أنواع البطاريق في العالم؟', 'correct_answer' => '18', 'category_id' => 20],
            ['question_text' => 'ما هو الحيوان الذي ينام واقفاً؟', 'correct_answer' => 'الحصان', 'category_id' => 20],
            ['question_text' => 'كم عدد قلوب دودة الأرض؟', 'correct_answer' => '5', 'category_id' => 20],
            ['question_text' => 'ما هو أكبر طائر في العالم؟', 'correct_answer' => 'النعامة', 'category_id' => 20],
            ['question_text' => 'ما هو أذكى الحيوانات البرية؟', 'correct_answer' => 'الشمبانزي', 'category_id' => 20],
            ['question_text' => 'كم عدد أجنحة الفراشة؟', 'correct_answer' => '4', 'category_id' => 20],
            ['question_text' => 'ما هو أبطأ حيوان في العالم؟', 'correct_answer' => 'الكسلان', 'category_id' => 20],
            ['question_text' => 'ما هو أخطر حيوان بحري؟', 'correct_answer' => 'قنديل البحر الصندوقي', 'category_id' => 20],
            ['question_text' => 'كم سنة تعيش السلحفاة البرية؟', 'correct_answer' => '150', 'category_id' => 20],
            ['question_text' => 'ما هي أكبر عين في المملكة الحيوانية؟', 'correct_answer' => 'الحبار العملاق', 'category_id' => 20],
            ['question_text' => 'ما هو الحيوان الذي ينام 20 ساعة يومياً؟', 'correct_answer' => 'الكوالا', 'category_id' => 20],
            ['question_text' => 'كم عدد أصابع الباندا؟', 'correct_answer' => '6', 'category_id' => 20],

            ['question_text' => 'ما هي السورة التي تسمى سنام القرآن؟', 'correct_answer' => 'سورة البقرة', 'category_id' => 21],
            ['question_text' => 'كم عدد آيات سورة البقرة؟', 'correct_answer' => '286', 'category_id' => 21],
            ['question_text' => 'من هو أول من كتب الوحي؟', 'correct_answer' => 'زيد بن ثابت', 'category_id' => 21],
            ['question_text' => 'في أي غزوة استشهد حمزة بن عبد المطلب؟', 'correct_answer' => 'غزوة أحد', 'category_id' => 21],
            ['question_text' => 'ما هي السورة التي لا تبدأ بالبسملة؟', 'correct_answer' => 'سورة التوبة', 'category_id' => 21],
            ['question_text' => 'من هو الصحابي الملقب بأسد الله؟', 'correct_answer' => 'حمزة بن عبد المطلب', 'category_id' => 21],
            ['question_text' => 'كم عدد الغزوات التي شارك فيها الرسول ﷺ؟', 'correct_answer' => '27', 'category_id' => 21],
            ['question_text' => 'ما هي أطول آية في القرآن؟', 'correct_answer' => 'آية الدين', 'category_id' => 21],
            ['question_text' => 'في أي عام وُلد النبي محمد ﷺ؟', 'correct_answer' => 'عام الفيل', 'category_id' => 21],
            ['question_text' => 'ما هي السورة التي تعدل ثلث القرآن؟', 'correct_answer' => 'سورة الإخلاص', 'category_id' => 21],
            ['question_text' => 'من هو آخر الصحابة وفاةً؟', 'correct_answer' => 'أبو الطفيل', 'category_id' => 21],
            ['question_text' => 'ما هو عدد أحزاب القرآن؟', 'correct_answer' => '60', 'category_id' => 21],
            ['question_text' => 'ما هي السورة التي تسمى قلب القرآن؟', 'correct_answer' => 'سورة يس', 'category_id' => 21],
            ['question_text' => 'كم عدد الرسل الذين ذكروا في القرآن؟', 'correct_answer' => '25', 'category_id' => 21],
            ['question_text' => 'ما هي غزوة الفرقان؟', 'correct_answer' => 'غزوة بدر', 'category_id' => 21],
            ['question_text' => 'من هو الصحابي الملقب بترجمان القرآن؟', 'correct_answer' => 'ابن عباس', 'category_id' => 21],
            ['question_text' => 'كم عدد السور المدنية في القرآن؟', 'correct_answer' => '28', 'category_id' => 21],
            ['question_text' => 'ما هي السورة التي تسمى عروس القرآن؟', 'correct_answer' => 'سورة الرحمن', 'category_id' => 21],
            ['question_text' => 'من هو أول مؤذن في الإسلام؟', 'correct_answer' => 'بلال بن رباح', 'category_id' => 21],
            ['question_text' => 'من هو النبي الذي رفع إلى السماء؟', 'correct_answer' => 'عيسى عليه السلام', 'category_id' => 21],
            ['question_text' => 'كم عدد أبواب جهنم؟', 'correct_answer' => '7', 'category_id' => 21],
            ['question_text' => 'من هو ثاني الخلفاء الراشدين؟', 'correct_answer' => 'عمر بن الخطاب', 'category_id' => 21],
            ['question_text' => 'من هو الصحابي الذي اهتز عرش الرحمن لموته؟', 'correct_answer' => 'سعد بن معاذ', 'category_id' => 21],
            ['question_text' => 'أين توفي الرسول ﷺ؟', 'correct_answer' => 'المدينة المنورة', 'category_id' => 21],
            ['question_text' => 'من هو أول من جهر بالقرآن في مكة؟', 'correct_answer' => 'عبد الله بن مسعود', 'category_id' => 21],
            ['question_text' => 'كم عدد التكبيرات في صلاة العيدين؟', 'correct_answer' => '12', 'category_id' => 21],
            ['question_text' => 'من هو الصحابي الملقب بذو النورين؟', 'correct_answer' => 'عثمان بن عفان', 'category_id' => 21],
            ['question_text' => 'كم عدد الأجزاء في القرآن؟', 'correct_answer' => '30', 'category_id' => 21],
            ['question_text' => 'ما هو أول مسجد بني في الإسلام؟', 'correct_answer' => 'مسجد قباء', 'category_id' => 21],
            ['question_text' => 'من هو خازن الجنة؟', 'correct_answer' => 'رضوان', 'category_id' => 21],
            ['question_text' => 'ما هي السورة التي تسمى الواقية؟', 'correct_answer' => 'سورة الملك', 'category_id' => 21],
            ['question_text' => 'من هو الصحابي الذي جمع القرآن؟', 'correct_answer' => 'أبو بكر الصديق', 'category_id' => 21],
            ['question_text' => 'كم عدد السجدات في القرآن؟', 'correct_answer' => '15', 'category_id' => 21],
            ['question_text' => 'ما هي السورة التي تسمى سورة التوديع؟', 'correct_answer' => 'سورة النصر', 'category_id' => 21],
            ['question_text' => 'من هي أول شهيدة في الإسلام؟', 'correct_answer' => 'سمية بنت خباط', 'category_id' => 21],
            ['question_text' => 'من هو آخر خلفاء بني أمية؟', 'correct_answer' => 'مروان بن محمد', 'category_id' => 21],
            ['question_text' => 'كم عدد السور التي سميت بأسماء أنبياء؟', 'correct_answer' => '7', 'category_id' => 21],
            ['question_text' => 'ما هي أول غزوة في الإسلام؟', 'correct_answer' => 'غزوة الأبواء', 'category_id' => 21],
            ['question_text' => 'من هو الصحابي الملقب بأمين الأمة؟', 'correct_answer' => 'أبو عبيدة بن الجراح', 'category_id' => 21],
            ['question_text' => 'من هو أول خليفة أموي؟', 'correct_answer' => 'معاوية بن أبي سفيان', 'category_id' => 21],
            ['question_text' => 'كم عدد الركعات في صلاة التراويح؟', 'correct_answer' => '8', 'category_id' => 21],
            ['question_text' => 'ما هي السورة التي يطلق عليها براءة؟', 'correct_answer' => 'سورة التوبة', 'category_id' => 21],
            ['question_text' => 'من هو النبي الذي آمن به جميع قومه؟', 'correct_answer' => 'يونس عليه السلام', 'category_id' => 21],
            ['question_text' => 'أين وُلد النبي محمد ﷺ؟', 'correct_answer' => 'مكة المكرمة', 'category_id' => 21],

            ['question_text' => 'من أين نشأت البيتزا؟', 'correct_answer' => 'إيطاليا', 'category_id' => 22],
            ['question_text' => 'ما هي الدولة الأولى في إنتاج القهوة؟', 'correct_answer' => 'البرازيل', 'category_id' => 22],
            ['question_text' => 'ما هو أشهر طبق في المطبخ الياباني؟', 'correct_answer' => 'السوشي', 'category_id' => 22],
            ['question_text' => 'من أين نشأت الشوكولاتة؟', 'correct_answer' => 'المكسيك', 'category_id' => 22],
            ['question_text' => 'ما هو المكون الرئيسي للحمص؟', 'correct_answer' => 'الحمص', 'category_id' => 22],
            ['question_text' => 'ما هي الدولة الأولى في إنتاج زيت الزيتون؟', 'correct_answer' => 'إسبانيا', 'category_id' => 22],
            ['question_text' => 'من أين نشأ المعكرونة؟', 'correct_answer' => 'إيطاليا', 'category_id' => 22],
            ['question_text' => 'ما هو أشهر طبق في المطبخ المكسيكي؟', 'correct_answer' => 'التاكو', 'category_id' => 22],
            ['question_text' => 'ما هو المكون الرئيسي للصوص البشاميل؟', 'correct_answer' => 'الحليب', 'category_id' => 22],
            ['question_text' => 'ما هي أشهر حلوى عربية؟', 'correct_answer' => 'الكنافة', 'category_id' => 22],
            ['question_text' => 'من أين نشأت البطاطس المقلية؟', 'correct_answer' => 'بلجيكا', 'category_id' => 22],
            ['question_text' => 'ما هو أشهر طبق في المطبخ الهندي؟', 'correct_answer' => 'الكاري', 'category_id' => 22],
            ['question_text' => 'ما هو المكون الرئيسي للسوشي؟', 'correct_answer' => 'الأرز', 'category_id' => 22],
            ['question_text' => 'ما هي الدولة الأولى في إنتاج التمور؟', 'correct_answer' => 'السعودية', 'category_id' => 22],
            ['question_text' => 'من أين نشأ الآيس كريم؟', 'correct_answer' => 'الصين', 'category_id' => 22],
            ['question_text' => 'ما هو أشهر طبق في المطبخ التركي؟', 'correct_answer' => 'الكباب', 'category_id' => 22],
            ['question_text' => 'ما هو المكون الرئيسي للسوشي؟', 'correct_answer' => 'الأرز', 'category_id' => 22],
            ['question_text' => 'ما هي الدولة التي تشتهر بالشوكولاتة السويسرية؟', 'correct_answer' => 'سويسرا', 'category_id' => 22],
            ['question_text' => 'ما هو أشهر طبق في المطبخ السوري؟', 'correct_answer' => 'الفلافل', 'category_id' => 22],
            ['question_text' => 'ما هو المشروب الوطني في إنجلترا؟', 'correct_answer' => 'الشاي', 'category_id' => 22],
            ['question_text' => 'من أين نشأت الكرواسون؟', 'correct_answer' => 'فرنسا', 'category_id' => 22],
            ['question_text' => 'ما هي الدولة الأولى في إنتاج الأرز؟', 'correct_answer' => 'الصين', 'category_id' => 22],
            ['question_text' => 'من أين نشأت المسقعة؟', 'correct_answer' => 'مصر', 'category_id' => 22],
            ['question_text' => 'ما هو أشهر طبق في المطبخ المغربي؟', 'correct_answer' => 'الكسكس', 'category_id' => 22],
            ['question_text' => 'من أين نشأت الباييلا؟', 'correct_answer' => 'إسبانيا', 'category_id' => 22],
            ['question_text' => 'ما هو أشهر طبق في المطبخ التايلاندي؟', 'correct_answer' => 'الباد تاي', 'category_id' => 22],
            ['question_text' => 'ما هي الدولة التي تشتهر بالفودكا؟', 'correct_answer' => 'روسيا', 'category_id' => 22],
            ['question_text' => 'ما هو أشهر طبق في المطبخ الفلسطيني؟', 'correct_answer' => 'المسخن', 'category_id' => 22],
            ['question_text' => 'ما هو أشهر طبق في المطبخ الكوري؟', 'correct_answer' => 'الكيمتشي', 'category_id' => 22],
            ['question_text' => 'ما هي الدولة الأولى في إنتاج الشاي؟', 'correct_answer' => 'الهند', 'category_id' => 22],
        ];

        foreach ($questions as $q) {
            BluffQuestion::create($q);
        }
    }
}
