<?php
return [
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'ما هو اسم بطل أنيمي "Naruto"؟',
        'a' => 'ساسكي أوتشيها',
        'b' => 'ناروتو أوزوماكي',
        'c' => 'ساكورا هارونو',
        'd' => 'كاكاشي',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'ما هو اسم قوة تيتان بيرين في Attack on Titan؟',
        'a' => 'تيتان المدرعة',
        'b' => 'تيتان المهاجم',
        'c' => 'تيتان المؤسس',
        'd' => 'تيتان الحرب',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'من هو مؤلف مانغا One Piece؟',
        'a' => 'ماساشي كيشيموتو',
        'b' => 'إيتشيرو أودا',
        'c' => 'هاجيمي إيسايما',
        'd' => 'أكيرا تورياما',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'ما هي "نينجوتسو" المميزة لآل أوتشيها؟',
        'a' => 'رايتون',
        'b' => 'شارينغان',
        'c' => 'يومانو',
        'd' => 'سوتون',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'في أنيمي Dragon Ball Z، كم مرة تحول غوكو إلى سوبر سايان لأول مرة؟',
        'a' => 'ضد فريزا',
        'b' => 'ضد سيل',
        'c' => 'ضد بيجيتا',
        'd' => 'ضد ماجين بو',
        'correct' => 'a',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'ما هو اسم الشركة الأسطورية المنتجة لأنيمي Spirited Away وPrincess Mononoke؟',
        'a' => 'Toei Animation',
        'b' => 'Studio Ghibli',
        'c' => 'Kyoto Animation',
        'd' => 'Madhouse',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'من هو مؤلف أنيمي Attack on Titan؟',
        'a' => 'إيتشيرو أودا',
        'b' => 'هاجيمي إيسايما',
        'c' => 'ماساشي كيشيموتو',
        'd' => 'أكيرا تورياما',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'ما هو اسم بطل أنيمي One Piece؟',
        'a' => 'زورو',
        'b' => 'نامي',
        'c' => 'مونكي دي لوفي',
        'd' => 'سانجي',
        'correct' => 'c',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'من هو مؤلف مانغا Dragon Ball؟',
        'a' => 'ماساشي كيشيموتو',
        'b' => 'إيتشيرو أودا',
        'c' => 'أكيرا تورياما',
        'd' => 'يوشيهيرو توغاشي',
        'correct' => 'c',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'في أنيمي Demon Slayer، ما هو اسم بطل القصة؟',
        'a' => 'زينيتسو',
        'b' => 'إينوسكي',
        'c' => 'تانجيرو كامادو',
        'd' => 'غييو توميوكا',
        'correct' => 'c',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'ما هو اسم القط العملاق اللطيف في أنيمي My Neighbor Totoro؟',
        'a' => 'توتورو',
        'b' => 'بيكاتشو',
        'c' => 'دورايمون',
        'd' => 'كيربي',
        'correct' => 'a',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'في Death Note، ما هو اسم مذكرة الموت؟',
        'a' => 'مذكرة ريوك',
        'b' => 'مذكرة الموت',
        'c' => 'دفتر شينيغامي',
        'd' => 'كتاب الظل',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'من هو بطل أنيمي Fullmetal Alchemist؟',
        'a' => 'موستانغ',
        'b' => 'إدورد إلريك',
        'c' => 'ألفونس إلريك',
        'd' => 'وينري',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'ما هو اسم أنيمي الساموراي الشهير لماساشي كيشيموتو؟',
        'a' => 'ساموراي 7',
        'b' => 'ساموراي تشامبلو',
        'c' => 'نينجا القمر',
        'd' => 'ناروتو',
        'correct' => 'd',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'كم عدد كرات Dragon Ball الموجودة؟',
        'a' => '5',
        'b' => '6',
        'c' => '7',
        'd' => '8',
        'correct' => 'c',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'ما هو اسم شقيق ناروتو الأكبر؟',
        'a' => 'ميناتو',
        'b' => 'كاكاشي',
        'c' => 'ساسكي',
        'd' => 'إيتاتشي أوتشيها',
        'correct' => 'd',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'في One Piece، ما هو اسم سفينة طاقم قبعة القش؟',
        'a' => 'ريد فورس',
        'b' => 'ثاوزند سني',
        'c' => 'ميري',
        'd' => 'غوين',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'ما هو اسم مدرسة ناروتو في الأكاديمية؟',
        'a' => 'إيروكا',
        'b' => 'ساكورا',
        'c' => 'تسونادي',
        'd' => 'هيناتا',
        'correct' => 'a',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'من هو مؤلف أنيمي Sparkle (Your Name)؟',
        'a' => 'هاياو ميازاكي',
        'b' => 'ماكوتو شينكاي',
        'c' => 'ساتوشي كون',
        'd' => 'مامورو هوسودا',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'في أنيمي Pokémon، ما هو اسم المدرب الأكثر شهرة؟',
        'a' => 'ميستي',
        'b' => 'بروك',
        'c' => 'آش كيتشام',
        'd' => 'غاري',
        'correct' => 'c',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'ما هي أقدم مهنة في أنيمي Hunter x Hunter؟',
        'a' => 'صياد الكنوز',
        'b' => 'صياد الوحوش',
        'c' => 'صياد',
        'd' => 'مغامر',
        'correct' => 'c',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'ما هو اسم أنيمي الميكا الشهير الذي يحارب فيه البشر عمالقة؟',
        'a' => 'غاندام',
        'b' => 'إيفانجيليون',
        'c' => 'أكسكاليبور',
        'd' => 'كود غياس',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'ما هو اسم الأنيمي الذي يتحدث عن طباخ شاب اسمه سوما؟',
        'a' => 'طعام الشوارع',
        'b' => 'مطعم سوكي',
        'c' => 'Food Wars',
        'd' => 'شيف الطموح',
        'correct' => 'c',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'ما هي رياضة الأنيمي المعروفة بـKuroko no Basket؟',
        'a' => 'كرة القدم',
        'b' => 'كرة السلة',
        'c' => 'الكرة الطائرة',
        'd' => 'التنس',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'في أنيمي Sword Art Online، ما اسم اللعبة الأولى التي حوصر فيها اللاعبون؟',
        'a' => 'ALfheim Online',
        'b' => 'Sword Art Online',
        'c' => 'Gun Gale Online',
        'd' => 'Underworld',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'ما هو اسم أنيمي الموت الشهير الذي ينافس فيه 100 شخص على كأس؟',
        'a' => 'Battle Royale',
        'b' => 'Mirai Nikki',
        'c' => 'Fate/Stay Night',
        'd' => 'Btooom!',
        'correct' => 'c',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'من هو مبتكر أنيمي Cowboy Bebop؟',
        'a' => 'شينيشيرو واتانابي',
        'b' => 'هاياو ميازاكي',
        'c' => 'ساتوشي كون',
        'd' => 'ماساموني شيرو',
        'correct' => 'a',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'في One Piece، ما هو اسم قرصان لوفي الأول؟',
        'a' => 'القراصنة الأحمر',
        'b' => 'قراصنة قبعة القش',
        'c' => 'القراصنة البيض',
        'd' => 'قراصنة الشمس',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'ما هو اسم أنيمي الرعب الشهير الذي يحكي عن فتاة تخرج من تلفزيون؟',
        'a' => 'Ju-On',
        'b' => 'Another',
        'c' => 'The Ring',
        'd' => 'Corpse Party',
        'correct' => 'c',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'ما هي قوة رأس الحجر في أنيمي One Punch Man؟',
        'a' => 'سرعته الفائقة',
        'b' => 'قوته الفائقة (ضربة واحدة)',
        'c' => 'تحمله للألم',
        'd' => 'قدرته على الطيران',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'في أنيمي Tokyo Ghoul، ما هو اسم البطل الذي يتحول إلى غول؟',
        'a' => 'هيدي',
        'b' => 'كين كانيكي',
        'c' => 'توكا',
        'd' => 'تسوكيياما',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'ما هو اسم أنيمي الخيال العلمي Steins;Gate عن ماذا يدور؟',
        'a' => 'السفر بين الكواكب',
        'b' => 'السفر عبر الزمن وأجهزة الكمبيوتر',
        'c' => 'الحرب في الفضاء',
        'd' => 'الروبوتات العملاقة',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'medium',
        'question' => 'ما اسم زهرة أنيمي Demon Slayer المميزة للشخير الأقوى؟',
        'a' => 'زهرة اللوتس',
        'b' => 'زهرة الوستيريا',
        'c' => 'زهرة الكرز',
        'd' => 'زهرة الورد',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'ما هي "Nen" في هانتر × هانتر وكم عدد أنواعها الرئيسية؟',
        'a' => 'قوة روحية، 4 أنواع',
        'b' => 'طاقة حيوية، 6 أنواع رئيسية',
        'c' => 'سحر، 8 أنواع',
        'd' => 'قوة مادية، 3 أنواع',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'في One Piece، ما هو اسم فاكهة شيطانية لوفي وما نوع تحوله الأحدث؟',
        'a' => 'Gum-Gum Fruit، Gear 5 (Nika)',
        'b' => 'Fire Fruit، Gear 4',
        'c' => 'Wind Fruit، Gear 6',
        'd' => 'Stone Fruit، Gear 3',
        'correct' => 'a',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'ما هو الفارق بين "Shonen" و"Seinen" كتصنيفات أنيمي؟',
        'a' => 'لا فارق',
        'b' => 'Shonen موجه للشباب الذكور وSeinen للرجال البالغين بمحتوى أكثر نضجاً',
        'c' => 'Shonen أقدم',
        'd' => 'الفارق في الرسومات فقط',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'أي استوديو أنيمي عُرف بأسلوبه السينمائي الاستثنائي في Violet Evergarden؟',
        'a' => 'Ufotable',
        'b' => 'Kyoto Animation',
        'c' => 'MAPPA',
        'd' => 'Wit Studio',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'ما هو نظام "الشيطانين العشرة" في Demon Slayer وما تسلسلهم؟',
        'a' => 'عشرة شياطين عشوائيون',
        'b' => 'الأشقاء الاثني عشر القمريون تحت قيادة موزان كيبوتسوجي مرتبين هرمياً',
        'c' => 'قادة منظمة شيطانية',
        'd' => 'محاربون بشريون',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'في Naruto Shippuden، من هو زعيم منظمة الأكاتسكي؟',
        'a' => 'إيتاتشي',
        'b' => 'أوروتشيمارو',
        'c' => 'باين (ناغاتو)',
        'd' => 'كيسامي',
        'correct' => 'c',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'ما هو اسم والد ناروتو؟',
        'a' => 'هيروزن',
        'b' => 'ميناتو ناميكازي (الوميض الأصفر)',
        'c' => 'داني',
        'd' => 'توبيراما',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'في Attack on Titan، ما هو الاسم الحقيقي لتيتان المرأة؟',
        'a' => 'ميكاسا',
        'b' => 'هيستوريا',
        'c' => 'آني ليونهارت',
        'd' => 'جان',
        'correct' => 'c',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'كم عدد أشكال التحول لـسوبر سايان في Dragon Ball Z الكلاسيكي؟',
        'a' => '2',
        'b' => '3',
        'c' => '4',
        'd' => '5',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'ما هو اسم التنين الذي يظهر عند جمع 7 كرات Dragon Ball؟',
        'a' => 'شينرون',
        'b' => 'شين لونغ',
        'c' => 'شين لون',
        'd' => 'بوور',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'في Studio Ghibli، ما هو فيلم هاياو ميازاكي الذي فاز بجائزة الأوسكار؟',
        'a' => 'Princess Mononoke',
        'b' => 'Spirited Away',
        'c' => 'My Neighbor Totoro',
        'd' => 'Howl\'s Moving Castle',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'ما هو اسم الجهاز الذي يستخدمه شينيغامي في Death Note؟',
        'a' => 'هاتف الموت',
        'b' => 'كمبيوتر الموت',
        'c' => 'مذكرات الموت',
        'd' => 'ساعة الموت',
        'correct' => 'c',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'في One Piece، من هو أقوى ملك قراصنة قبل لوفي؟',
        'a' => 'شانكس',
        'b' => 'غول دي روجر',
        'c' => 'وايتبيرد',
        'd' => 'كايدو',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'ما هي تقنية "Bankai" في Bleach؟',
        'a' => 'تقنية سيوف',
        'b' => 'المرحلة الثانية لتحرير السيف الميت',
        'c' => 'هجوم ناري',
        'd' => 'درع روحي',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'من هو مؤلف مانغا Hunter x Hunter؟',
        'a' => 'يوشيهيرو توغاشي',
        'b' => 'هيرومو أراكاوا',
        'c' => 'كوهي هوريكوشي',
        'd' => 'تيتي كوبو',
        'correct' => 'a',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'في Demon Slayer، ما اسم التنفس الذي يستخدمه تانجيرو؟',
        'a' => 'تنفس الشمس',
        'b' => 'تنفس الماء',
        'c' => 'تنفس النار',
        'd' => 'تنفس الريح',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'ما هو اسم أنيمي Code Geass؟ ما هي قوة لولوش؟',
        'a' => 'التحكم بالعقول (Geass)',
        'b' => 'قراءة الأفكار',
        'c' => 'التخفي',
        'd' => 'السرعة الخارقة',
        'correct' => 'a',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'في أنيمي Fairy Tail، ما اسم رئيس النقابة؟',
        'a' => 'إيرزا',
        'b' => 'ميراجين',
        'c' => 'ماكاروف',
        'd' => 'ناتسو',
        'correct' => 'c',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'ما هو اسم أنيمي Action-Drama الذي يدور حول كرة القدم ويسمى "Blue Lock"؟',
        'a' => 'كرة القدم الشيطانية',
        'b' => 'السجن الأزرق',
        'c' => 'الهداف',
        'd' => 'كابتن ماجد',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'من هو مخترع تقنية Rasengan في ناروتو؟',
        'a' => 'ناروتو',
        'b' => 'ميناتو',
        'c' => 'جيْرايَا',
        'd' => 'كاكاشي',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'في Attack on Titan، من هو بيرين الحقيقي صاحب تيتان المؤسس؟',
        'a' => 'إرين',
        'b' => 'راينر',
        'c' => 'إرين ييغر',
        'd' => 'زيكي',
        'correct' => 'c',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'ما معنى كلمة "Otaku" في الثقافة اليابانية؟',
        'a' => 'محترف',
        'b' => 'شخص مهووس بالأنيمي والمانغا',
        'c' => 'مبتدئ',
        'd' => 'طالب',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'ما هو اسم أول أنيمي تجاري ياباني؟',
        'a' => 'Momotaro\'s Divine Sea Warriors',
        'b' => 'Astro Boy',
        'c' => 'Speed Racer',
        'd' => 'Dragon Ball',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'في أنيمي Your Name، ما اسم الشخصية الرئيسية الذكر؟',
        'a' => 'تاكي تاتشيبانا',
        'b' => 'ميتسوها مياميزو',
        'c' => 'كاتسوهيكو',
        'd' => 'توشيكي',
        'correct' => 'a',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'في One Punch Man، ما هو تصنيف سايتاما في رابطة الأبطال؟',
        'a' => 'S-Class',
        'b' => 'A-Class',
        'c' => 'B-Class',
        'd' => 'C-Class',
        'correct' => 'd',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'ما هي قوة "هاشيرا" في Demon Slayer؟',
        'a' => 'مبتدئ',
        'b' => 'أقوى محاربي الشياطين من البشر',
        'c' => 'شيطان',
        'd' => 'تاجر أسلحة',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'ما هو أطول أنيمي في التاريخ من حيث عدد الحلقات؟',
        'a' => 'One Piece',
        'b' => 'Sazae-san',
        'c' => 'Dragon Ball',
        'd' => 'Naruto',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'في أنيمي Psycho-Pass، ماذا يقيس جهاز Sibyl؟',
        'a' => 'مستوى الذكاء',
        'b' => 'مستوى الجريمة والنفسية البشرية',
        'c' => 'القوة البدنية',
        'd' => 'الذاكرة',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'ما هي "Chakra" في عالم ناروتو؟',
        'a' => 'طاقة الحياة فقط',
        'b' => 'مزيج من الطاقة الجسدية والروحية',
        'c' => 'سحر',
        'd' => 'قوة الشياطين',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'في أنيمي "Jujutsu Kaisen"، ما اسم البطل؟',
        'a' => 'ميجومي',
        'b' => 'يوجي إيتادوري',
        'c' => 'جوجو',
        'd' => 'غوجو',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'ما اسم تنين سيف التنين في أنيمي One Piece الذي يمتلكه زورو؟',
        'a' => 'Wado Ichimonji',
        'b' => 'Enma',
        'c' => 'Sandai Kitetsu',
        'd' => 'Shusui',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'hard',
        'question' => 'من هو مؤلف أنيمي Death Parade؟',
        'a' => 'يوزورو تاتشيكاوا',
        'b' => 'يوكي مادارامي',
        'c' => 'تسوتومو ناكامورا',
        'd' => 'كينجي ناكامورا',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'في Fullmetal Alchemist Brotherhood، ما هو مفهوم "الحقيقة" وما علاقته بـ"الخسارة المتكافئة"؟',
        'a' => 'إله الكيمياء',
        'b' => 'الوعي الكوني الذي يمنح ويأخذ بالتساوي وجسد ذلك بالخسارة المتكافئة',
        'c' => 'فلسفة نيلية',
        'd' => 'قوة الحجر الفيلسوفي',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'ما هو تأثير Evangelion على صناعة الأنيمي من منظور السرد الفلسفي والبنية النفسية؟',
        'a' => 'لا تأثير خاص',
        'b' => 'أسس سردية مركزها أزمة الهوية والديكونستراكشن لنمط Super Robot مع فرويد ويونغ',
        'c' => 'فقط من حيث التقنية',
        'd' => 'أثّر في الكوميكس فقط',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'ما هو مفهوم "Sakuga" في الأنيمي وكيف يختلف عن "Standard Animation"؟',
        'a' => 'تقنية صوتية',
        'b' => 'لقطات أنيمي فائقة الجودة مع حرية المحرك، تكسر نمط الحركة المحدودة',
        'c' => 'أسلوب رسم ياباني قديم',
        'd' => 'مصطلح تقنية تلوين',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'كيف استخدم هاياو مياظاكي مفهوم البيئة والطبيعة في Nausicaä كنقد حضاري؟',
        'a' => 'لم يكن نقداً',
        'b' => 'صوّر الطبيعة كنقيض للتكنولوجيا وأظهر أن الانسجام معها يتطلب التخلي عن الغطرسة البشرية',
        'c' => 'إشادة بالحرب',
        'd' => 'فانتازيا مجردة',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'كيف يُمثل أنيمي "Paranoia Agent" نقداً للمجتمع الياباني ما بعد الحداثي؟',
        'a' => 'لا نقد اجتماعي',
        'b' => 'يستعمل الواقعية السحرية لتعرية الهروب الجماعي من المسؤولية',
        'c' => 'نقد سياسي بحت',
        'd' => 'تجربة فنية شكلية',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'في Naruto ما هو اسم تقنية إيتاتشي النهائية المحرمة؟',
        'a' => 'Amaterasu',
        'b' => 'Tsukuyomi',
        'c' => 'Izanami',
        'd' => 'Susano\'o',
        'correct' => 'c',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'ما هو الترتيب الصحيح لأقوى 3 تيتانات في Attack on Titan؟',
        'a' => 'المؤسس > المهاجم > المدرعة',
        'b' => 'المهاجم > المؤسس > الحرب',
        'c' => 'المؤسس > المدرعة > المهاجم',
        'd' => 'الحرب > المؤسس > المهاجم',
        'correct' => 'a',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'من هو الخالق الحقيقي لعالم One Piece حسب ما كشف عنه أودا باسم "Im-sama"؟',
        'a' => 'غول دي روجر',
        'b' => 'الحكومة العالمية السرية - إم',
        'c' => 'جوي بوي',
        'd' => 'شوجي',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'ما هي الرواية الفلسفية التي استلهم منها أنيمي Psycho-Pass مفهومه الأساسي عن العدالة؟',
        'a' => 'الجريمة والعقاب',
        'b' => 'اليوتوبيا',
        'c' => 'فلسفة بنثام النفعية ومفهوم البانوبتيكون',
        'd' => 'الجمهورية لأفلاطون',
        'correct' => 'c',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'في أنيمي Serial Experiments Lain، ما هي القضية الفلسفية المركزية؟',
        'a' => 'الهوية والوجود في عصر المعلومات',
        'b' => 'الحرب',
        'c' => 'الحب',
        'd' => 'السفر عبر الزمن',
        'correct' => 'a',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'من هو أول "Hokage" في قرية الورق في ناروتو؟',
        'a' => 'هاشيراما سينجو',
        'b' => 'توبيراما سينجو',
        'c' => 'هيروزن ساروتوبي',
        'd' => 'ميناتو',
        'correct' => 'a',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'ما معنى مصطلح "Kawaisa" في الأنيمي وكيف يستخدم كأداة سردية؟',
        'a' => 'القوة',
        'b' => 'اللطافة كآلية لتخفيف التوتر وربط الجمهور عاطفياً',
        'c' => 'الشر',
        'd' => 'الجمال',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'في Dragon Ball Super، ما هي قوة Ultra Instinct وما شرط تفعيلها؟',
        'a' => 'قوة نارية تتطلب الغضب',
        'b' => 'حركة جسدية تلقائية تتطلب هدوء العقل الكامل وانفصال المشاعر',
        'c' => 'درع يتطلب الخوف',
        'd' => 'سرعة تتطلب التضحية',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'ما هو الرمز الثقافي والتاريخي لـ"النينجا" في الأنيمي مقارنة بالتاريخ الياباني الحقيقي؟',
        'a' => 'متطابقان',
        'b' => 'الأنيمي يبالغ بشكل خيالي بينما تاريخياً كانوا جواسيس ومخربين بقدرات محدودة',
        'c' => 'التاريخ أهمل النينجا',
        'd' => 'الأنيمي أقل',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'ما هو أسلوب الرسم "Moe" وما تأثيره على شخصيات الأنيمي الحديثة؟',
        'a' => 'واقعي جداً',
        'b' => 'أسلوب يبرز البراءة واللطافة لإثارة الحماية العاطفية لدى المشاهد',
        'c' => 'عنيف',
        'd' => 'قوطي',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'في Demon Slayer، لماذا لا يستطيع موزان كيبوتسوجي هزيمة هاشيرا بسهولة رغم قوته الهائلة؟',
        'a' => 'لأنه ضعيف',
        'b' => 'بسبب لعنة الأجداد وخوفه من تنفس الشمس',
        'c' => 'لأنه يخاف من الماء',
        'd' => 'لأنه مريض',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'من هو المخرج الذي ابتكر أنيمي "Neon Genesis Evangelion"؟',
        'a' => 'هاياو ميازاكي',
        'b' => 'هيديكي أنو',
        'c' => 'ساتوشي كون',
        'd' => 'ماساموني شيرو',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'ما هي العلاقة بين الأنيمي والمانغا والـ"Light Novel" من حيث دورة الإنتاج؟',
        'a' => 'عشوائية تماماً',
        'b' => 'غالباً المانغا أو اللایت نوفل مصدر أصلي ثم يُحَوّل لأنيمي تسويقياً',
        'c' => 'الأنيمي أولاً',
        'd' => 'المانغا والأنيمي منفصلان',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'كيف اختلف أنيمي "Berserk" (1997) عن المانغا الأصلية في السرد؟',
        'a' => 'متطابق',
        'b' => 'الأنيمي حذف آرك Black Swordsman وترك الماضي فقط مما غيّر البناء السردي',
        'c' => 'المانغا أقل',
        'd' => 'الأنيمي أضاف شخصيات جديدة',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "كونغ فو" في عالم "هانتر × هانتر" المتعلق بـNen؟',
        'a' => 'فنون قتالية',
        'b' => 'الإتقان المتقدم لـNen من خلال التمارين العقلية والجسدية والوعي بالوعي',
        'c' => 'طبخ',
        'd' => 'رقص',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'ما اسم قوة لوفي القديمة التي اكتشفها في Gear 5؟',
        'a' => 'سحر المطاط',
        'b' => 'Hito Hito no Mi Model: Nika (التجسيد الحر للشمس)',
        'c' => 'Gomu Gomu no Mi',
        'd' => 'فاكهة النار',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'في Steins;Gate، ما هو مفهوم "Reading Steiner"؟',
        'a' => 'قدرة خارقة',
        'b' => 'القدرة على الاحتفاظ بذاكرة الخط الزمني الأصلي عند تغيير الماضي',
        'c' => 'قراءة العقول',
        'd' => 'التحكم بالوقت',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'ما الدافع الفلسفي وراء مشروع ("Human Instrumentality Project") في Evangelion؟',
        'a' => 'السيطرة على العالم',
        'b' => 'دمج البشر في كيان واحد لإزالة الألم الناتج عن الحدود الفردية',
        'c' => 'تدمير البشرية',
        'd' => 'صنع أسلحة',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'من هو صاحب نظرية "السوبر فلات" التي أثرت في الأنيمي الحديث؟',
        'a' => 'هاياو ميازاكي',
        'b' => 'تاكاشي موراكامي',
        'c' => 'ساتوشي كون',
        'd' => 'ليج ماتسوموتو',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'ما هو أقدم أنيمي معروف في التاريخ من عام 1917؟',
        'a' => 'Momotaro',
        'b' => 'Namakura Gatana (السيف البليد)',
        'c' => 'Astro Boy',
        'd' => 'Kimba',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'في Fullmetal Alchemist، ما العلاقة بين "حجر الفيلسوف" و"الخيمياء البشرية"؟',
        'a' => 'لا علاقة',
        'b' => 'حجر الفيلسوف يتجاوز قانون الخسارة المتكافئة ويجعل الخيمياء البشرية ممكنة',
        'c' => 'حجر الفيلسوف يمنعها',
        'd' => 'الخيمياء البشرية أقوى',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'كيف يمثل أنيمي "Perfect Blue" أزمة هوية المشاهير في عصر الإعلام؟',
        'a' => 'بلا رمزية',
        'b' => 'يمزج الواقع بالخيال ليعبّر عن تفكك الذات تحت ضغط الشهرة والمراقبة الدائمة',
        'c' => 'كوميديا',
        'd' => 'أكشن فقط',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'ما هو الفرق بين "Shonen" و"Shoujo" و"Josei" كتصنيفات ديموغرافية؟',
        'a' => 'كلها نفس الشيء',
        'b' => 'Shonen للذكور اليافعين، Shoujo للإناث اليافعات، Josei للنساء البالغات',
        'c' => 'Shonen أقدم',
        'd' => 'حسب الرسم',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'في أنيمي "Monster" لناوكي أوراساوا، ما الفكرة الفلسفية حول الشر التي يمثلها يوهان؟',
        'a' => 'الشر مجرد وهم',
        'b' => 'الشر كنتاج للفراغ الوجودي والعبثية النيتشوية المتطرفة',
        'c' => 'الشر وراثي',
        'd' => 'الشر نتيجة فقر',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'كيف استخدم استوديو "Ufotable" تقنيات CG في Demon Slayer لإحداث ثورة في معارك الأنيمي؟',
        'a' => 'لم يستخدمها',
        'b' => 'دمج CG بالرسوم اليدوية بمزج سلس لخلق معارك سائلة ومذهلة بصرياً',
        'c' => 'CG فقط',
        'd' => 'يدوي فقط',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "الإطار المحدود" في أنيمي؟',
        'a' => 'إطار برواز',
        'b' => 'تقنية اقتصادية تحرك أجزاء محدودة من الصورة لتقليل التكاليف مع الحفاظ على الإيحاء بالحركة',
        'c' => 'إطار للعرض',
        'd' => 'برنامج',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'ما هي أهمية "Madhouse" في نشر الأنيمي عالمياً عبر "Ninja Scroll"؟',
        'a' => 'لا أهمية',
        'b' => 'Ninja Scroll كان باكورة نجاح الأنيمي في الغرب بمحتواه العنيف الناضج',
        'c' => 'فشل',
        'd' => 'أطفال فقط',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'كيف ينتقد أنيمي "Paprika" للمخرج ساتوشي كون علاقة الأحلام بالواقع والتكنولوجيا؟',
        'a' => 'لا نقد',
        'b' => 'يصور تداخل الأحلام والتقنية كاستعارة لاختراق العقل الجمعي وفقدان الحدود',
        'c' => 'ثناء على التقنية',
        'd' => 'قصة حب فقط',
        'correct' => 'b',
    ],
    [
        'category' => 'anime',
        'difficulty' => 'very_hard',
        'question' => 'ما هو دور موسيقي "Yoko Kanno" في تشكيل هوية أنيمي "Cowboy Bebop"؟',
        'a' => 'لا دور',
        'b' => 'مزج Jazz وBlues ليعكس الروح النوستالجية المنعزلة للشخصيات',
        'c' => 'أغاني أطفال',
        'd' => 'موسيقى كلاسيكية فقط',
        'correct' => 'b',
    ],
];
