<?php

return [
    [
        'category' => 'basketball',
        'difficulty' => 'medium',
        'question' => 'من هو اللاعب الملقب بـ "Air Jordan"؟',
        'a' => 'كوبي براينت',
        'b' => 'مايكل جوردان',
        'c' => 'ليبرون جيمس',
        'd' => 'شاكيل أونيل',
        'correct' => 'b',
    ],
    [
        'category' => 'basketball',
        'difficulty' => 'medium',
        'question' => 'كم عدد لاعبي كرة السلة في كل فريق على أرض الملعب؟',
        'a' => '4',
        'b' => '6',
        'c' => '5',
        'd' => '7',
        'correct' => 'c',
    ],
    [
        'category' => 'basketball',
        'difficulty' => 'medium',
        'question' => 'ما هي أعلى هيئة تنظيمية لكرة السلة في العالم؟',
        'a' => 'NBA',
        'b' => 'FIBA',
        'c' => 'WNBA',
        'd' => 'EuroLeague',
        'correct' => 'b',
    ],
    [
        'category' => 'basketball',
        'difficulty' => 'hard',
        'question' => 'أي فريق فاز بأول بطولة NBA في التاريخ؟',
        'a' => 'بوسطن سيلتيكس',
        'b' => 'لوس أنجلوس ليكرز',
        'c' => 'شيكاغو بولز',
        'd' => 'فيلادلفيا ووريورز',
        'correct' => 'd',
    ],
    [
        'category' => 'basketball',
        'difficulty' => 'hard',
        'question' => 'من هو اللاعب الذي سجل أكبر عدد من النقاط في مباراة واحدة في تاريخ NBA؟',
        'a' => 'كوبي براينت - 81 نقطة',
        'b' => 'مايكل جوردان - 69 نقطة',
        'c' => 'ويلت تشامبرلين - 100 نقطة',
        'd' => 'ليبرون جيمس - 61 نقطة',
        'correct' => 'c',
    ],
    [
        'category' => 'basketball',
        'difficulty' => 'hard',
        'question' => 'ما هو طول خط الرميات الثلاثية في NBA؟',
        'a' => '22 قدماً',
        'b' => '23.75 قدماً',
        'c' => '24 قدماً',
        'd' => '21.5 قدماً',
        'correct' => 'b',
    ],
    [
        'category' => 'basketball',
        'difficulty' => 'very_hard',
        'question' => 'من هو اللاعب الوحيد الذي فاز بجائزة أفضل لاعب (MVP) في NBA لأربع مرات متتالية؟',
        'a' => 'ماجيك جونسون',
        'b' => 'لاري بيرد',
        'c' => 'بيل راسل',
        'd' => 'ليبرون جيمس',
        'correct' => 'c',
    ],
    [
        'category' => 'basketball',
        'difficulty' => 'very_hard',
        'question' => 'ما هو الفريق الوحيد الذي أنهى موسم NBA كاملاً بدون خسارة وفاز بالبطولة؟',
        'a' => 'شيكاغو بولز 1996',
        'b' => 'جولدن ستيت ووريورز 2016',
        'c' => 'فيلادلفيا 76ers 1967',
        'd' => 'لوس أنجلوس ليكرز 1972',
        'correct' => 'c',
    ],
    [
        'category' => 'basketball',
        'difficulty' => 'very_hard',
        'question' => 'من هو أقصر لاعب في تاريخ NBA؟',
        'a' => 'نيت روبنسون',
        'b' => 'سبود ويب',
        'c' => 'ماغسي بوجز',
        'd' => 'إيرل بويكنز',
        'correct' => 'c',
    ],
    [
        'category' => 'basketball',
        'difficulty' => 'medium',
        'question' => 'كم عدد أرباع مباراة كرة السلة في NBA؟',
        'a' => '3',
        'b' => '2',
        'c' => '4',
        'd' => '5',
        'correct' => 'c',
    ],
    [
        'category' => 'basketball',
        'difficulty' => 'hard',
        'question' => 'أي لاعب يحمل الرقم القياسي لأكبر عدد من التمريرات الحاسمة في مسيرته في NBA؟',
        'a' => 'كريس بول',
        'b' => 'ماجيك جونسون',
        'c' => 'جون ستوكتون',
        'd' => 'ستيف ناش',
        'correct' => 'c',
    ],
    [
        'category' => 'basketball',
        'difficulty' => 'medium',
        'question' => 'أين يقع مقر قاعة مشاهير كرة السلة (Naismith Memorial Basketball Hall of Fame)؟',
        'a' => 'نيويورك',
        'b' => 'شيكاغو',
        'c' => 'سبرينغفيلد',
        'd' => 'لوس أنجلوس',
        'correct' => 'c',
    ],
];
