<?php
return [
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي عاصمة فرنسا؟', 'a' => 'لندن', 'b' => 'باريس', 'c' => 'برلين', 'd' => 'مدريد', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي عاصمة مصر؟', 'a' => 'الإسكندرية', 'b' => 'القاهرة', 'c' => 'الجيزة', 'd' => 'الأقصر', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي عاصمة اليابان؟', 'a' => 'طوكيو', 'b' => 'سول', 'c' => 'بكين', 'd' => 'بانكوك', 'correct' => 'a'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي عاصمة أستراليا؟', 'a' => 'سيدني', 'b' => 'ملبورن', 'c' => 'كانبرا', 'd' => 'بريسبان', 'correct' => 'c'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي عاصمة البرازيل؟', 'a' => 'ريو دي جانيرو', 'b' => 'برازيليا', 'c' => 'ساو باولو', 'd' => 'سلفادور', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي عاصمة تركيا؟', 'a' => 'إسطنبول', 'b' => 'أنقرة', 'c' => 'إزمير', 'd' => 'بورصة', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي عاصمة المملكة العربية السعودية؟', 'a' => 'جدة', 'b' => 'مكة', 'c' => 'الرياض', 'd' => 'الدمام', 'correct' => 'c'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي عاصمة ألمانيا؟', 'a' => 'ميونخ', 'b' => 'برلين', 'c' => 'فرانكفورت', 'd' => 'هامبورغ', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي عاصمة الهند؟', 'a' => 'مومباي', 'b' => 'نيودلهي', 'c' => 'كلكتا', 'd' => 'بنغالور', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي عاصمة روسيا؟', 'a' => 'موسكو', 'b' => 'سانت بطرسبرغ', 'c' => 'كييف', 'd' => 'نوفوسيبيرسك', 'correct' => 'a'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي عاصمة كندا؟', 'a' => 'تورنتو', 'b' => 'أوتاوا', 'c' => 'فانكوفر', 'd' => 'مونتريال', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي عاصمة إيطاليا؟', 'a' => 'ميلانو', 'b' => 'روما', 'c' => 'نابولي', 'd' => 'البندقية', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي عاصمة الأرجنتين؟', 'a' => 'بوينس آيرس', 'b' => 'قرطبة', 'c' => 'روساريو', 'd' => 'مندوزا', 'correct' => 'a'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي عاصمة جنوب أفريقيا؟', 'a' => 'كيب تاون', 'b' => 'بريتوريا', 'c' => 'جوهانسبرغ', 'd' => 'ديربان', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي عاصمة الصين؟', 'a' => 'شنغهاي', 'b' => 'بكين', 'c' => 'هونغ كونغ', 'd' => 'غوانزو', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي عاصمة الإمارات العربية المتحدة؟', 'a' => 'دبي', 'b' => 'أبو ظبي', 'c' => 'الشارقة', 'd' => 'العين', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي عاصمة العراق؟', 'a' => 'البصرة', 'b' => 'بغداد', 'c' => 'أربيل', 'd' => 'الموصل', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي عاصمة السودان؟', 'a' => 'بورتسودان', 'b' => 'الخرطوم', 'c' => 'أم درمان', 'd' => 'كسلا', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي عاصمة المغرب؟', 'a' => 'الدار البيضاء', 'b' => 'الرباط', 'c' => 'مراكش', 'd' => 'فاس', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي عاصمة الجزائر؟', 'a' => 'وهران', 'b' => 'الجزائر', 'c' => 'عنابة', 'd' => 'قسنطينة', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي أكبر دولة في العالم من حيث المساحة؟', 'a' => 'الصين', 'b' => 'روسيا', 'c' => 'الولايات المتحدة', 'd' => 'كندا', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي أصغر دولة في العالم من حيث المساحة؟', 'a' => 'موناكو', 'b' => 'الفاتيكان', 'c' => 'سان مارينو', 'd' => 'ليختنشتاين', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'كم عدد الدول في قارة أفريقيا؟', 'a' => '45', 'b' => '54', 'c' => '48', 'd' => '50', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'أي دولة في العالم تمتلك أكبر عدد من السكان؟', 'a' => 'الصين', 'b' => 'الهند', 'c' => 'الولايات المتحدة', 'd' => 'إندونيسيا', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي عاصمة إسبانيا؟', 'a' => 'برشلونة', 'b' => 'مدريد', 'c' => 'إشبيلية', 'd' => 'فالنسيا', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي عاصمة البرتغال؟', 'a' => 'بورتو', 'b' => 'لشبونة', 'c' => 'براغا', 'd' => 'كيمبرا', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي عاصمة هولندا؟', 'a' => 'روتردام', 'b' => 'أمستردام', 'c' => 'لاهاي', 'd' => 'أوترخت', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي عاصمة السويد؟', 'a' => 'غوتنبرغ', 'b' => 'ستوكهولم', 'c' => 'مالمو', 'd' => 'أوبسالا', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي عاصمة النرويج؟', 'a' => 'برغن', 'b' => 'أوسلو', 'c' => 'ترومسو', 'd' => 'ستافانغر', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي عاصمة الدنمارك؟', 'a' => 'أرهوس', 'b' => 'كوبنهاغن', 'c' => 'أودنسه', 'd' => 'آلبورغ', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي عاصمة بولندا؟', 'a' => 'كراكوف', 'b' => 'وارسو', 'c' => 'غدانسك', 'd' => 'فروتسواف', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي عاصمة النمسا؟', 'a' => 'سالزبورغ', 'b' => 'فيينا', 'c' => 'غراتس', 'd' => 'لينتس', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي عاصمة سويسرا؟', 'a' => 'زيورخ', 'b' => 'برن', 'c' => 'جنيف', 'd' => 'بازل', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي عاصمة اليونان؟', 'a' => 'سالونيك', 'b' => 'أثينا', 'c' => 'باتراس', 'd' => 'هيراكليون', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'medium', 'question' => 'ما هي عاصمة بلجيكا؟', 'a' => 'بروج', 'b' => 'بروكسل', 'c' => 'أنتويرب', 'd' => 'غنت', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'hard', 'question' => 'كم نجمة في علم الصين؟', 'a' => '4 نجوم', 'b' => '5 نجوم', 'c' => '3 نجوم', 'd' => '6 نجوم', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'hard', 'question' => 'أي دولة علمها أحمر بالكامل مع دائرة بيضاء في المنتصف؟', 'a' => 'تركيا', 'b' => 'اليابان', 'c' => 'تونس', 'd' => 'بنغلاديش', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'hard', 'question' => 'أي دولة علمها يضم ورقة قيقب (maple leaf)؟', 'a' => 'الولايات المتحدة', 'b' => 'كندا', 'c' => 'بريطانيا', 'd' => 'أستراليا', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'hard', 'question' => 'كم عدد الألوان في علم جنوب أفريقيا؟', 'a' => '4', 'b' => '6', 'c' => '5', 'd' => '7', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'hard', 'question' => 'أي دولة علمها أحمر وأبيض وأخضر مع نجم أحمر في المنتصف؟', 'a' => 'المغرب', 'b' => 'الجزائر', 'c' => 'سوريا', 'd' => 'تونس', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'hard', 'question' => 'أي دولة علمها أحمر وأبيض فقط، ويتكون من صليبين متقاطعين؟', 'a' => 'النرويج', 'b' => 'الدنمارك', 'c' => 'سويسرا', 'd' => 'فنلندا', 'correct' => 'c'],
    ['category' => 'capitals', 'difficulty' => 'hard', 'question' => 'أي دولة علمها أخضر بالكامل مع هلال وثلاث نجوم؟', 'a' => 'باكستان', 'b' => 'بنغلاديش', 'c' => 'الجزائر', 'd' => 'موريتانيا', 'correct' => 'a'],
    ['category' => 'capitals', 'difficulty' => 'hard', 'question' => 'أي دولة لها علم ثنائي اللون أزرق وأبيض مع شعار النبالة؟', 'a' => 'اليونان', 'b' => 'فنلندا', 'c' => 'إسرائيل', 'd' => 'الأرجنتين', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'hard', 'question' => 'كم عدد النجوم في علم الولايات المتحدة الأمريكية؟', 'a' => '48', 'b' => '50', 'c' => '52', 'd' => '49', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'hard', 'question' => 'كم عدد الخطوط الحمراء والبيضاء في علم الولايات المتحدة؟', 'a' => '12', 'b' => '13', 'c' => '11', 'd' => '14', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'hard', 'question' => 'أي دولة علمها ثلاثي الألوان: أحمر وأصفر وأخضر (أفقي)؟', 'a' => 'المجر', 'b' => 'ليتوانيا', 'c' => 'بلغاريا', 'd' => 'ألمانيا', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'hard', 'question' => 'ما هي عاصمة أوكرانيا؟', 'a' => 'لفيف', 'b' => 'كييف', 'c' => 'أوديسا', 'd' => 'خاركيف', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'hard', 'question' => 'ما هي عاصمة تايلاند؟', 'a' => 'شيانغ ماي', 'b' => 'بانكوك', 'c' => 'بوكيت', 'd' => 'باتايا', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'hard', 'question' => 'ما هي عاصمة فيتنام؟', 'a' => 'مدينة هو تشي منه', 'b' => 'هانوي', 'c' => 'دا نانغ', 'd' => 'هايفونغ', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'hard', 'question' => 'ما هي عاصمة الفلبين؟', 'a' => 'سيبو', 'b' => 'مانيلا', 'c' => 'دافاو', 'd' => 'بوراكاي', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'hard', 'question' => 'ما هي عاصمة إندونيسيا؟', 'a' => 'بالاي', 'b' => 'جاكرتا', 'c' => 'باندونغ', 'd' => 'سورابايا', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'hard', 'question' => 'ما هي عاصمة ماليزيا؟', 'a' => 'كوالالمبور', 'b' => 'جورج تاون', 'c' => 'جوهور باهرو', 'd' => 'إيبوه', 'correct' => 'a'],
    ['category' => 'capitals', 'difficulty' => 'hard', 'question' => 'ما هي عاصمة كوريا الجنوبية؟', 'a' => 'بوسان', 'b' => 'سول', 'c' => 'إنتشون', 'd' => 'ديغو', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'hard', 'question' => 'ما هي عاصمة كولومبيا؟', 'a' => 'ميديلين', 'b' => 'بوغوتا', 'c' => 'كالي', 'd' => 'بارانكويلا', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'hard', 'question' => 'ما هي عاصمة بيرو؟', 'a' => 'كوسكو', 'b' => 'ليما', 'c' => 'أريكويبا', 'd' => 'تروجيلو', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'hard', 'question' => 'ما هي عاصمة تشيلي؟', 'a' => 'فالبارايسو', 'b' => 'سانتياغو', 'c' => 'كونثبثيون', 'd' => 'لا سيرينا', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'hard', 'question' => 'ما هي عاصمة نيجيريا؟', 'a' => 'لاغوس', 'b' => 'أبوجا', 'c' => 'كانو', 'd' => 'إبادان', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'hard', 'question' => 'ما هي عاصمة إثيوبيا؟', 'a' => 'أديس أبابا', 'b' => 'ديرة داوا', 'c' => 'هرر', 'd' => 'بحر دار', 'correct' => 'a'],
    ['category' => 'capitals', 'difficulty' => 'hard', 'question' => 'ما هي عاصمة كينيا؟', 'a' => 'مومباسا', 'b' => 'نيروبي', 'c' => 'كسومو', 'd' => 'ناكورو', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'hard', 'question' => 'ما هي عاصمة تنزانيا؟', 'a' => 'دار السلام', 'b' => 'دودوما', 'c' => 'أروشا', 'd' => 'موانزا', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'hard', 'question' => 'ما هي عاصمة أنغولا؟', 'a' => 'لواندا', 'b' => 'هوامبو', 'c' => 'بنغيلا', 'd' => 'لوبيتو', 'correct' => 'a'],
    ['category' => 'capitals', 'difficulty' => 'hard', 'question' => 'أي دولة هي الأطول في العالم من الشمال إلى الجنوب؟', 'a' => 'روسيا', 'b' => 'تشيلي', 'c' => 'البرازيل', 'd' => 'كندا', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'hard', 'question' => 'أي دولة هي الأكثر كثافة سكانية في العالم؟', 'a' => 'سنغافورة', 'b' => 'موناكو', 'c' => 'هونغ كونغ', 'd' => 'البحرين', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'أي دولة في العالم هي الوحيدة التي لا يوجد بها نهر؟', 'a' => 'ليبيا', 'b' => 'السعودية', 'c' => 'الكويت', 'd' => 'اليمن', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'كم عدد الدول التي تمر عبر خط الاستواء؟', 'a' => '10', 'b' => '13', 'c' => '11', 'd' => '15', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'ما هي الدولة الوحيدة في العالم التي تمتلك علماً غير مستطيل؟', 'a' => 'سويسرا', 'b' => 'نيبال', 'c' => 'الفاتيكان', 'd' => 'قطر', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'أي دولة هي الدولة الوحيدة التي علمها يظهر على علم دولة أخرى؟', 'a' => 'المملكة المتحدة', 'b' => 'فرنسا', 'c' => 'البرتغال', 'd' => 'إسبانيا', 'correct' => 'a'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'ما هي الدولة الوحيدة التي يظهر اسمها على علمها؟', 'a' => 'السعودية', 'b' => 'العراق', 'c' => 'إيران', 'd' => 'أفغانستان', 'correct' => 'a'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'أي دولة لديها أطول حدود برية في العالم؟', 'a' => 'روسيا', 'b' => 'كندا', 'c' => 'الصين', 'd' => 'البرازيل', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'كم عدد الدول التي تتحدث العربية كلغة رسمية؟', 'a' => '18', 'b' => '22', 'c' => '25', 'd' => '20', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'أي دولة هي الدولة الوحيدة التي لا يوجد بها مطار؟', 'a' => 'الفاتيكان', 'b' => 'موناكو', 'c' => 'سان مارينو', 'd' => 'ليختنشتاين', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'أي دولة في أمريكا الجنوبية لا تطل على البحر؟', 'a' => 'بوليفيا', 'b' => 'باراغواي', 'c' => 'كلتاهما', 'd' => 'الأوروغواي', 'correct' => 'c'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'أي دولة علمها هو الوحيد الذي ليس له شكل رباعي في العالم؟', 'a' => 'سويسرا', 'b' => 'نيبال', 'c' => 'سلوفينيا', 'd' => 'فيجي', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'ما هي العاصمة الوحيدة في العالم التي تقع على قارتين؟', 'a' => 'إسطنبول', 'b' => 'موسكو', 'c' => 'باريس', 'd' => 'لندن', 'correct' => 'a'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'ما هي عاصمة ميانمار (بورما)؟', 'a' => 'يانغون', 'b' => 'نايبيداو', 'c' => 'ماندالاي', 'd' => 'باغان', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'ما هي عاصمة كازاخستان؟', 'a' => 'ألماتي', 'b' => 'نور سلطان (أستانا)', 'c' => 'قراغندي', 'd' => 'شيمكنت', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'ما هي عاصمة أذربيجان؟', 'a' => 'باكو', 'b' => 'كنجه', 'c' => 'ناختشيفان', 'd' => 'سومقاييت', 'correct' => 'a'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'ما هي عاصمة كرواتيا؟', 'a' => 'سبليت', 'b' => 'زغرب', 'c' => 'دوبروفنيك', 'd' => 'رييكا', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'ما هي عاصمة رومانيا؟', 'a' => 'كلوج نابوكا', 'b' => 'بوخارست', 'c' => 'تيميشوارا', 'd' => 'براشوف', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'ما هي عاصمة صربيا؟', 'a' => 'نوفي ساد', 'b' => 'بلغراد', 'c' => 'نيش', 'd' => 'سوبوتيتسا', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'كم عدد الدول التي لديها أقاليم في القارة القطبية الجنوبية؟', 'a' => '5', 'b' => '7', 'c' => '6', 'd' => '8', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'أي دولة هي الدولة الوحيدة في العالم التي لا توجد بها غابات؟', 'a' => 'مصر', 'b' => 'السعودية', 'c' => 'ليبيا', 'd' => 'اليمن', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'أي دولة في أفريقيا هي الوحيدة التي لم تستعمر أبداً؟', 'a' => 'إثيوبيا', 'b' => 'ليبيريا', 'c' => 'الصومال', 'd' => 'السودان', 'correct' => 'a'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'كم عدد الجزر في إندونيسيا؟', 'a' => 'أكثر من 5000', 'b' => 'أكثر من 13000', 'c' => 'أكثر من 17000', 'd' => 'أكثر من 20000', 'correct' => 'c'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'ما هي المدينة الأكثر اكتظاظاً بالسكان في أفريقيا؟', 'a' => 'القاهرة', 'b' => 'لاغوس', 'c' => 'جوهانسبرغ', 'd' => 'نيروبي', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'أي دولة في العالم هي ثاني أكبر دولة من حيث المساحة؟', 'a' => 'الصين', 'b' => 'الولايات المتحدة', 'c' => 'كندا', 'd' => 'البرازيل', 'correct' => 'c'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'ما هي الدولة العربية الوحيدة التي تقع على الخليج العربي والمحيط الهندي؟', 'a' => 'السعودية', 'b' => 'الإمارات', 'c' => 'عمان', 'd' => 'اليمن', 'correct' => 'c'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'أي دولة في العالم تملك أطول ساحل بحري؟', 'a' => 'أستراليا', 'b' => 'كندا', 'c' => 'روسيا', 'd' => 'إندونيسيا', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'كم عدد المناطق الزمنية في روسيا؟', 'a' => '9', 'b' => '11', 'c' => '10', 'd' => '12', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'أي دولة أوروبية هي الوحيدة التي ليس لها عاصمة رسمية؟', 'a' => 'مالطا', 'b' => 'سويسرا', 'c' => 'هولندا', 'd' => 'لوكسمبورغ', 'correct' => 'c'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'أي دولة هي الدولة الوحيدة التي علمها مختلف الوجهين؟', 'a' => 'أمريكا', 'b' => 'روسيا', 'c' => 'باراغواي', 'd' => 'الهند', 'correct' => 'c'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'كم عدد الدول التي تمر عبر قناة السويس؟', 'a' => '2', 'b' => '0', 'c' => '1', 'd' => '3', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'أي دولة تملك أكبر احتياطي نفط في العالم؟', 'a' => 'السعودية', 'b' => 'فنزويلا', 'c' => 'العراق', 'd' => 'الكويت', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'ما هي أقدم عاصمة في العالم لا تزال مأهولة؟', 'a' => 'أثينا', 'b' => 'دمشق', 'c' => 'روما', 'd' => 'بكين', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'ما هي الدولة الوحيدة في العالم التي لا تملك جيشاً؟', 'a' => 'سويسرا', 'b' => 'كوستاريكا', 'c' => 'النمسا', 'd' => 'السويد', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'كم عدد الدول في شبه الجزيرة العربية؟', 'a' => '5', 'b' => '7', 'c' => '6', 'd' => '8', 'correct' => 'b'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'أي دولة هي الأقرب إلى خط التاريخ الدولي من الشرق؟', 'a' => 'اليابان', 'b' => 'نيوزيلندا', 'c' => 'فيجي', 'd' => 'أستراليا', 'correct' => 'c'],
    ['category' => 'capitals', 'difficulty' => 'very_hard', 'question' => 'ما هي عاصمة سلوفاكيا؟', 'a' => 'براتيسلافا', 'b' => 'كوشيتسا', 'c' => 'براغ', 'd' => 'بودابست', 'correct' => 'a'],
];
