<?php

return [
    [
        'category' => 'disney-characters',
        'difficulty' => 'medium',
        'question' => 'ما هو اسم الأميرة التي تعيش مع سبعة أقزام؟',
        'a' => 'سندريلا',
        'b' => 'سنو وايت',
        'c' => 'رابونزل',
        'd' => 'أورورا',
        'correct' => 'b',
    ],
    [
        'category' => 'disney-characters',
        'difficulty' => 'medium',
        'question' => 'من هو الشخصية الرئيسية في فيلم "The Lion King"؟',
        'a' => 'موفاسا',
        'b' => 'سيمبا',
        'c' => 'سكار',
        'd' => 'تيمون',
        'correct' => 'b',
    ],
    [
        'category' => 'disney-characters',
        'difficulty' => 'medium',
        'question' => 'ما هو اسم الفتاة التي تزور عالم العجائب في فيلم ديزني؟',
        'a' => 'أليس',
        'b' => 'ماري',
        'c' => 'ويندي',
        'd' => 'جين',
        'correct' => 'a',
    ],
    [
        'category' => 'disney-characters',
        'difficulty' => 'hard',
        'question' => 'ما هو اسم البطريق الصغير في فيلم "Mary Poppins"؟',
        'a' => 'بينغو',
        'b' => 'داني',
        'c' => 'بين',
        'd' => 'بيني',
        'correct' => 'd',
    ],
    [
        'category' => 'disney-characters',
        'difficulty' => 'hard',
        'question' => 'في أي عام صدر فيلم "Beauty and the Beast" الأصلي؟',
        'a' => '1989',
        'b' => '1991',
        'c' => '1992',
        'd' => '1990',
        'correct' => 'b',
    ],
    [
        'category' => 'disney-characters',
        'difficulty' => 'hard',
        'question' => 'من هي الشريرة الرئيسية في فيلم "Sleeping Beauty"؟',
        'a' => 'ملكة الثلج',
        'b' => 'الساحرة الشريرة',
        'c' => 'ماليفسينت',
        'd' => 'المرأة العجوز',
        'correct' => 'c',
    ],
    [
        'category' => 'disney-characters',
        'difficulty' => 'very_hard',
        'question' => 'ما هو اسم سمكة القرش في فيلم "Finding Nemo"؟',
        'a' => 'بروس',
        'b' => 'تشامب',
        'c' => 'جوزيف',
        'd' => 'ريكس',
        'correct' => 'a',
    ],
    [
        'category' => 'disney-characters',
        'difficulty' => 'very_hard',
        'question' => 'كم عدد الأفلام الرسمية في سلسلة "Disney Princess" الكلاسيكية؟',
        'a' => '10',
        'b' => '11',
        'c' => '12',
        'd' => '9',
        'correct' => 'c',
    ],
    [
        'category' => 'disney-characters',
        'difficulty' => 'very_hard',
        'question' => 'ما هو اسم الكلب المخلص في فيلم "Up"؟',
        'a' => 'دوج',
        'b' => 'ماكس',
        'c' => 'كيفن',
        'd' => 'روفوس',
        'correct' => 'a',
    ],
    [
        'category' => 'disney-characters',
        'difficulty' => 'medium',
        'question' => 'من هو أمير ديزني الذي يظهر في فيلم "Aladdin"؟',
        'a' => 'فليب',
        'b' => 'نافين',
        'c' => 'علاء الدين',
        'd' => 'تشارمينغ',
        'correct' => 'c',
    ],
];
