<?php
return [
    [
        'category' => 'football-stadiums',
        'difficulty' => 'medium',
        'question' => 'ما هو أكبر ملعب كرة قدم في العالم من حيث السعة؟',
        'a' => 'كامب نو',
        'b' => 'ملعب رونغدو الأول',
        'c' => 'ويمبلي',
        'd' => 'سانتياغو برنابيو',
        'correct' => 'b',
    ],
    [
        'category' => 'football-stadiums',
        'difficulty' => 'medium',
        'question' => 'ما اسم ملعب نادي برشلونة الشهير؟',
        'a' => 'سانتياغو برنابيو',
        'b' => 'كامب نو',
        'c' => 'أولد ترافورد',
        'd' => 'أنفيلد',
        'correct' => 'b',
    ],
    [
        'category' => 'football-stadiums',
        'difficulty' => 'medium',
        'question' => 'ما هو ملعب منتخب إنجلترا الوطني لكرة القدم؟',
        'a' => 'ويمبلي',
        'b' => 'أولد ترافورد',
        'c' => 'ستامفورد بريدج',
        'd' => 'الإمارات',
        'correct' => 'a',
    ],
    [
        'category' => 'football-stadiums',
        'difficulty' => 'hard',
        'question' => 'ما اسم ملعب نادي ريال مدريد؟',
        'a' => 'كامب نو',
        'b' => 'سانتياغو برنابيو',
        'c' => 'فيسنتي كالديرون',
        'd' => 'رامون سانشيز بيزخوان',
        'correct' => 'b',
    ],
    [
        'category' => 'football-stadiums',
        'difficulty' => 'hard',
        'question' => 'في أي مدينة يقع ملعب سان سيرو (جوزيبي مياتسا)؟',
        'a' => 'روما',
        'b' => 'ميلانو',
        'c' => 'تورينو',
        'd' => 'نابولي',
        'correct' => 'b',
    ],
    [
        'category' => 'football-stadiums',
        'difficulty' => 'hard',
        'question' => 'ما هو الملعب الذي استضاف نهائي كأس العالم 2022 في قطر؟',
        'a' => 'ملعب لوسيل',
        'b' => 'ملعب البيت',
        'c' => 'ملعب الثمامة',
        'd' => 'استاد خليفة الدولي',
        'correct' => 'a',
    ],
    [
        'category' => 'football-stadiums',
        'difficulty' => 'very_hard',
        'question' => 'ما اسم ملعب نادي مانشستر يونايتد؟',
        'a' => 'الاتحاد',
        'b' => 'أولد ترافورد',
        'c' => 'ستاد سيتي أوف مانشستر',
        'd' => 'أنفيلد',
        'correct' => 'b',
    ],
    [
        'category' => 'football-stadiums',
        'difficulty' => 'very_hard',
        'question' => 'كم تبلغ السعة التخمينية لملعب كامب نو قبل تجديده الأخير؟',
        'a' => 'حوالي 99 ألف متفرج',
        'b' => 'حوالي 80 ألف متفرج',
        'c' => 'حوالي 90 ألف متفرج',
        'd' => 'حوالي 105 آلاف متفرج',
        'correct' => 'a',
    ],
    [
        'category' => 'football-stadiums',
        'difficulty' => 'very_hard',
        'question' => 'ما اسم الملعب الذي يُطلق عليه لقب "مسرح الأحلام"؟',
        'a' => 'ويمبلي',
        'b' => 'أولد ترافورد',
        'c' => 'سانتياغو برنابيو',
        'd' => 'كامب نو',
        'correct' => 'b',
    ],
    [
        'category' => 'football-stadiums',
        'difficulty' => 'very_hard',
        'question' => 'في أي دولة يقع ملعب "سيغنال إيدونا بارك" (سيغنال إيدونا)؟',
        'a' => 'إيطاليا',
        'b' => 'ألمانيا',
        'c' => 'إسبانيا',
        'd' => 'فرنسا',
        'correct' => 'b',
    ],
];
