<?php
return [
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'ما هو اسم البطل الرئيسي في سلسلة The Legend of Zelda؟',
        'a' => 'زيلدا',
        'b' => 'لينك',
        'c' => 'غانون',
        'd' => 'نافي',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'أي شركة طورت لعبة The Last of Us؟',
        'a' => 'CD Projekt Red',
        'b' => 'Naughty Dog',
        'c' => 'Rockstar Games',
        'd' => 'Insomniac',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'ما هو اسم الشخصية الرئيسية في سلسلة God of War الأصلية؟',
        'a' => 'كريتوس',
        'b' => 'أتريوس',
        'c' => 'زيوس',
        'd' => 'أريس',
        'correct' => 'a',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'ما هي اللعبة التي تدور أحداثها في مدينة "Night City"؟',
        'a' => 'GTA V',
        'b' => 'Cyberpunk 2077',
        'c' => 'Watch Dogs',
        'd' => 'Deus Ex',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'ما هي أكثر لعبة مبيعاً في تاريخ ألعاب الفيديو حتى 2024؟',
        'a' => 'GTA V',
        'b' => 'Tetris',
        'c' => 'Minecraft',
        'd' => 'Mario Kart',
        'correct' => 'c',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'ما هي لعبة Battle Royale الأكثر شعبية في 2023؟',
        'a' => 'PUBG',
        'b' => 'Apex Legends',
        'c' => 'Fortnite',
        'd' => 'Warzone',
        'correct' => 'c',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'في أي لعبة ظهرت شخصية "Master Chief" لأول مرة؟',
        'a' => 'Halo 2',
        'b' => 'Halo: Combat Evolved',
        'c' => 'Halo 3',
        'd' => 'Halo Reach',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'ما هو اسم الشركة المطورة للعبة Grand Theft Auto؟',
        'a' => 'Ubisoft',
        'b' => 'Rockstar Games',
        'c' => 'EA',
        'd' => 'Activision',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'من هو مبتكر سلسلة Metal Gear Solid؟',
        'a' => 'هيديو كوجيما',
        'b' => 'شينجي ميكامي',
        'c' => 'فوميتو أويدا',
        'd' => 'تومويوكي هوشينو',
        'correct' => 'a',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'أي شركة تُصنع جهاز PlayStation؟',
        'a' => 'Microsoft',
        'b' => 'Nintendo',
        'c' => 'Sony',
        'd' => 'Sega',
        'correct' => 'c',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'ما هي لعبة المنصات الأشهر من Nintendo والتي تظهر فيها شخصية أنبوب سباك؟',
        'a' => 'Sonic',
        'b' => 'Mario',
        'c' => 'Megaman',
        'd' => 'Crash Bandicoot',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'في أي عام صدرت لعبة PUBG لأول مرة؟',
        'a' => '2015',
        'b' => '2017',
        'c' => '2018',
        'd' => '2016',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'أي لعبة فازت بجائزة Game of the Year 2023؟',
        'a' => 'Baldur\'s Gate 3',
        'b' => 'Hogwarts Legacy',
        'c' => 'The Legend of Zelda: Tears of the Kingdom',
        'd' => 'Alan Wake 2',
        'correct' => 'a',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'ما هو نوع لعبة FIFA؟',
        'a' => 'سباق',
        'b' => 'رياضة كرة قدم',
        'c' => 'تصويب',
        'd' => 'استراتيجية',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'ما هو اسم بطل سلسلة God of War الحديث من 2018؟',
        'a' => 'كريتوس وأتريوس',
        'b' => 'أتريوس فقط',
        'c' => 'فريا',
        'd' => 'ثور',
        'correct' => 'a',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'أي لعبة من التالية هي من نوع Open World؟',
        'a' => 'Pac-Man',
        'b' => 'Tetris',
        'c' => 'The Witcher 3',
        'd' => 'Street Fighter',
        'correct' => 'c',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'ما اسم أول جهاز ألعاب منزلي من Nintendo؟',
        'a' => 'Game Boy',
        'b' => 'NES',
        'c' => 'SNES',
        'd' => 'Nintendo 64',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'من هي شركة التطوير وراء لعبة The Witcher 3؟',
        'a' => 'Ubisoft',
        'b' => 'CD Projekt Red',
        'c' => 'Bethesda',
        'd' => 'BioWare',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'في أي لعبة نتحكم بشخصية "Doom Slayer"؟',
        'a' => 'Doom',
        'b' => 'Quake',
        'c' => 'Wolfenstein',
        'd' => 'Half-Life',
        'correct' => 'a',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'ما هو نوع لعبة Civilization؟',
        'a' => 'تصويب',
        'b' => 'استراتيجية تناوب الأدوار',
        'c' => 'منصات',
        'd' => 'رياضة',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'أي لعبة بدأت سلسلة Assassin\'s Creed؟',
        'a' => 'Assassin\'s Creed II',
        'b' => 'Assassin\'s Creed Brotherhood',
        'c' => 'Assassin\'s Creed',
        'd' => 'Assassin\'s Creed Revelations',
        'correct' => 'c',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'ما هي أشهر لعبة من نوع Battle Royale من إنتاج Epic Games؟',
        'a' => 'PUBG',
        'b' => 'Fortnite',
        'c' => 'Apex Legends',
        'd' => 'Call of Duty Warzone',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'كم عدد أزرار التحكم الرئيسية في يد تحكم PlayStation DualSense؟',
        'a' => '12',
        'b' => '14',
        'c' => '16',
        'd' => '10',
        'correct' => 'c',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'ما الاسم الرسمي لجهاز نينتندو المحمول الذي صدر عام 2017؟',
        'a' => 'Nintendo Switch',
        'b' => 'Nintendo 3DS',
        'c' => 'Nintendo Wii U',
        'd' => 'Nintendo DS',
        'correct' => 'a',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'من هو الشخصية الرئيسية في لعبة Horizon Zero Dawn؟',
        'a' => 'إيلوي',
        'b' => 'لاي',
        'c' => 'كلوي',
        'd' => 'تيسا',
        'correct' => 'a',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'في أي سنة تأسست شركة Nintendo؟',
        'a' => '1889',
        'b' => '1925',
        'c' => '1950',
        'd' => '1972',
        'correct' => 'a',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'ما هي اللعبة التي بدأت نوع "Battle Royale" الحديث؟',
        'a' => 'Fortnite',
        'b' => 'PUBG',
        'c' => 'H1Z1',
        'd' => 'Minecraft Hunger Games',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'ما هو اسم عالم لعبة The Legend of Zelda: Breath of the Wild؟',
        'a' => 'Morrowind',
        'b' => 'Hyrule',
        'c' => 'Tamriel',
        'd' => 'Zelda',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'أي لعبة تُعتبر أول لعبة فيديو في التاريخ؟',
        'a' => 'Pong',
        'b' => 'Spacewar!',
        'c' => 'Tennis for Two',
        'd' => 'Computer Space',
        'correct' => 'c',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'من هو مبتكر لعبة Minecraft؟',
        'a' => 'نوتش (ماركوس بيرسون)',
        'b' => 'هيروبرين',
        'c' => 'ستيف جوبز',
        'd' => 'بيل غيتس',
        'correct' => 'a',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'ما هو اسم بطل سلسلة Uncharted؟',
        'a' => 'دريك',
        'b' => 'ناثان دريك',
        'c' => 'سام دريك',
        'd' => 'سالي',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'أي لعبة من السلسلة التالية تتبع أسلوب RPG؟',
        'a' => 'Call of Duty',
        'b' => 'FIFA',
        'c' => 'Skyrim',
        'd' => 'Forza',
        'correct' => 'c',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'medium',
        'question' => 'ما اسم المنصة الرقمية لتوزيع الألعاب من Valve؟',
        'a' => 'Epic Games Store',
        'b' => 'Steam',
        'c' => 'GOG',
        'd' => 'Origin',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'hard',
        'question' => 'ما هو نظام "Soulslike" في الألعاب ومن أسسه؟',
        'a' => 'نظام RPG ياباني - وهو محل اهتمام الباحثين',
        'b' => 'نوع ألعاب ذو صعوبة عالية طوّره هيدتاكا مياظاكي في FromSoftware',
        'c' => 'ألعاب هروب - وهو ما تؤكده الأدلة المتوفرة',
        'd' => 'ألعاب منصات - وقد نوقش في العديد من المراجع',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'hard',
        'question' => 'ما هو مفهوم "MOBA" وما اللعبتان الأكثر شهرة؟',
        'a' => 'ألعاب إطلاق نار - ويرتبط بمفاهيم أخرى مهمة',
        'b' => 'Multiplayer Online Battle Arena، أشهرها Dota 2 وLeague of Legends',
        'c' => 'ألعاب استراتيجية - وقد نوقش في العديد من المراجع',
        'd' => 'ألعاب سباق - وله تطبيقات عملية متعددة, وهذا يعتبر من المسلمات في هذا المجال',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'hard',
        'question' => 'ما هو "Elden Ring" ومن هو كاتب عالمه؟',
        'a' => 'لعبة سباق - وله تطبيقات عملية متعددة, وقد تم التحقق منه عبر تجارب متعددة',
        'b' => 'لعبة RPG من FromSoftware، كتب عالمها جورج R.R. مارتن مع مياظاكي',
        'c' => 'لعبة بقاء - ويرتبط بمفاهيم أخرى مهمة, ويرتبط بشكل وثيق بموضوعات أخرى',
        'd' => 'أكشن من Ubisoft - وقد نوقش في العديد من المراجع',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'hard',
        'question' => 'ما هي أزمة "Video Game Crash 1983" وما سببها الرئيسي؟',
        'a' => 'انهيار Nintendo - وهو ما تؤكده الأدلة المتوفرة',
        'b' => 'إغراق السوق بألعاب رديئة وانهيار الثقة في الصناعة',
        'c' => 'أزمة اقتصادية عالمية - وقد أيدته دراسات عديدة موثوقة',
        'd' => 'حرائق المصانع - ويرتبط بمفاهيم أخرى مهمة',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'hard',
        'question' => 'في لعبة Hollow Knight، ما هو التفسير لحقيقة "Pure Vessel" ودوره في القصة؟',
        'a' => 'العدو الرئيسي - وهو محل اهتمام الباحثين',
        'b' => 'نسخة مثالية من Hollow Knight خُلق لاحتواء العدوى لكنه فشل',
        'c' => 'ملك قديم - وقد ساهم في تطور المعرفة, وقد أسهم بشكل كبير في تطور المعرفة',
        'd' => 'شخصية قابلة للعب - وهو ما تؤكده الأدلة المتوفرة',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'hard',
        'question' => 'ما الفرق بين Ray Tracing و Rasterization في رسومات الألعاب؟',
        'a' => 'لا فرق - وله دور محوري في السياق العام, وهو أحد المحاور الأساسية في هذا السياق',
        'b' => 'Ray Tracing يحاكي الضوء طبيعياً وRasterization يحول المضلعات إلى بكسلات',
        'c' => 'الأول للألعاب والثاني للأفلام - وله تطبيقات عملية متعددة',
        'd' => 'الأفضل دائماً هو Rasterization - وهو مفهوم أساسي في هذا المجال',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'hard',
        'question' => 'ما هي لعبة "Dark Souls" الأولى ومن طورها؟',
        'a' => 'طورتها Ubisoft - وهو موضوع ذو أهمية كبيرة',
        'b' => 'طورتها FromSoftware وأخرجها هيدتاكا مياظاكي عام 2011',
        'c' => 'طورتها Capcom - وهو محل اهتمام الباحثين',
        'd' => 'طورتها Square Enix - وهو موضوع ذو أهمية كبيرة',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'hard',
        'question' => 'ما هو محرك الألعاب الذي طورته Epic Games؟',
        'a' => 'Unity',
        'b' => 'Unreal Engine',
        'c' => 'Frostbite',
        'd' => 'Source',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'hard',
        'question' => 'أي شركة تمتلك علامة Xbox الآن؟',
        'a' => 'Sony',
        'b' => 'Microsoft',
        'c' => 'Nintendo',
        'd' => 'Sega',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'hard',
        'question' => 'من هو مبتكر شخصية Sonic the Hedgehog؟',
        'a' => 'شينجي ميكامي',
        'b' => 'يوجي ناكا',
        'c' => 'ساتورو إواتا',
        'd' => 'غونبي يوكوي',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'hard',
        'question' => 'ما هو اسم أول جهاز ألعاب من سوني بلايستيشن؟',
        'a' => 'PlayStation 2',
        'b' => 'PlayStation 1',
        'c' => 'PlayStation 3',
        'd' => 'PlayStation Portable',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'hard',
        'question' => 'في لعبة Overwatch، ما هو نوع اللعبة؟',
        'a' => 'Battle Royale',
        'b' => 'Hero Shooter',
        'c' => 'MOBA',
        'd' => 'RTS',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'hard',
        'question' => 'ما هي سلسلة الألعاب التي أسست نوع Stealth Action؟',
        'a' => 'Assassin\'s Creed',
        'b' => 'Metal Gear Solid',
        'c' => 'Hitman',
        'd' => 'Thief',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'hard',
        'question' => 'أي لعبة حققت أعلى إيرادات في يوم إطلاقها على الإطلاق؟',
        'a' => 'GTA V',
        'b' => 'Red Dead Redemption 2',
        'c' => 'Call of Duty: Modern Warfare 2',
        'd' => 'Cyberpunk 2077',
        'correct' => 'a',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'hard',
        'question' => 'ما هي تقنية DLSS من NVIDIA؟',
        'a' => 'تقنية رفع الدقة بالذكاء الاصطناعي',
        'b' => 'تقنية تتبع الأشعة',
        'c' => 'بطاقة رسومات',
        'd' => 'برنامج تحرير فيديو',
        'correct' => 'a',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'hard',
        'question' => 'ما هي السلسلة التي بدأت نوع "Survival Horror" في الألعاب؟',
        'a' => 'Resident Evil',
        'b' => 'Silent Hill',
        'c' => 'Dead Space',
        'd' => 'Alone in the Dark',
        'correct' => 'a',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'hard',
        'question' => 'ما معنى مصطلح "Roguelike" في الألعاب؟',
        'a' => 'ألعاب ألغاز - وله تطبيقات عملية متعددة',
        'b' => 'ألعاب ذات موت دائم ومستويات عشوائية مستوحاة من Rogue',
        'c' => 'ألعاب منصات - وهو محل اهتمام الباحثين',
        'd' => 'ألعاب قتال - وهو مفهوم أساسي في هذا المجال',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'hard',
        'question' => 'ما هي الشركة المطورة للعبة Red Dead Redemption 2؟',
        'a' => 'Rockstar North',
        'b' => 'Rockstar San Diego',
        'c' => 'Rockstar Studios',
        'd' => 'Rockstar London',
        'correct' => 'c',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'hard',
        'question' => 'ما هو نظام "NG+" في الألعاب؟',
        'a' => 'New Game Plus، إعادة اللعبة مع الاحتفاظ بالتطور',
        'b' => 'نسخة محدثة من اللعبة - وله تطبيقات عملية متعددة',
        'c' => 'وضع متعدد اللاعبين - وله دور محوري في السياق العام',
        'd' => 'حزمة توسعة - وقد أيدته دراسات عديدة موثوقة',
        'correct' => 'a',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'hard',
        'question' => 'ما هي لعبة "Half-Life" ومن الشركة المطورة؟',
        'a' => 'طورتها id Software - وهو ما تؤكده الأدلة المتوفرة',
        'b' => 'طورتها Valve عام 1998 وأحدثت ثورة في تصويب FPS',
        'c' => 'طورتها Bungie - وقد ساهم في تطور المعرفة',
        'd' => 'طورتها 3D Realms - وله دور محوري في السياق العام',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'hard',
        'question' => 'في أي عام صدر أول جهاز Xbox؟',
        'a' => '1999',
        'b' => '2001',
        'c' => '2002',
        'd' => '2000',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'hard',
        'question' => 'ما الفرق بين لعبة MMO و MOBA؟',
        'a' => 'الأولى جماعية ضخمة متصلة والثانية ساحة معركة متعددة اللاعبين',
        'b' => 'لا فرق - وقد نوقش في العديد من المراجع, وقد أسهم بشكل كبير في تطور المعرفة',
        'c' => 'الأولى فردية - وهو محل اهتمام الباحثين, وقد أسهم بشكل كبير في تطور المعرفة',
        'd' => 'كلاهما نفس النوع - وله تطبيقات عملية متعددة',
        'correct' => 'a',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'hard',
        'question' => 'ما هو اسم البطل الرئيسي في لعبة Sekiro: Shadows Die Twice؟',
        'a' => 'Wolf',
        'b' => 'Sekiro',
        'c' => 'Isshin',
        'd' => 'Genichiro',
        'correct' => 'a',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'hard',
        'question' => 'من هي الشركة المطورة للعبة "Stardew Valley"؟',
        'a' => 'Mojang',
        'b' => 'ConcernedApe (مطور فردي)',
        'c' => 'Square Enix',
        'd' => 'Nintendo',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'hard',
        'question' => 'ما هو النظام الأساسي الذي تجري عليه مسابقات League of Legends؟',
        'a' => 'Battle.net',
        'b' => 'Steam',
        'c' => 'Uplay',
        'd' => 'منصة Riot Games',
        'correct' => 'd',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'hard',
        'question' => 'أي لعبة تُعتبر أول لعبة تستخدم تقنية Three-dimensional (3D) بشكل كامل؟',
        'a' => 'Super Mario 64',
        'b' => 'Wolfenstein 3D',
        'c' => 'Quake',
        'd' => 'Tomb Raider',
        'correct' => 'a',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'hard',
        'question' => 'ما هي أقوى بطاقة رسوميات للألعاب من NVIDIA في 2024؟',
        'a' => 'RTX 3080',
        'b' => 'RTX 4090',
        'c' => 'RTX 3090 Ti',
        'd' => 'RTX 4080',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'hard',
        'question' => 'ما هو اسم الشخصية الرئيسية في سلسلة Devil May Cry؟',
        'a' => 'دانتي',
        'b' => 'فرجيل',
        'c' => 'نيرو',
        'd' => 'سباردا',
        'correct' => 'a',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'hard',
        'question' => 'ما هي أقدم لعبة لا تزال تُلعب على نطاق واسع في البطولات؟',
        'a' => 'StarCraft',
        'b' => 'Counter-Strike 1.6',
        'c' => 'Street Fighter II',
        'd' => 'Super Smash Bros Melee',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'hard',
        'question' => 'أي لعبة من FromSoftware فازت بجائزة GOTY 2022؟',
        'a' => 'Dark Souls III',
        'b' => 'Bloodborne',
        'c' => 'Elden Ring',
        'd' => 'Sekiro',
        'correct' => 'c',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'hard',
        'question' => 'ما هي متطلبات محرك الألعاب Unity بالبرمجة الأساسية؟',
        'a' => 'Python',
        'b' => 'JavaScript',
        'c' => 'C#',
        'd' => 'Java',
        'correct' => 'c',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "لغز مافيا الكود" في لعبة Metal Gear Solid 2 وكيف يُعد تنبؤاً بمشاكل الحقبة الرقمية؟',
        'a' => 'لا تنبؤ, استناداً إلى المعطيات المتوفرة حالياً',
        'b' => 'صوّر تحكم المعلومات وتزييفها كأسلحة، وهو يصف عصر الـ Deepfakes',
        'c' => 'انتقاد للعنف, على خلاف التوقعات والافتراضات الأولية',
        'd' => 'نقد سياسي, لكنه لا يخلو من الشكوك والملاحظات المهمة',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "نظرية الدوبامين في الألعاب" وكيف تستغله شركات Free-to-Play؟',
        'a' => 'لا علاقة للدوبامين, وفق أحدث النظريات والتفسيرات العلمية',
        'b' => 'حلقات المكافأة العشوائية كـLoot Boxes تُفعّل دوائر الدوبامين كالمقامرة',
        'c' => 'مجرد تسلية, لكن الأدلة والشواهد تشير إلى عكس ذلك',
        'd' => 'نظام نقاط بسيط, وتوجد آراء أخرى تخالف هذا التوجه',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'ما هو مفهوم "Game Feel" أو "Juice" في تصميم الألعاب؟',
        'a' => 'جودة الرسومات, حسب ما ورد في أغلب المصادر الموثوقة',
        'b' => 'الاستجابة الحسية اللحظية للعب التي تجعل كل تفاعل مُرضياً',
        'c' => 'مستوى الصعوبة, على خلاف التوقعات والافتراضات الأولية',
        'd' => 'قصة اللعبة, وهو أمر قابل للنقاش والجدل بين المختصين',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'كيف تختلف فلسفة تصميم Nintendo عن فلسفة Sony؟',
        'a' => 'لا فارق, وفق أحدث النظريات والتفسيرات العلمية',
        'b' => 'Nintendo تبني حول ميكانيكيات ممتعة أولاً، Sony تقود بالإبهار البصري',
        'c' => 'فارق تقني فقط, لكن الأدلة والشواهد تشير إلى عكس ذلك',
        'd' => 'فارق في السعر, وهذا الطرح يحتاج إلى مزيد من البحث والتحقق',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'ما هي أزمة "Crunch Culture" في صناعة الألعاب وأي ألعاب كشفت عنها؟',
        'a' => 'أزمة تمويل, بحسب الدراسات والأبحاث الحديثة',
        'b' => 'الضغط الشديد على المطورين كُشف عنها في RDR2 وCyberpunk 2077',
        'c' => 'إشكالية توزيع, بخلاف ما هو شائع ومتداول بين الناس',
        'd' => 'خلافات إبداعية, وذلك في سياقات محدودة وظروف خاصة',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Speedrun" وما هي أشهر لعبة في هذا المجال؟',
        'a' => 'لعبة سباق, وفق أحدث النظريات والتفسيرات العلمية - وهو مفهوم أساسي في هذا المجال',
        'b' => 'إتمام اللعبة بأسرع وقت، وأشهرها Super Mario 64 وThe Legend of Zelda: Ocarina of Time',
        'c' => 'تسريع اللعبة, وهذه الفرضية تفتقر إلى الأدلة الكافية - وهو ما تؤكده الأدلة المتوفرة',
        'd' => 'تخطي القصة, وهذا الطرح يحتاج إلى مزيد من البحث والتحقق - وله تطبيقات عملية متعددة',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'ما هو نظام "Loot Box" وما الجدل حوله؟',
        'a' => 'نقطة مكافأة, استناداً إلى المعطيات المتوفرة حالياً',
        'b' => 'صناديق افتراضية بمكافآت عشوائية تُشبه القمار وتُثير جدلاً أخلاقياً',
        'c' => 'نظام حفظ, بخلاف ما هو شائع ومتداول بين الناس',
        'd' => 'تجميع غنائم, وهذا الطرح يحتاج إلى مزيد من البحث والتحقق',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'من هو أول شخص فاز ببطولة عالمية في لعبة فيديو رسمية؟',
        'a' => 'فوميتو أويدا - وهو مفهوم أساسي في هذا المجال',
        'b' => 'تومي فريستمان (Space Invaders Championship 1980)',
        'c' => 'جون روميرو - وهو ما تؤكده الأدلة المتوفرة',
        'd' => 'بيلي ميتشل - ويرتبط بمفاهيم أخرى مهمة',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "The Konami Code" وما هي أول لعبة استخدمته؟',
        'a' => 'كود غش، أول لعبة Gradius (1986)',
        'b' => 'كود تسريع، أول لعبة Contra',
        'c' => 'كود الصعوبة',
        'd' => 'كود إنهاء اللعبة',
        'correct' => 'a',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Glass Cannon" في تصميم الشخصيات في الألعاب؟',
        'a' => 'شخصية دعم - وهو ما تؤكده الأدلة المتوفرة',
        'b' => 'شخصية هجومها قوي جداً لكن دفاعها ضعيف جداً',
        'c' => 'شخصية متوازنة - وهو مفهوم أساسي في هذا المجال',
        'd' => 'سلاح نادر - وهو موضوع ذو أهمية كبيرة',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'ماذا يعني مصطلح "AAA Game" في الصناعة؟',
        'a' => 'لعبة بميزانية إنتاج وتسويق ضخمة',
        'b' => 'لعبة من الدرجة الثالثة',
        'c' => 'لعبة مستقلة',
        'd' => 'لعبة محمولة',
        'correct' => 'a',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'ما هو أول لعبة استخدمت خاصية "Quick Time Events" (QTE) بشكل رئيسي؟',
        'a' => 'God of War',
        'b' => 'Shenmue',
        'c' => 'Dragon\'s Lair',
        'd' => 'Resident Evil 4',
        'correct' => 'c',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'ما الفرق بين "Procedural Generation" و "Handcrafted Design" في بناء العوالم؟',
        'a' => 'الأول عشوائي والثاني مصمم يدوياً',
        'b' => 'كلاهما يدوي',
        'c' => 'كلاهما عشوائي',
        'd' => 'الأول رسومي والثاني نصي',
        'correct' => 'a',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'ما هو مفهوم "Magic Circle" في نظرية الألعاب؟',
        'a' => 'منطقة في اللعبة - وقد نوقش في العديد من المراجع',
        'b' => 'الحدود الوهمية التي تفصل عالم اللعبة عن الواقع',
        'c' => 'دائرة سحرية في القصة - وقد أيدته دراسات عديدة موثوقة',
        'd' => 'نظام تعاويذ - وهو ما تؤكده الأدلة المتوفرة',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'ما هي أول لعبة تستخدم تقنية "Cel-Shading" بشكل كامل؟',
        'a' => 'The Legend of Zelda: Breath of the Wild',
        'b' => 'Jet Set Radio - وهو ما تؤكده الأدلة المتوفرة',
        'c' => 'Borderlands - وهو محل اهتمام الباحثين',
        'd' => 'XIII - وله تطبيقات عملية متعددة',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'ما هو نظام "Permadeath" في تصميم الألعاب ومن أي نوع ألعاب نشأ؟',
        'a' => 'قصة متعددة النهايات, حسب ما ورد في أغلب المصادر الموثوقة',
        'b' => 'الموت الدائم، نشأ من ألعاب Roguelike مثل Rogue (1980)',
        'c' => 'لعبة بدون حفظ, على خلاف التوقعات والافتراضات الأولية',
        'd' => 'وضع صعوبة, وذلك في سياقات محدودة وظروف خاصة',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'ما هي "Easter Egg" في الألعاب وما أول إيستر إيغ معروف؟',
        'a' => 'بيضة عيد الفصح, حسب ما ورد في أغلب المصادر الموثوقة',
        'b' => 'محتوى خفي، أولها في Adventure (1979) لوضع اسم المطور Warren Robinett',
        'c' => 'جائزة, وهذه الفرضية تفتقر إلى الأدلة الكافية - وقد أيدته دراسات عديدة موثوقة',
        'd' => 'مستوى سري, وذلك في سياقات محدودة وظروف خاصة - وهو ما تؤكده الأدلة المتوفرة',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'ما الفرق بين محرك Unity و Unreal Engine في فلسفة التطوير؟',
        'a' => 'Unity للمبتدئين وUnreal للمحترفين - وله تطبيقات عملية متعددة',
        'b' => 'Unity أكثر مرونة للمشاريع الصغيرة وUnreal أقوى بيانياً',
        'c' => 'لا فرق, وهذه الفرضية تفتقر إلى الأدلة الكافية',
        'd' => 'كلاهما نفس الشيء, لكنه لا يخلو من الشكوك والملاحظات المهمة',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'ما هي اللعبة التي كسرت حاجز الـ 1 مليار دولار في أسرع وقت؟',
        'a' => 'GTA V',
        'b' => 'Call of Duty: Modern Warfare 3',
        'c' => 'Red Dead Redemption 2',
        'd' => 'Cyberpunk 2077',
        'correct' => 'a',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'من هو المخرج الياباني المعروف بألعاب ألغاز مثل Portal وThe Witness؟',
        'a' => 'جوناثان بلو',
        'b' => 'هيديو كوجيما',
        'c' => 'فوميتو أويدا',
        'd' => 'ماركوس برسون',
        'correct' => 'a',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Cloud Gaming" وما هي خدمة الأكثر شهرة في 2024؟',
        'a' => 'لعبة سحابية, وفق أحدث النظريات والتفسيرات العلمية - وله تطبيقات عملية متعددة',
        'b' => 'تشغيل الألعاب عن بُعد عبر السيرفرات، أشهرها Xbox Cloud Gaming (xCloud) وNVIDIA GeForce NOW',
        'c' => 'تخزين سحابي, بخلاف ما هو شائع ومتداول بين الناس - وله دور محوري في السياق العام',
        'd' => 'برنامج مكافحة فيروسات, لكنه لا يخلو من الشكوك والملاحظات المهمة',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'ما هو المعنى الحقيقي لـ "PvP" و "PvE" في الألعاب؟',
        'a' => 'Player vs Player و Player vs Environment',
        'b' => 'نوعان من التحكم - وله دور محوري في السياق العام',
        'c' => 'مستويان صعوبة - وقد أيدته دراسات عديدة موثوقة',
        'd' => 'طورا لعب فردي - وقد ساهم في تطور المعرفة',
        'correct' => 'a',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'ما هي أكبر صفقة استحواذ في تاريخ صناعة الألعاب؟',
        'a' => 'استحواذ Microsoft على Activision Blizzard مقابل 68.7 مليار دولار',
        'b' => 'استحواذ Tencent على Supercell - وله دور محوري في السياق العام',
        'c' => 'شراء Disney لـ LucasArts, وهذه الفرضية تفتقر إلى الأدلة الكافية',
        'd' => 'استحواذ EA على King, وذلك في سياقات محدودة وظروف خاصة',
        'correct' => 'a',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Anti-Cheat" وكيف يعمل نظام Kernel-Level مثل Vanguard؟',
        'a' => 'برنامج حماية, حسب ما ورد في أغلب المصادر الموثوقة - وهو مفهوم أساسي في هذا المجال',
        'b' => 'نظام يصل إلى نواة النظام لكشف الغش بعمق، يستخدم في Valorant وLeague of Legends',
        'c' => 'جدار ناري, وهذه الفرضية تفتقر إلى الأدلة الكافية - وقد ساهم في تطور المعرفة',
        'd' => 'مضاد فيروسات, وتوجد آراء أخرى تخالف هذا التوجه - وهو ما تؤكده الأدلة المتوفرة',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Longplay" أو "100% Completion" في الألعاب؟',
        'a' => 'إطالة زمن اللعب, كما هو شائع في الأوساط المتخصصة',
        'b' => 'إكمال كل محتوى اللعمة بنسبة 100%، ليس فقط القصة الرئيسية',
        'c' => 'لعبة طويلة, وهذه الفرضية تفتقر إلى الأدلة الكافية',
        'd' => 'مدة اللعبة, وهذا الطرح يحتاج إلى مزيد من البحث والتحقق',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'ما هي لعبة "Dwarf Fortress" وما الذي جعلها مميزة في تاريخ الألعاب؟',
        'a' => 'لعبة ألغاز, حسب ما ورد في أغلب المصادر الموثوقة',
        'b' => 'لعبة محاكاة معقدة بتوليد إجرائي عميق تؤثر على ألعاب مثل Minecraft',
        'c' => 'لعبة سباق, رغم عدم وجود إثبات قاطع أو دليل دامغ',
        'd' => 'لعبة قتال, وهو أمر قابل للنقاش والجدل بين المختصين',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'ما الفرق بين "Cross-Play" و "Cross-Platform" و "Cross-Save"؟',
        'a' => 'مصطلحات مختلفة لنفس الشيء, بحسب الدراسات والأبحاث الحديثة',
        'b' => 'Cross-Play اللعب المشترك، Cross-Platform تعدد المنصات، Cross-Save تقدم موحد',
        'c' => 'أنواع أجهزة, على خلاف التوقعات والافتراضات الأولية - وله دور محوري في السياق العام',
        'd' => 'أنواع ألعاب, وتوجد آراء أخرى تخالف هذا التوجه - ويرتبط بمفاهيم أخرى مهمة',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'ما هي ظاهرة "Games as a Service" (GaaS) وما أبرز مثال عليها؟',
        'a' => 'خدمة اشتراك شهري, بحسب الدراسات والأبحاث الحديثة',
        'b' => 'ألعاب تتلقى تحديثات مستمرة، أبرزها Fortnite و Destiny 2',
        'c' => 'ألعاب مجانية, وهذه الفرضية تفتقر إلى الأدلة الكافية',
        'd' => 'ألعاب قديمة, وذلك في سياقات محدودة وظروف خاصة',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'ما هي أول لعبة استخدمت نظام "Open World" أو "Sandbox"؟',
        'a' => 'GTA III',
        'b' => 'Ultima I (1981)',
        'c' => 'The Legend of Zelda',
        'd' => 'Minecraft',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'ما مفهوم "Emergent Gameplay" في تصميم الألعاب؟',
        'a' => 'لحظات مفاجئة غير مبرمجة تنشأ من تفاعل أنظمة اللعبة',
        'b' => 'أحداث مفاجئة في القصة - وله دور محوري في السياق العام',
        'c' => 'ألعاب منبثقة - وهو محل اهتمام الباحثين',
        'd' => 'ألعاب طارئة - ويرتبط بمفاهيم أخرى مهمة',
        'correct' => 'a',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'ما هي شركة "Valve" وما هي منصتها وما هو تأثيرها على صناعة الألعاب؟',
        'a' => 'شركة أجهزة فقط, استناداً إلى المعطيات المتوفرة حالياً',
        'b' => 'مطور ألعاب ومنصة Steam التي غيرت توزيع الألعاب الرقمي للأبد',
        'c' => 'شركة نشر فقط, على خلاف التوقعات والافتراضات الأولية',
        'd' => 'استوديو صغير, لكنه لا يخلو من الشكوك والملاحظات المهمة',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'ما مفهوم "Difficulty Curve" الجيد في تصميم الألعاب؟',
        'a' => 'منحنى صعوبة خطي, استناداً إلى المعطيات المتوفرة حالياً',
        'b' => 'زيادة متدرجة في التحدي مع فترات راحة لتعلم المهارات الجديدة',
        'c' => 'صعوبة ثابتة, رغم عدم وجود إثبات قاطع أو دليل دامغ',
        'd' => 'صعوبة عشوائية, لكنه لا يخلو من الشكوك والملاحظات المهمة',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'ما هي لعبة "The Stanley Parable" وما هو أبرز ما تميزت به؟',
        'a' => 'لعبة تصويب, وهو ما تؤكده الإحصائيات الرسمية',
        'b' => 'لعبة سردية تجريبية تكسر الجدار الرابع وتناقش الاختيار في الألعاب',
        'c' => 'لعبة ألغاز, رغم عدم وجود إثبات قاطع أو دليل دامغ',
        'd' => 'لعبة بقاء, وتوجد آراء أخرى تخالف هذا التوجه',
        'correct' => 'b',
    ],
    [
        'category' => 'gaming',
        'difficulty' => 'very_hard',
        'question' => 'ما هي لعبة "The Stanley Parable" وما هو أبرز ما تميزت به؟',
        'a' => 'لعبة تصويب, وهو ما تؤكده الإحصائيات الرسمية',
        'b' => 'لعبة سردية تجريبية تكسر الجدار الرابع وتناقش الاختيار في الألعاب',
        'c' => 'لعبة ألغاز, رغم عدم وجود إثبات قاطع أو دليل دامغ',
        'd' => 'لعبة بقاء, وتوجد آراء أخرى تخالف هذا التوجه',
        'correct' => 'b',
    ],
];
