<?php
return [
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'أي فيلم حقق أعلى إيرادات في تاريخ السينما؟',
        'a' => 'Avengers: Endgame',
        'b' => 'Avatar',
        'c' => 'Titanic',
        'd' => 'The Lion King',
        'correct' => 'b',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'من أخرج فيلم Oppenheimer 2023؟',
        'a' => 'ستيفن سبيلبيرغ',
        'b' => 'كريستوفر نولان',
        'c' => 'جيمس كاميرون',
        'd' => 'ريدلي سكوت',
        'correct' => 'b',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'أي فيلم فاز بجائزة أوسكار أفضل فيلم 2024؟',
        'a' => 'Oppenheimer',
        'b' => 'Barbie',
        'c' => 'Poor Things',
        'd' => 'Killers of the Flower Moon',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'ما هو اسم الكوكب في فيلم Avatar؟',
        'a' => 'Pandora',
        'b' => 'Titan',
        'c' => 'Krypton',
        'd' => 'Tatooine',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'من قام بتمثيل دور Joker في فيلم 2019؟',
        'a' => 'جاك نيكلسون',
        'b' => 'هيث ليدجر',
        'c' => 'خواكين فينيكس',
        'd' => 'بروس ويليس',
        'correct' => 'c',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'ما هو أول فيلم في سلسلة Marvel Cinematic Universe؟',
        'a' => 'Captain America',
        'b' => 'Thor',
        'c' => 'Iron Man',
        'd' => 'The Avengers',
        'correct' => 'c',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'من أخرج فيلم Pulp Fiction؟',
        'a' => 'كوينتن تارانتينو',
        'b' => 'ستيفن سبيلبيرغ',
        'c' => 'ديفيد فينشر',
        'd' => 'مارتن سكورسيزي',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'كم عدد جوائز الأوسكار التي فاز بها فيلم Titanic؟',
        'a' => '5',
        'b' => '8',
        'c' => '11',
        'd' => '14',
        'correct' => 'c',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'من هو الممثل الذي جسد دور John Wick؟',
        'a' => 'كيانو ريفز',
        'b' => 'جيسون ستاثام',
        'c' => 'سيلفستر ستالوني',
        'd' => 'بروس ويليس',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'ما هو الفيلم الأعلى إيرادات في عام 2023؟',
        'a' => 'Barbie',
        'b' => 'Oppenheimer',
        'c' => 'The Super Mario Bros. Movie',
        'd' => 'Guardians of the Galaxy Vol. 3',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'ما هي مدة عرض فيلم The Godfather الأصلي؟',
        'a' => '150 دقيقة',
        'b' => '175 دقيقة',
        'c' => '200 دقيقة',
        'd' => '225 دقيقة',
        'correct' => 'b',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'من أخرج فيلم Schindler\'s List؟',
        'a' => 'ستيفن سبيلبيرغ',
        'b' => 'كريستوفر نولان',
        'c' => 'جيمس كاميرون',
        'd' => 'ريدلي سكوت',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'أي ممثل فاز بجائزة الأوسكار عن دوره في فيلم The Revenant؟',
        'a' => 'براد بيت',
        'b' => 'ليوناردو دي كابريو',
        'c' => 'ماثيو ماكونهي',
        'd' => 'توم هاردي',
        'correct' => 'b',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'في أي عام صدر أول فيلم من سلسلة Harry Potter؟',
        'a' => '2001',
        'b' => '2002',
        'c' => '2003',
        'd' => '2004',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'من هو مخرج ثلاثية The Dark Knight؟',
        'a' => 'تيم برتون',
        'b' => 'زاك سنايدر',
        'c' => 'كريستوفر نولان',
        'd' => 'جويل شوماخر',
        'correct' => 'c',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'أي من الأفلام التالية لم يخرجه كوينتن تارانتينو؟',
        'a' => 'Django Unchained',
        'b' => 'Inglourious Basterds',
        'c' => 'Kill Bill',
        'd' => 'The Departed',
        'correct' => 'd',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'كم عدد الأفلام الرئيسية في سلسلة Fast & Furious حتى 2024؟',
        'a' => '9',
        'b' => '10',
        'c' => '11',
        'd' => '12',
        'correct' => 'b',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'من هو مخرج فيلم The Shawshank Redemption؟',
        'a' => 'فرانك دارابونت',
        'b' => 'ستيفن سبيلبيرغ',
        'c' => 'مارتن سكورسيزي',
        'd' => 'كلينت إيستوود',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'ما هو الفيلم الأعلى تقييماً على IMDb في التاريخ؟',
        'a' => 'The Godfather',
        'b' => 'The Shawshank Redemption',
        'c' => 'The Dark Knight',
        'd' => 'Pulp Fiction',
        'correct' => 'b',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'من الممثلة التي لعبت دور Katniss Everdeen في The Hunger Games؟',
        'a' => 'إيما ستون',
        'b' => 'سكارليت جوهانسون',
        'c' => 'كريستين ستيوارت',
        'd' => 'جينيفر لورنس',
        'correct' => 'd',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'في أي عام فاز فيلم Parasite بجائزة أوسكار أفضل فيلم؟',
        'a' => '2018',
        'b' => '2019',
        'c' => '2020',
        'd' => '2021',
        'correct' => 'c',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'من أخرج فيلم The Social Network؟',
        'a' => 'آرون سوركين',
        'b' => 'ديفيد فينشر',
        'c' => 'كريستوفر نولان',
        'd' => 'بول توماس أندرسون',
        'correct' => 'b',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'ما هي الشخصية التي لعبها روبرت داوني جونيور في Marvel Cinematic Universe؟',
        'a' => 'آيرون مان',
        'b' => 'كابتن أمريكا',
        'c' => 'ثور',
        'd' => 'سبايدرمان',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'من هو المخرج المعروف بأسلوبه البصري في أفلام مثل The Grand Budapest Hotel؟',
        'a' => 'ويس أندرسون',
        'b' => 'تيم برتون',
        'c' => 'جييرمو ديل تورو',
        'd' => 'وودي آلن',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'ما اسم الشخصية التي لعبها هيث ليدجر في فيلم The Dark Knight؟',
        'a' => 'ذو الوجهين',
        'b' => 'بين',
        'c' => 'الجوكر',
        'd' => 'ريدلر',
        'correct' => 'c',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'ما هو الفيلم الأعلى إيرادات من فئة R-rated في التاريخ؟',
        'a' => 'Deadpool',
        'b' => 'Joker',
        'c' => 'The Matrix Reloaded',
        'd' => 'Logan',
        'correct' => 'b',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'من أخرج فيلم Gladiator؟',
        'a' => 'ريدلي سكوت',
        'b' => 'ستيفن سبيلبيرغ',
        'c' => 'جيمس كاميرون',
        'd' => 'توني سكوت',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'من هو أول ممثل جسد شخصية جيمس بوند في السينما؟',
        'a' => 'شون كونري',
        'b' => 'روجر مور',
        'c' => 'تيموثي دالتون',
        'd' => 'بيرس بروسنان',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'أي فيلم من الأفلام التالية جمع ليوناردو دي كابريو وكيت وينسلت معاً؟',
        'a' => 'Inception',
        'b' => 'Shutter Island',
        'c' => 'Titanic',
        'd' => 'The Wolf of Wall Street',
        'correct' => 'c',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'ما هو الاسم الحقيقي لمارلين مونرو؟',
        'a' => 'نورما جين مورتنسون',
        'b' => 'ميرلين مونرو',
        'c' => 'إليزابيث تايلور',
        'd' => 'أودري هيبورن',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'من أخرج فيلم The Silence of the Lambs؟',
        'a' => 'ألفريد هيتشكوك',
        'b' => 'ريدلي سكوت',
        'c' => 'ديفيد لينش',
        'd' => 'جوناثان ديم',
        'correct' => 'd',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'أي ممثل لعب دور Wolverine في أفلام X-Men؟',
        'a' => 'توم هاردي',
        'b' => 'هيو جاكمان',
        'c' => 'جيك جيلينهال',
        'd' => 'ريان رينولدز',
        'correct' => 'b',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'كم عدد الأجزاء الرئيسية لسلسلة The Godfather؟',
        'a' => 'جزئين',
        'b' => '4 أجزاء',
        'c' => '3 أجزاء',
        'd' => '5 أجزاء',
        'correct' => 'c',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'medium',
        'question' => 'من أخرج فيلم Jaws (الفك المفترس)؟',
        'a' => 'ستيفن سبيلبيرغ',
        'b' => 'جيمس كاميرون',
        'c' => 'ريدلي سكوت',
        'd' => 'جون كاربنتر',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'في أي فيلم استخدم كريستوفر نولان أسلوب "Practical Effects" بدلاً من CGI لتفجير حقيقي؟',
        'a' => 'Inception',
        'b' => 'The Dark Knight',
        'c' => 'Tenet',
        'd' => 'Dunkirk',
        'correct' => 'b',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'ما هو الأسلوب السردي المستخدم في فيلم Rashomon للمخرج أكيرا كوروساوا؟',
        'a' => 'السرد الخطي - وله تطبيقات عملية متعددة',
        'b' => 'راشومون إفيكت (روايات متعددة لنفس الحدث)',
        'c' => 'الراوي الغير موثوق - وقد أيدته دراسات عديدة موثوقة',
        'd' => 'السرد العكسي - وهو محل اهتمام الباحثين',
        'correct' => 'b',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'أي فيلم استخدم تقنية "bullet time" لأول مرة بشكل مبهر؟',
        'a' => 'Mission Impossible',
        'b' => 'The Matrix',
        'c' => 'Face/Off',
        'd' => 'Speed',
        'correct' => 'b',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'ما ميزانية فيلم Avengers: Endgame التقريبية؟',
        'a' => '150 مليون دولار',
        'b' => '200 مليون دولار',
        'c' => '356 مليون دولار',
        'd' => '500 مليون دولار',
        'correct' => 'c',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'من فاز بجائزة أوسكار أفضل ممثل مرتين على التوالي في القرن الحالي؟',
        'a' => 'توم هانكس',
        'b' => 'دانزل واشنطن',
        'c' => 'توم هانكس مجدداً',
        'd' => 'لا أحد',
        'correct' => 'd',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'من هو المخرج الذي فاز بجائزة الأوسكار لأفضل مخرج 3 مرات؟',
        'a' => 'ستيفن سبيلبيرغ',
        'b' => 'كريستوفر نولان',
        'c' => 'جيمس كاميرون',
        'd' => 'جون فورد',
        'correct' => 'd',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'من هو المخرج المعروف بثلاثية Three Colors (أزرق، أبيض، أحمر)؟',
        'a' => 'كريستوف كيشلوفسكي',
        'b' => 'بيدرو ألمودوبار',
        'c' => 'فرانسوا تروفو',
        'd' => 'جان لوك غودار',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'ما هي الدولة التي أنتجت فيلم Parasite الفائز بأوسكار 2020؟',
        'a' => 'اليابان',
        'b' => 'كوريا الجنوبية',
        'c' => 'الصين',
        'd' => 'تايوان',
        'correct' => 'b',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'من هو المخرج الذي يُنسب إليه الفضل في تأسيس نوع أفلام Spaghetti Western؟',
        'a' => 'سيرجيو ليوني',
        'b' => 'جون فورد',
        'c' => 'كلينت إيستوود',
        'd' => 'سام بيكينبا',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'في أي عام تم عرض أول فيلم سينمائي للأخوين لوميير؟',
        'a' => '1895',
        'b' => '1900',
        'c' => '1905',
        'd' => '1910',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'كم عدد ترشيحات الأوسكار لأفضل مخرج التي حصل عليها ألفريد هيتشكوك دون فوز؟',
        'a' => '5',
        'b' => '3',
        'c' => '7',
        'd' => '0',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'من هو الممثل الذي رفض جائزة الأوسكار لأفضل ممثل عن دوره في فيلم The Godfather؟',
        'a' => 'مارلون براندو',
        'b' => 'آل باتشينو',
        'c' => 'جيمس كان',
        'd' => 'روبرت دوفال',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'ما هي اللغة الأساسية التي تحدث بها حوار فيلم The Passion of the Christ؟',
        'a' => 'الآرامية واللاتينية والعبرية',
        'b' => 'الإنجليزية فقط',
        'c' => 'اللاتينية فقط',
        'd' => 'اليونانية القديمة',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'كم عدد الأفلام الرئيسية في سلسلة Star Wars (الملحمة الأساسية) حتى 2024؟',
        'a' => '6',
        'b' => '9',
        'c' => '11',
        'd' => '12',
        'correct' => 'b',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'من هو ممثل الصوت الذي أدى صوت Darth Vader في Star Wars؟',
        'a' => 'مارك هاميل',
        'b' => 'هاريسون فورد',
        'c' => 'جيمس إيرل جونز',
        'd' => 'ديفيد براوز',
        'correct' => 'c',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'ما هو أول فيلم كرتوني طويل من إنتاج ديزني؟',
        'a' => 'Pinocchio',
        'b' => 'Fantasia',
        'c' => 'Snow White and the Seven Dwarfs',
        'd' => 'Bambi',
        'correct' => 'c',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'من هو المخرج الذي أخرج فيلمي The Sixth Sense و Split؟',
        'a' => 'إم. نايت شيامالان',
        'b' => 'جيمس وان',
        'c' => 'جوردان بيل',
        'd' => 'آري أستر',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'في أي عام صدر فيلم Citizen Kane؟',
        'a' => '1939',
        'b' => '1941',
        'c' => '1945',
        'd' => '1950',
        'correct' => 'b',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'أي شخصية كرتونية حصلت على نجمة على ممشى المشاهير في هوليوود؟',
        'a' => 'سوبرمان',
        'b' => 'باتمان',
        'c' => 'سبايدرمان',
        'd' => 'ميكي ماوس',
        'correct' => 'd',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'ما اسم شركة الإنتاج التي أسسها جورج لوكاس؟',
        'a' => 'أمبلين إنترتينمنت',
        'b' => 'دريم ووركس',
        'c' => 'لوكاسفيلم',
        'd' => 'باد روبوت',
        'correct' => 'c',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'أي فيلم من إخراج مارتن سكورسيزي فاز بجائزة أوسكار أفضل فيلم؟',
        'a' => 'Goodfellas',
        'b' => 'Taxi Driver',
        'c' => 'The Wolf of Wall Street',
        'd' => 'The Departed',
        'correct' => 'd',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'من هو المخرج الإسباني المعروف بأسلوبه المميز في أفلام مثل The Skin I Live In؟',
        'a' => 'لويس بونويل',
        'b' => 'بيدرو ألمودوبار',
        'c' => 'بابلو ألتو',
        'd' => 'أليخاندرو آمينابار',
        'correct' => 'b',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'ما معنى مصطلح Deus Ex Machina في السينما؟',
        'a' => 'حل مفاجئ وغير متوقع في نهاية القصة',
        'b' => 'شخصية شريرة مقنعة',
        'c' => 'مشهد مطاردات طويل',
        'd' => 'تقنية تصوير خاصة',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'ما اسم أول فيلم ناطق Talkie في تاريخ السينما؟',
        'a' => 'City Lights',
        'b' => 'The Jazz Singer',
        'c' => 'Singin\' in the Rain',
        'd' => 'Metropolis',
        'correct' => 'b',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'من هو المخرج المكسيكي الذي أخرج Birdman و The Revenant؟',
        'a' => 'جييرمو ديل تورو',
        'b' => 'أليخاندرو غونزاليس إيناريتو',
        'c' => 'ألفونسو كوارون',
        'd' => 'كوينتن تارانتينو',
        'correct' => 'b',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'أي من الأفلام التالية فاز بجوائز الأوسكار الخمس الكبرى (فيلم، مخرج، ممثل، ممثلة، سيناريو)؟',
        'a' => 'The Godfather',
        'b' => 'The Silence of the Lambs',
        'c' => 'Schindler\'s List',
        'd' => 'Titanic',
        'correct' => 'b',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'من هو الممثل الذي لعب دور هانيبال ليكتر في The Silence of the Lambs؟',
        'a' => 'أنتوني هوبكنز',
        'b' => 'براين كوكس',
        'c' => 'مادس ميكلسن',
        'd' => 'غاري أولدمان',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'ما هي المدة التقريبية لفيلم Gone with the Wind؟',
        'a' => '3 ساعات',
        'b' => '3 ساعات و 58 دقيقة',
        'c' => '4 ساعات و 30 دقيقة',
        'd' => 'ساعتان و 45 دقيقة',
        'correct' => 'b',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'من المخرج الذي فاز بأوسكار أفضل مخرج عن أول فيلم روائي طويل له (American Beauty)؟',
        'a' => 'ستيفن دالدراي',
        'b' => 'بول توماس أندرسون',
        'c' => 'سام مينديز',
        'd' => 'ديفيد فينشر',
        'correct' => 'c',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'من هو مخرج فيلم Parasite الكوري الجنوبي؟',
        'a' => 'بونغ جون هو',
        'b' => 'بارك تشان ووك',
        'c' => 'كيم كي دوك',
        'd' => 'لي تشانغ دونغ',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'ما اسم الشخصية الرئيسية في سلسلة أفلام Indiana Jones؟',
        'a' => 'إنديانا جونز',
        'b' => 'هان سولو',
        'c' => 'جيمس بوند',
        'd' => 'إيثان هانت',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'أي من الأفلام التالية لم يخرجها ستيفن سبيلبيرغ؟',
        'a' => 'Jaws',
        'b' => 'E.T.',
        'c' => 'The Green Mile',
        'd' => 'Saving Private Ryan',
        'correct' => 'c',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'hard',
        'question' => 'ما هي اللغة التي استخدمها ميل جيبسون في فيلم Apocalypto؟',
        'a' => 'الإسبانية',
        'b' => 'البرتغالية',
        'c' => 'الإنجليزية',
        'd' => 'لغة المايا القديمة',
        'correct' => 'd',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'ما هو مفهوم Kuleshov Effect وكيف يؤثر على السينما؟',
        'a' => 'تأثير الموسيقى على المشاعر',
        'b' => 'تأثير تتابع المشاهد على تفسير المشاهد',
        'c' => 'أسلوب تصوير التحرك السريع',
        'd' => 'استخدام الإضاءة لخلق التوتر',
        'correct' => 'b',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'أي مخرج طور نظرية Auteur Theory في السينما؟',
        'a' => 'ستانلي كوبريك',
        'b' => 'أندريه بازان وترويج فرانسوا تروفو',
        'c' => 'فيدريكو فيليني',
        'd' => 'أورسون ويلز',
        'correct' => 'b',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'في فيلم 2001: A Space Odyssey، ما الذي يرمز إليه Monolith وفقاً لكوبريك نفسه؟',
        'a' => 'الله',
        'b' => 'رفض إعطاء تفسير محدد',
        'c' => 'التطور البشري',
        'd' => 'الذكاء الاصطناعي',
        'correct' => 'b',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'ما هو الفارق بين Diegetic Sound و Non-Diegetic Sound في السينما؟',
        'a' => 'نوعا مؤثرات صوتية - وقد نوقش في العديد من المراجع',
        'b' => 'الأول مسموع بالشخصيات والثاني للمشاهد فقط',
        'c' => 'فارق في الجودة الصوتية - وهو مفهوم أساسي في هذا المجال',
        'd' => 'لا فارق فعلياً - وقد ساهم في تطور المعرفة',
        'correct' => 'b',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'أي فيلم يُعتبر مؤسساً لنظرية Male Gaze حسب لورا مولفي؟',
        'a' => 'Vertigo',
        'b' => 'Rear Window',
        'c' => 'كلاهما',
        'd' => 'Psycho',
        'correct' => 'c',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'ما هي تقنية Dutch Angle في التصوير السينمائي؟',
        'a' => 'إمالة الكاميرا جانبياً لخلق شعور بعدم الارتياح',
        'b' => 'التصوير من الأعلى مباشرة - ويرتبط بمفاهيم أخرى مهمة',
        'c' => 'التصوير من مستوى الأرض - وهو محل اهتمام الباحثين',
        'd' => 'تحريك الكاميرا بشكل دائري - وله دور محوري في السياق العام',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'ما هي قاعدة 180 Degree Rule في السينما؟',
        'a' => 'زاوية الكاميرا لا تتجاوز 180 درجة',
        'b' => 'الحفاظ على اتجاه نظر الشخصيات ثابتاً',
        'c' => 'قاعدة تصوير ثلاثية الأبعاد',
        'd' => 'قانون الإضاءة السينمائي الأساسي',
        'correct' => 'b',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'من يعتبر الأب الروحي للموجة الفرنسية الجديدة French New Wave؟',
        'a' => 'أندريه بازان',
        'b' => 'فرانسوا تروفو',
        'c' => 'جان لوك غودار',
        'd' => 'كلود شابرول',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'ما مفهوم Mise-en-scène في التحليل السينمائي؟',
        'a' => 'تنسيق العناصر البصرية داخل الإطار',
        'b' => 'تقنية قص المشاهد',
        'c' => 'نوع من الموسيقى التصويرية',
        'd' => 'أسلوب تمثيلي محدد',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'أي فيلم من المدرسة الواقعية الإيطالية Italian Neorealism يُعد الأكثر تأثيراً؟',
        'a' => 'Rome Open City',
        'b' => 'Umberto D.',
        'c' => 'Bicycle Thieves',
        'd' => 'La Strada',
        'correct' => 'c',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'من هو المخرج الذي استخدم تقنية Match Cut الشهيرة بين عظمة وسفينة فضائية في 2001؟',
        'a' => 'ريدلي سكوت',
        'b' => 'جورج لوكاس',
        'c' => 'أندريه تاركوفسكي',
        'd' => 'ستانلي كوبريك',
        'correct' => 'd',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'ما هي تقنية Smell-O-Vision في السينما؟',
        'a' => 'تقنية تذوق الطعام أثناء الفيلم, وقد تم التحقق منه عبر تجارب متعددة',
        'b' => 'تقنية إطلاق روائح متزامنة مع مشاهد الفيلم',
        'c' => 'نظارة للواقع الافتراضي قديمة, وقد حظي باهتمام واسع من الباحثين',
        'd' => 'تقنية عرض ثلاثي الأبعاد - وهو ما تؤكده الأدلة المتوفرة',
        'correct' => 'b',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'ما الفرق بين الـ Crane Shot والـ Tracking Shot في التصوير؟',
        'a' => 'كلاهما نفس التقنية',
        'b' => 'الأول للتصوير البطيء والثاني للسريع',
        'c' => 'الأول من أعلى والثاني من أسفل',
        'd' => 'الأول حركة رأسية والثاني حركة أفقية',
        'correct' => 'd',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'من هو أول مخرج استخدم تقنية Dolly Zoom أو Vertigo Effect في السينما؟',
        'a' => 'أورسون ويلز',
        'b' => 'ألفريد هيتشكوك',
        'c' => 'ستانلي كوبريك',
        'd' => 'بريان دي بالما',
        'correct' => 'b',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'ما هي سينما الطليعة Avant-garde Cinema؟',
        'a' => 'أفلام تجريبية خارج السرد التقليدي',
        'b' => 'أفلام حربية',
        'c' => 'أفلام ثلاثية الأبعاد',
        'd' => 'أفلام وثائقية',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'من هو المخرج الذي اشتهر بأفلامه الصامتة مثل Modern Times و The Great Dictator؟',
        'a' => 'باستر كيتون',
        'b' => 'هارولد لويد',
        'c' => 'تشارلي تشابلن',
        'd' => 'ديفيد غريفيث',
        'correct' => 'c',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'ما هو مفهوم Suspension of Disbelief في السينما؟',
        'a' => 'تعليق العقل الناقد لتقبل الأحداث الخيالية',
        'b' => 'تصديق كل ما يظهر على الشاشة - وقد نوقش في العديد من المراجع',
        'c' => 'الشك في مصداقية الفيلم - وقد ساهم في تطور المعرفة',
        'd' => 'تحليل الفيلم بشكل نقدي - ويرتبط بمفاهيم أخرى مهمة',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'في أي عام تأسست أكاديمية فنون وعلوم الصور المتحركة المانحة لجوائز الأوسكار؟',
        'a' => '1925',
        'b' => '1926',
        'c' => '1927',
        'd' => '1929',
        'correct' => 'c',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'ما هو الاسم الرسمي لجائزة السعفة الذهبية في مهرجان كان السينمائي؟',
        'a' => 'Golden Lion',
        'b' => 'Palme d\'Or',
        'c' => 'Golden Bear',
        'd' => 'Silver Bear',
        'correct' => 'b',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'من هو مخرج الفيلم الياباني Seven Samurai؟',
        'a' => 'أكيرا كوروساوا',
        'b' => 'ياسوجيرو أوزو',
        'c' => 'كينجي ميزوغوتشي',
        'd' => 'ماساتاكي كوباياشي',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'ما هي تقنية Stop Motion في التحريك السينمائي؟',
        'a' => 'رسم بإطارات متتالية',
        'b' => 'تحريك بالكمبيوتر ثلاثي الأبعاد',
        'c' => 'تحريك مجسمات مادية إطاراً بإطار',
        'd' => 'تصوير حي ممزوج برسوم متحركة',
        'correct' => 'c',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'بماذا يُعرف فيلم The Battle of Algiers في تاريخ السينما؟',
        'a' => 'استخدام أسلوب شبه وثائقي في تصوير الثورة',
        'b' => 'كونه أول فيلم ملون جزائري - وقد نوقش في العديد من المراجع',
        'c' => 'كونه فيلم رسوم متحركة - وله دور محوري في السياق العام',
        'd' => 'كونه أول فيلم ثلاثي الأبعاد - وقد ساهم في تطور المعرفة',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'ما هو اختبار Bechdel Test في السينما؟',
        'a' => 'اختبار جودة المؤثرات البصرية - وقد نوقش في العديد من المراجع',
        'b' => 'اختبار تمثيل المرأة بحوار بين امرأتين عن غير الرجال',
        'c' => 'اختبار سلامة التصوير, لكن الأدلة والشواهد تشير إلى عكس ذلك',
        'd' => 'اختبار جودة الإخراج, وهو أمر قابل للنقاش والجدل بين المختصين',
        'correct' => 'b',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'في أي عام تم إصدار أول فيلم بتقنية IMAX؟',
        'a' => '1968',
        'b' => '1970',
        'c' => '1975',
        'd' => '1980',
        'correct' => 'b',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'ما هي طريقة Method Acting التي اشتهر بها مارلون براندو؟',
        'a' => 'الانغماس الكامل في الشخصية وتقمصها',
        'b' => 'التمثيل بدون نص',
        'c' => 'الارتجال الكامل',
        'd' => 'حفظ النص فقط',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'من هو المخرج السويدي المعروف بأفلامه الفلسفية مثل The Seventh Seal و Persona؟',
        'a' => 'أكيرا كوروساوا',
        'b' => 'فيدريكو فيليني',
        'c' => 'أندريه تاركوفسكي',
        'd' => 'إنغمار بيرغمان',
        'correct' => 'd',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'ما مفهوم Negative Space في التصوير السينمائي؟',
        'a' => 'المساحة المظلمة في الإطار - وله دور محوري في السياق العام',
        'b' => 'التصوير بالأبيض والأسود - وقد ساهم في تطور المعرفة',
        'c' => 'المساحة الفارغة حول العنصر الرئيسي لخلق معنى',
        'd' => 'تقنية إضاءة عكسية - وقد أيدته دراسات عديدة موثوقة',
        'correct' => 'c',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'من هو المخرج الروسي الذي أخرج Stalker و Andrei Rublev؟',
        'a' => 'أندريه تاركوفسكي',
        'b' => 'سيرجي آيزنشتاين',
        'c' => 'دزيغا فيرتوف',
        'd' => 'ألكسندر سوكوروف',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'ما الفرق بين Dubbing و Subtitling في ترجمة الأفلام؟',
        'a' => 'كلاهما ترجمة, وفق أحدث النظريات والتفسيرات العلمية',
        'b' => 'الأول ترجمة والثاني دبلجة, بحسب ما توصلت إليه الأبحاث والتجارب',
        'c' => 'الأول للصم والبكم, بخلاف ما هو شائع ومتداول بين الناس',
        'd' => 'الأول استبدال الحوار الصوتي والثاني ترجمة نصية على الشاشة',
        'correct' => 'd',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'من هو الممثل الذي لعب دور هانيبال ليكتر لأول مرة في السينما؟',
        'a' => 'براين كوكس',
        'b' => 'أنتوني هوبكنز',
        'c' => 'مادس ميكلسن',
        'd' => 'غاري أولدمان',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'ما هي Cinéma Vérité التي ظهرت في ستينيات القرن الماضي؟',
        'a' => 'سينما الخيال العلمي',
        'b' => 'سينما الحقيقة الواقعية الوثائقية',
        'c' => 'السينما النقدية',
        'd' => 'السينما الصامتة',
        'correct' => 'b',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'من هو المخرج الذي أخرج فيلم Blade Runner 2049؟',
        'a' => 'ريدلي سكوت',
        'b' => 'كريستوفر نولان',
        'c' => 'دينيس فيلنوف',
        'd' => 'نيكولاس ويندينج ريفن',
        'correct' => 'c',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'ما هو مصطلح B-Movie في صناعة السينما؟',
        'a' => 'أفلام منخفضة الميزانية وسريعة الإنتاج',
        'b' => 'أفلام من الفئة الثانية في جودتها, ويعتبر مرجعية مهمة في هذا الشأن',
        'c' => 'أفلام وثائقية قصيرة - وقد نوقش في العديد من المراجع',
        'd' => 'أفلام تجارية ضخمة - وقد ساهم في تطور المعرفة',
        'correct' => 'a',
    ],
    [
        'category' => 'movies',
        'difficulty' => 'very_hard',
        'question' => 'ما هو مصطلح B-Movie في صناعة السينما؟',
        'a' => 'أفلام منخفضة الميزانية وسريعة الإنتاج',
        'b' => 'أفلام من الفئة الثانية في جودتها',
        'c' => 'أفلام وثائقية قصيرة - وله تطبيقات عملية متعددة',
        'd' => 'أفلام تجارية ضخمة - وهو مفهوم أساسي في هذا المجال',
        'correct' => 'a',
    ],
];
