<?php
return [
    [
        'category' => 'premier-league',
        'difficulty' => 'medium',
        'question' => 'في أي عام تأسست الدوري الإنجليزي الممتاز (البريميرليغ)؟',
        'a' => '1888',
        'b' => '1992',
        'c' => '1904',
        'd' => '1980',
        'correct' => 'b',
    ],
    [
        'category' => 'premier-league',
        'difficulty' => 'medium',
        'question' => 'ما هو النادي الأكثر تتويجاً بلقب البريميرليغ منذ انطلاقه عام 1992؟',
        'a' => 'ليفربول',
        'b' => 'مانشستر يونايتد',
        'c' => 'تشيلسي',
        'd' => 'أرسنال',
        'correct' => 'b',
    ],
    [
        'category' => 'premier-league',
        'difficulty' => 'medium',
        'question' => 'من هو الهداف التاريخي للبريميرليغ؟',
        'a' => 'واين روني',
        'b' => 'آلان شيرر',
        'c' => 'هاري كين',
        'd' => 'تيري هنري',
        'correct' => 'b',
    ],
    [
        'category' => 'premier-league',
        'difficulty' => 'hard',
        'question' => 'أي نادٍ حقب موسماً كاملاً دون هزيمة في البريميرليغ (2003-2004)؟',
        'a' => 'مانشستر يونايتد',
        'b' => 'أرسنال',
        'c' => 'تشيلسي',
        'd' => 'ليفربول',
        'correct' => 'b',
    ],
    [
        'category' => 'premier-league',
        'difficulty' => 'hard',
        'question' => 'ما هو النادي الذي يُلقب بـ"الريدز" (The Reds)؟',
        'a' => 'مانشستر يونايتد',
        'b' => 'ليفربول',
        'c' => 'أرسنال',
        'd' => 'توتنهام',
        'correct' => 'b',
    ],
    [
        'category' => 'premier-league',
        'difficulty' => 'hard',
        'question' => 'من هو أكثر مدرب فوزاً بلقب البريميرليغ؟',
        'a' => 'أرسين فينغر',
        'b' => 'السير أليكس فيرغسون',
        'c' => 'جوزيه مورينيو',
        'd' => 'بيب غوارديولا',
        'correct' => 'b',
    ],
    [
        'category' => 'premier-league',
        'difficulty' => 'very_hard',
        'question' => 'كم عدد ألقاب ليفربول في البريميرليغ؟',
        'a' => '0',
        'b' => '1',
        'c' => '2',
        'd' => '3',
        'correct' => 'b',
    ],
    [
        'category' => 'premier-league',
        'difficulty' => 'very_hard',
        'question' => 'أي نادٍ حقق أكبر عدد من النقاط في موسم واحد بالبريميرليغ (100 نقطة)؟',
        'a' => 'مانشستر سيتي',
        'b' => 'ليفربول',
        'c' => 'تشيلسي',
        'd' => 'مانشستر يونايتد',
        'correct' => 'a',
    ],
    [
        'category' => 'premier-league',
        'difficulty' => 'very_hard',
        'question' => 'ما هو الملعب الذي يلعب فيه نادي توتنهام هوتسبير مبارياته؟',
        'a' => 'ستامفورد بريدج',
        'b' => 'ملعب توتنهام هوتسبير',
        'c' => 'الإمارات',
        'd' => 'الحيوية (Vitality)',
        'correct' => 'b',
    ],
    [
        'category' => 'premier-league',
        'difficulty' => 'very_hard',
        'question' => 'من هو اللاعب الذي سجل أسرع هدف في تاريخ البريميرليغ (7.69 ثانية)؟',
        'a' => 'تييري هنري',
        'b' => 'شين لونغ',
        'c' => 'آلان شيرر',
        'd' => 'ساديو ماني',
        'correct' => 'b',
    ],
];
