<?php
return [
    [
        'category' => 'special-dates',
        'difficulty' => 'medium',
        'question' => 'في أي يوم يُحتفل باليوم العالمي للمرأة؟',
        'a' => '8 مارس',
        'b' => '21 مارس',
        'c' => '1 مايو',
        'd' => '12 فبراير',
        'correct' => 'a',
    ],
    [
        'category' => 'special-dates',
        'difficulty' => 'medium',
        'question' => 'في أي تاريخ يُحتفل بعيد الاستقلال في الولايات المتحدة الأمريكية؟',
        'a' => '14 يوليو',
        'b' => '4 يوليو',
        'c' => '1 أغسطس',
        'd' => '17 سبتمبر',
        'correct' => 'b',
    ],
    [
        'category' => 'special-dates',
        'difficulty' => 'medium',
        'question' => 'ما هو اليوم العالمي للغة العربية؟',
        'a' => '18 ديسمبر',
        'b' => '21 فبراير',
        'c' => '1 مارس',
        'd' => '15 نوفمبر',
        'correct' => 'a',
    ],
    [
        'category' => 'special-dates',
        'difficulty' => 'hard',
        'question' => 'في أي يوم يُحتفل باليوم العالمي للسلام؟',
        'a' => '1 يناير',
        'b' => '21 سبتمبر',
        'c' => '10 ديسمبر',
        'd' => '24 أكتوبر',
        'correct' => 'b',
    ],
    [
        'category' => 'special-dates',
        'difficulty' => 'hard',
        'question' => 'ما هو التاريخ الذي يُصادف اليوم العالمي للبيئة؟',
        'a' => '22 أبريل',
        'b' => '5 يونيو',
        'c' => '16 سبتمبر',
        'd' => '2 فبراير',
        'correct' => 'b',
    ],
    [
        'category' => 'special-dates',
        'difficulty' => 'hard',
        'question' => 'في أي يوم يُحتفل باليوم العالمي للعمال؟',
        'a' => '1 مايو',
        'b' => '4 يوليو',
        'c' => '8 مارس',
        'd' => '14 فبراير',
        'correct' => 'a',
    ],
    [
        'category' => 'special-dates',
        'difficulty' => 'very_hard',
        'question' => 'ما هو اليوم العالمي المخصص للتوعية بمرض التوحد؟',
        'a' => '2 أبريل',
        'b' => '7 أبريل',
        'c' => '10 أكتوبر',
        'd' => '14 نوفمبر',
        'correct' => 'a',
    ],
    [
        'category' => 'special-dates',
        'difficulty' => 'very_hard',
        'question' => 'في أي تاريخ يُصادف اليوم العالمي للمياه؟',
        'a' => '22 مارس',
        'b' => '5 يونيو',
        'c' => '18 ديسمبر',
        'd' => '16 أكتوبر',
        'correct' => 'a',
    ],
    [
        'category' => 'special-dates',
        'difficulty' => 'very_hard',
        'question' => 'ما هو اليوم العالمي للصحة النفسية؟',
        'a' => '7 أبريل',
        'b' => '10 أكتوبر',
        'c' => '1 ديسمبر',
        'd' => '15 مارس',
        'correct' => 'b',
    ],
    [
        'category' => 'special-dates',
        'difficulty' => 'very_hard',
        'question' => 'في أي يوم يُحتفل باليوم العالمي للتطوع؟',
        'a' => '5 ديسمبر',
        'b' => '3 ديسمبر',
        'c' => '18 ديسمبر',
        'd' => '1 ديسمبر',
        'correct' => 'a',
    ],
];
