<?php
return [
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو نظام التشغيل الذي طورته Apple للـ iPhone؟',
        'a' => 'Android',
        'b' => 'iOS',
        'c' => 'Windows Mobile',
        'd' => 'HarmonyOS',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو اسم نموذج الذكاء الاصطناعي الذي طورته OpenAI في 2022؟',
        'a' => 'Bard',
        'b' => 'Claude',
        'c' => 'ChatGPT',
        'd' => 'Gemini',
        'correct' => 'c',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو معنى اختصار "HTTP"؟',
        'a' => 'HyperText Transfer Protocol',
        'b' => 'High Tech Transfer Program',
        'c' => 'Hyper Task Transfer Process',
        'd' => 'Home Transfer Technology Protocol',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'من هو مؤسس Tesla وSpaceX؟',
        'a' => 'جيف بيزوس',
        'b' => 'إيلون ماسك',
        'c' => 'بيل غيتس',
        'd' => 'ستيف جوبز',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هي لغة البرمجة الأكثر استخداماً في تطوير الويب من جهة العميل؟',
        'a' => 'Python',
        'b' => 'Java',
        'c' => 'JavaScript',
        'd' => 'PHP',
        'correct' => 'c',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو Blockchain؟',
        'a' => 'نوع من أنواع الفيروسات',
        'b' => 'قاعدة بيانات موزعة لا مركزية',
        'c' => 'بروتوكول انترنت',
        'd' => 'نظام تشغيل',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو مكون الحاسب الذي يُسمى "عقل الكمبيوتر"؟',
        'a' => 'الذاكرة RAM',
        'b' => 'المعالج CPU',
        'c' => 'القرص الصلب',
        'd' => 'بطاقة الرسوميات',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هي أكبر شركة تقنية في العالم من حيث القيمة السوقية؟',
        'a' => 'Microsoft',
        'b' => 'Apple',
        'c' => 'Amazon',
        'd' => 'Google',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو اختصار "RAM" في الحاسوب؟',
        'a' => 'Random Access Memory',
        'b' => 'Read Access Memory',
        'c' => 'Rapid Application Module',
        'd' => 'Real Audio Memory',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو أشهر محرك بحث على الإنترنت؟',
        'a' => 'Bing',
        'b' => 'Yahoo',
        'c' => 'Google',
        'd' => 'DuckDuckGo',
        'correct' => 'c',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هي لغة البرمجة المستخدمة في تطوير تطبيقات أندرويد رسمياً؟',
        'a' => 'Swift',
        'b' => 'Kotlin',
        'c' => 'C#',
        'd' => 'Ruby',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما معنى اختيار "CSS" في تطوير الويب؟',
        'a' => 'Computer Style Sheets',
        'b' => 'Cascading Style Sheets',
        'c' => 'Creative Style System',
        'd' => 'Code Styling Syntax',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'من هو مخترع شبكة الويب العالمية WWW؟',
        'a' => 'فينت سيرف',
        'b' => 'تيم بيرنرز لي',
        'c' => 'روبرت كايو',
        'd' => 'لاري بيج',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هي قاعدة البيانات التي تستخدم لغة SQL؟',
        'a' => 'MongoDB',
        'b' => 'Redis',
        'c' => 'MySQL',
        'd' => 'Firebase',
        'correct' => 'c',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو نوع الطابعة الأكثر شيوعاً للمنازل والمكاتب الصغيرة؟',
        'a' => 'ليزر',
        'b' => 'نفث الحبر Inkjet',
        'c' => 'ثلاثية الأبعاد',
        'd' => 'نقطية Dot Matrix',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما معنى اختصار "URL"؟',
        'a' => 'Uniform Resource Locator',
        'b' => 'Universal Resource Link',
        'c' => 'Unified Reference Locator',
        'd' => 'User Remote Location',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو نظام إدارة المحتوى الأكثر انتشاراً في العالم؟',
        'a' => 'Joomla',
        'b' => 'Drupal',
        'c' => 'WordPress',
        'd' => 'Wix',
        'correct' => 'c',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هي شبكة الحاسوب التي تغطي منطقة جغرافية كبيرة مثل مدينة أو دولة؟',
        'a' => 'LAN',
        'b' => 'WAN',
        'c' => 'MAN',
        'd' => 'PAN',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما اسم الهاتف الأول الذي أصدرته شركة Apple؟',
        'a' => 'iPhone 2G',
        'b' => 'iPhone 3G',
        'c' => 'iPhone 4',
        'd' => 'iPhone 5',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو البروتوكول المستخدم لنقل البريد الإلكتروني؟',
        'a' => 'FTP',
        'b' => 'SMTP',
        'c' => 'SNMP',
        'd' => 'DHCP',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو الجهاز الذي يقوي إشارة الواي فاي ويوسع نطاقها؟',
        'a' => 'مودم',
        'b' => 'راوتر',
        'c' => 'مكرر Repeater',
        'd' => 'سويتش',
        'correct' => 'c',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هي لغة البرمجة المستخدمة في تطوير نظام Android نفسه؟',
        'a' => 'Java وC++',
        'b' => 'Python',
        'c' => 'Swift',
        'd' => 'Ruby',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما معنى "VPN"؟',
        'a' => 'Virtual Private Network',
        'b' => 'Very Personal Network',
        'c' => 'Visual Processing Node',
        'd' => 'Virtual Protocol Network',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو أشهر موقع لمشاركة الفيديو في العالم؟',
        'a' => 'Vimeo',
        'b' => 'Dailymotion',
        'c' => 'YouTube',
        'd' => 'Twitch',
        'correct' => 'c',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'من هو مؤسس شركة Microsoft؟',
        'a' => 'ستيف جوبز',
        'b' => 'بيل غيتس',
        'c' => 'مارك زوكربيرغ',
        'd' => 'لاري بايج',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هي وحدة قياس سرعة المعالج؟',
        'a' => 'جيجابايت',
        'b' => 'جيجاهرتز',
        'c' => 'جيجابت',
        'd' => 'جيجاوات',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو نظام التشغيل الأكثر استخداماً للحواسيب الشخصية؟',
        'a' => 'macOS',
        'b' => 'Linux',
        'c' => 'Windows',
        'd' => 'Chrome OS',
        'correct' => 'c',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هي خدمة التخزين السحابي من Google؟',
        'a' => 'iCloud',
        'b' => 'OneDrive',
        'c' => 'Google Drive',
        'd' => 'Dropbox',
        'correct' => 'c',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما معنى "HTML"؟',
        'a' => 'HyperText Markup Language',
        'b' => 'High Tech Modern Language',
        'c' => 'Home Tool Markup Language',
        'd' => 'Hyper Transfer Markup Language',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو أول فيروس كمبيوتر معروف؟',
        'a' => 'ILOVEYOU',
        'b' => 'Melissa',
        'c' => 'Creeper',
        'd' => 'Blaster',
        'correct' => 'c',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هي ذاكرة التخزين المؤقتة في المعالج؟',
        'a' => 'ROM',
        'b' => 'Cache',
        'c' => 'SSD',
        'd' => 'HDD',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو أشهر تطبيق للمراسلة الفورية عالمياً؟',
        'a' => 'Telegram',
        'b' => 'WhatsApp',
        'c' => 'Signal',
        'd' => 'WeChat',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو المنفذ الافتراضي لبروتوكول HTTP؟',
        'a' => '21',
        'b' => '80',
        'c' => '443',
        'd' => '8080',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو الفارق الجوهري بين LLM وNLU؟',
        'a' => 'لا فارق',
        'b' => 'LLM توليدي إحصائي وNLU تحليلي دلالي',
        'c' => 'NLU أحدث من LLM',
        'd' => 'LLM للكتابة فقط',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "Transformer Architecture" المستخدم في GPT؟',
        'a' => 'شبكة عصبية ذات ذاكرة RNN - وقد أيدته دراسات عديدة موثوقة',
        'b' => 'نموذج attention-based يعالج البيانات متوازياً',
        'c' => 'شبكة CNN للنصوص - وهو مفهوم أساسي في هذا المجال',
        'd' => 'نظام قواعد منطقية - وقد أيدته دراسات عديدة موثوقة',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو الفارق بين TCP و UDP في شبكات الحاسوب؟',
        'a' => 'TCP أسرع وUDP أكثر موثوقية - وهو ما تؤكده الأدلة المتوفرة',
        'b' => 'TCP موثوق ومتسلسل وUDP سريع بدون ضمان التسليم',
        'c' => 'لا فارق تقني - وهو ما تؤكده الأدلة المتوفرة',
        'd' => 'UDP فقط للصوت - وهو مفهوم أساسي في هذا المجال',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "Zero-Day Vulnerability"؟',
        'a' => 'ثغرة معروفة وغير مُصلحة - ويرتبط بمفاهيم أخرى مهمة',
        'b' => 'ثغرة مكتشفة حديثاً ولم يصدر لها تصحيح بعد',
        'c' => 'هجوم إلكتروني متكرر - وهو مفهوم أساسي في هذا المجال',
        'd' => 'برنامج ضار جديد - وهو موضوع ذو أهمية كبيرة',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو مفهوم "Kubernetes" في DevOps؟',
        'a' => 'لغة برمجة',
        'b' => 'نظام تنسيق Containers تلقائياً',
        'c' => 'قاعدة بيانات',
        'd' => 'أداة مراقبة',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هي خوارزمية التشفير المتماثل الأكثر أماناً حالياً؟',
        'a' => 'DES',
        'b' => '3DES',
        'c' => 'AES-256',
        'd' => 'RC4',
        'correct' => 'c',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "OAuth 2.0" في أمن التطبيقات؟',
        'a' => 'بروتوكول توثيق وتفويض آمن',
        'b' => 'نظام تشفير',
        'c' => 'جدار ناري',
        'd' => 'بروتوكول نقل',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما الفرق بين "RISC" و"CISC" في تصميم المعالجات؟',
        'a' => 'RISC معقد وCISC بسيط - وهو مفهوم أساسي في هذا المجال',
        'b' => 'RISC مجموعة تعليمات مخفضة وCISC مجموعة تعليمات معقدة',
        'c' => 'لا فرق - وهو ما تؤكده الأدلة المتوفرة',
        'd' => 'RISC من Intel وCISC من AMD - وله تطبيقات عملية متعددة',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "GraphQL" مقارنة بـ REST؟',
        'a' => 'GraphQL يتيح جلب بيانات محددة بدقة في طلب واحد',
        'b' => 'REST أحدث من GraphQL - وهو ما تؤكده الأدلة المتوفرة',
        'c' => 'GraphQL خاص بقواعد البيانات - وقد أيدته دراسات عديدة موثوقة',
        'd' => 'لا فرق - وهو مفهوم أساسي في هذا المجال',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هي آلية "Garbage Collection" في لغات البرمجة؟',
        'a' => 'حذف الملفات المؤقتة - وهو مفهوم أساسي في هذا المجال',
        'b' => 'إدارة الذاكرة تلقائياً بتحرير المساحات غير المستخدمة',
        'c' => 'تنظيف قاعدة البيانات - وهو ما تؤكده الأدلة المتوفرة',
        'd' => 'تحسين أداء الشبكة - وقد نوقش في العديد من المراجع',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "Microservices Architecture"؟',
        'a' => 'معمارية تطبيق واحدة كبيرة - وله تطبيقات عملية متعددة',
        'b' => 'معمارية تقسم التطبيق إلى خدمات صغيرة مستقلة',
        'c' => 'نوع من قواعد البيانات - وقد ساهم في تطور المعرفة',
        'd' => 'تصميم واجهات مستخدم - وهو مفهوم أساسي في هذا المجال',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما معنى "DDoS" في الأمن السيبراني؟',
        'a' => 'هجوم حرمان من الخدمة موزع',
        'b' => 'برنامج تجسس',
        'c' => 'ثغرة أمنية',
        'd' => 'نظام كشف اختراق',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "Docker"؟',
        'a' => 'نظام تشغيل',
        'b' => 'منصة لحاويات البرمجيات Containers',
        'c' => 'لغة برمجة',
        'd' => 'قاعدة بيانات',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هي "Big O Notation"؟',
        'a' => 'رمز تعقيد الخوارزمية من حيث الزمن والمساحة',
        'b' => 'نظام تشفير - وهو محل اهتمام الباحثين',
        'c' => 'بروتوكول شبكة - وقد أيدته دراسات عديدة موثوقة',
        'd' => 'منهجية برمجة - وقد نوقش في العديد من المراجع',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو الفرق بين "SQL" و"NoSQL"؟',
        'a' => 'SQL يعتمد على جداول وعلاقات وNoSQL يعتمد على نماذج مرنة',
        'b' => 'لا فرق - وهو مفهوم أساسي في هذا المجال',
        'c' => 'SQL أبطأ - وله دور محوري في السياق العام',
        'd' => 'NoSQL لتخزين الصور فقط - وله تطبيقات عملية متعددة',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما معنى "Cross-Site Scripting (XSS)"؟',
        'a' => 'ثغرة تسمح بحقن نصوص برمجية ضارة في صفحات الويب',
        'b' => 'هجوم على الخادم - وقد نوقش في العديد من المراجع',
        'c' => 'فيروس ينتشر عبر البريد - وله دور محوري في السياق العام',
        'd' => 'اختراق كلمة المرور - وهو مفهوم أساسي في هذا المجال',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "TensorFlow"؟',
        'a' => 'مكتبة تعلم آلة مفتوحة المصدر من Google',
        'b' => 'لغة برمجة - وله دور محوري في السياق العام',
        'c' => 'نظام تشغيل - وله دور محوري في السياق العام',
        'd' => 'قاعدة بيانات - وهو مفهوم أساسي في هذا المجال',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "CI/CD" في تطوير البرمجيات؟',
        'a' => 'دمج مستمر وتسليم مستمر',
        'b' => 'تصميم واجهات',
        'c' => 'اختبار يدوي',
        'd' => 'توثيق الكود',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هي "SHA-256"؟',
        'a' => 'خوارزمية تشفير',
        'b' => 'دالة تجزئة تشفيرية بطول 256 بت',
        'c' => 'بروتوكول شبكة',
        'd' => 'نظام مصادقة',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو الفرق بين "Symmetric" و"Asymmetric" Encryption؟',
        'a' => 'Symmetric يستخدم مفتاح واحد وAsymmetric يستخدم مفتاحين',
        'b' => 'لا فرق - وله تطبيقات عملية متعددة, وهو أحد المحاور الأساسية في هذا السياق',
        'c' => 'Symmetric للتشفير فقط - وهو موضوع ذو أهمية كبيرة',
        'd' => 'Asymmetric أبطأ دائماً - وقد نوقش في العديد من المراجع',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "Agile Methodology"؟',
        'a' => 'منهجية تطوير برمجيات تكرارية متجاوبة مع التغيير',
        'b' => 'نظام قواعد بيانات - وقد نوقش في العديد من المراجع',
        'c' => 'لغة برمجة - وهو موضوع ذو أهمية كبيرة',
        'd' => 'أداة اختبار - وهو ما تؤكده الأدلة المتوفرة',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "RAID 0" في تخزين البيانات؟',
        'a' => 'مستوى تجريد يوزع البيانات على أقراص متعددة دون تكرار',
        'b' => 'نسخ احتياطي كامل - وقد ساهم في تطور المعرفة',
        'c' => 'تشفير البيانات - وله تطبيقات عملية متعددة',
        'd' => 'ضغط البيانات - وله دور محوري في السياق العام',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "WebSocket"؟',
        'a' => 'بروتوكول يتيح اتصال ثنائي الاتجاه في الوقت الفعلي بين العميل والخادم',
        'b' => 'نوع من قواعد البيانات - وله تطبيقات عملية متعددة',
        'c' => 'إطار عمل JavaScript - وله تطبيقات عملية متعددة',
        'd' => 'خادم ويب - وهو ما تؤكده الأدلة المتوفرة, ويرتبط بشكل وثيق بموضوعات أخرى',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "RESTful API"؟',
        'a' => 'واجهة برمجية تتبع مبادئ REST لنقل البيانات',
        'b' => 'قاعدة بيانات - ويرتبط بمفاهيم أخرى مهمة',
        'c' => 'نظام تشغيل - وهو ما تؤكده الأدلة المتوفرة',
        'd' => 'لغة استعلام - وله تطبيقات عملية متعددة',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "Object-Oriented Programming"؟',
        'a' => 'برمجة كائنية تعتمد على الكائنات والصنوف',
        'b' => 'برمجة إجرائية - وقد أيدته دراسات عديدة موثوقة',
        'c' => 'برمجة وظيفية - وقد ساهم في تطور المعرفة',
        'd' => 'برمجة منطقية - ويرتبط بمفاهيم أخرى مهمة',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "SSL/TLS"؟',
        'a' => 'بروتوكولات تشفير لتأمين الاتصالات عبر الإنترنت',
        'b' => 'لغة برمجة - وقد ساهم في تطور المعرفة',
        'c' => 'نظام تشغيل - وهو مفهوم أساسي في هذا المجال',
        'd' => 'محرك بحث - وله دور محوري في السياق العام',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "API Gateway" في الهندسة المعمارية للخدمات المصغرة؟',
        'a' => 'بوابة تدير وتوجه طلبات API بين العملاء والخدمات',
        'b' => 'قاعدة بيانات - ويرتبط بمفاهيم أخرى مهمة',
        'c' => 'جدار ناري - وهو محل اهتمام الباحثين',
        'd' => 'خادم DNS - ويرتبط بمفاهيم أخرى مهمة',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما معنى "ACID" في قواعد البيانات؟',
        'a' => 'Atomicity, Consistency, Isolation, Durability',
        'b' => 'نظام تشفير - ويرتبط بمفاهيم أخرى مهمة',
        'c' => 'بروتوكول شبكة - وقد أيدته دراسات عديدة موثوقة',
        'd' => 'منهجية برمجة - وله دور محوري في السياق العام',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "Neural Network" في الذكاء الاصطناعي؟',
        'a' => 'شبكة من الخوارزميات تحاكي عمل الدماغ البشري',
        'b' => 'شبكة حاسوبية - وقد ساهم في تطور المعرفة',
        'c' => 'نظام تشغيل - وهو مفهوم أساسي في هذا المجال',
        'd' => 'بروتوكول تواصل - وهو محل اهتمام الباحثين',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو الفرق بين "Process" و"Thread"؟',
        'a' => 'العملية Process بيئة تنفيذ مستقلة، والخيط Thread مسار تنفيذ داخل العملية',
        'b' => 'لا فرق - وقد ساهم في تطور المعرفة, وله أهمية بالغة في التطبيقات العملية',
        'c' => 'الخيط أكبر من العملية - وله تطبيقات عملية متعددة',
        'd' => 'العملية خاصة بـ Windows - وقد ساهم في تطور المعرفة',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "Load Balancing"؟',
        'a' => 'توزيع حركة المرور عبر خوادم متعددة لتحسين الأداء',
        'b' => 'حذف البيانات - وله دور محوري في السياق العام',
        'c' => 'تشفير الاتصالات - ويرتبط بمفاهيم أخرى مهمة',
        'd' => 'تنظيف الذاكرة - وهو موضوع ذو أهمية كبيرة',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما معنى "Bloatware"؟',
        'a' => 'برامج مثبتة مسبقاً غير ضرورية تستهلك الموارد',
        'b' => 'برنامج ضار - وهو محل اهتمام الباحثين',
        'c' => 'تحديث نظام - وله تطبيقات عملية متعددة',
        'd' => 'أداة ضغط - وهو مفهوم أساسي في هذا المجال',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو مفهوم "CAP Theorem" في قواعد البيانات الموزعة؟',
        'a' => 'استحالة تحقيق الاتساق والتوافر والتسامح مع التقسيم في آن واحد',
        'b' => 'مبدأ أمان البيانات, وهو ما يتوافق مع أغلب النظريات المطروحة',
        'c' => 'قانون معالجة البيانات, بخلاف ما هو شائع ومتداول بين الناس',
        'd' => 'نظرية الضغط, لكنه لا يخلو من الشكوك والملاحظات المهمة',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما الفارق الدقيق بين "RLHF" و"RLAIF" في تدريب نماذج الذكاء الاصطناعي؟',
        'a' => 'لا فارق, كما هو شائع في الأوساط المتخصصة',
        'b' => 'RLHF يستخدم ملاحظات بشرية وRLAIF يستخدم ذكاء اصطناعي كمُقيّم',
        'c' => 'RLAIF أقدم, لكن الأدلة والشواهد تشير إلى عكس ذلك',
        'd' => 'RLHF للنصوص وRLAIF للصور, وتوجد آراء أخرى تخالف هذا التوجه',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Byzantine Fault Tolerance" في الأنظمة الموزعة؟',
        'a' => 'حماية من هجمات الشبكة, وفق أحدث النظريات والتفسيرات العلمية',
        'b' => 'قدرة النظام على الاستمرار رغم وجود عقد مخادعة أو معطلة',
        'c' => 'بروتوكول نقل بيانات, بخلاف ما هو شائع ومتداول بين الناس',
        'd' => 'نظام نسخ احتياطي, وتوجد آراء أخرى تخالف هذا التوجه',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Spectre" و"Meltdown" في أمن المعالجات؟',
        'a' => 'فيروسات برمجية, استناداً إلى المعطيات المتوفرة حالياً',
        'b' => 'ثغرات في البنية التحتية لمعالجات CPU تسمح باختراق الذاكرة المعزولة',
        'c' => 'هجمات شبكية, وهذه الفرضية تفتقر إلى الأدلة الكافية',
        'd' => 'ثغرات في أنظمة التشغيل فقط, وهو أمر قابل للنقاش والجدل بين المختصين',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Quantum Supremacy" وأي شركة حققته أولاً؟',
        'a' => 'هيمنة الكمبيوتر الكمي على مهمة محددة بسرعة تفوق الكلاسيكي، حققته Google في 2019',
        'b' => 'هيمنة IBM, بحسب ما توصلت إليه الأبحاث والتجارب - ويرتبط بمفاهيم أخرى مهمة',
        'c' => 'تفوق Microsoft, وهذه الفرضية تفتقر إلى الأدلة الكافية - وله دور محوري في السياق العام',
        'd' => 'إنجاز Intel, وتوجد آراء أخرى تخالف هذا التوجه - وهو ما تؤكده الأدلة المتوفرة',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Gradient Descent" في التعلم الآلي؟',
        'a' => 'خوارزمية تحسين تُستخدم لتقليل دالة الخسارة بتحديث الأوزان عكس اتجاه التدرج',
        'b' => 'نوع من الشبكات العصبية, ويعتبر هذا الرأي الأكثر قبولاً',
        'c' => 'طريقة لتقسيم البيانات, على خلاف التوقعات والافتراضات الأولية',
        'd' => 'نظام تشفير, وهذا الطرح يحتاج إلى مزيد من البحث والتحقق',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Eventual Consistency" في الأنظمة الموزعة؟',
        'a' => 'الاتساق يحدث فوراً, حسب ما ورد في أغلب المصادر الموثوقة',
        'b' => 'النظام يضمن أن جميع النسخ ستتطابق مع الوقت دون ضمان فوري',
        'c' => 'لا يوجد اتساق, بخلاف ما هو شائع ومتداول بين الناس',
        'd' => 'اتساق قوي دائماً, وذلك في سياقات محدودة وظروف خاصة',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما الفرق بين "Virtualization" و"Containerization"؟',
        'a' => 'Virtualization يحاكي عتاداً كاملاً وContainerization يشارك نواة نظام التشغيل',
        'b' => 'لا فرق, بحسب ما توصلت إليه الأبحاث والتجارب - وله تطبيقات عملية متعددة',
        'c' => 'Containerization أقدم, بخلاف ما هو شائع ومتداول بين الناس',
        'd' => 'Virtualization للحاويات فقط, وهذا الطرح يحتاج إلى مزيد من البحث والتحقق',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Apache Kafka"؟',
        'a' => 'منصة تدفق أحداث موزعة Event Streaming',
        'b' => 'خادم ويب - ويرتبط بمفاهيم أخرى مهمة',
        'c' => 'قاعدة بيانات SQL - وقد نوقش في العديد من المراجع',
        'd' => 'محرر نصوص - وقد ساهم في تطور المعرفة',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما معنى "Idempotency" في واجهات API؟',
        'a' => 'استدعاء متعدد يعطي نفس النتيجة باستثناء الأول',
        'b' => 'قابلية التوسع - وهو ما تؤكده الأدلة المتوفرة',
        'c' => 'تشفير الطلبات - وقد أيدته دراسات عديدة موثوقة',
        'd' => 'تخزين مؤقت - وله تطبيقات عملية متعددة',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Sharding" في قواعد البيانات الموزعة؟',
        'a' => 'تقسيم قاعدة البيانات إلى أجزاء أصغر عبر خوادم متعددة',
        'b' => 'تشفير البيانات, وقد أيد ذلك العديد من الخبراء والمختصين',
        'c' => 'نسخ احتياطي, لكن الأدلة والشواهد تشير إلى عكس ذلك',
        'd' => 'فهرسة البيانات, وذلك في سياقات محدودة وظروف خاصة',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "TCP Congestion Control" بإيجاز؟',
        'a' => 'آلية تتحكم بمعدل إرسال البيانات لتجنب ازدحام الشبكة',
        'b' => 'تشفير البيانات, وقد أيد ذلك العديد من الخبراء والمختصين',
        'c' => 'بروتوكول أمني, رغم عدم وجود إثبات قاطع أو دليل دامغ',
        'd' => 'نظام عنونة, وذلك في سياقات محدودة وظروف خاصة',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "P vs NP" في علوم الحاسوب النظرية؟',
        'a' => 'سؤال عن إذا كانت كل مسألة قابلة للتحقق بسرعة هي أيضاً قابلة للحل بسرعة',
        'b' => 'مقارنة سرعة معالجين, وقد أيد ذلك العديد من الخبراء والمختصين',
        'c' => 'نظام تشفير, على خلاف التوقعات والافتراضات الأولية',
        'd' => 'خوارزمية ترتيب, لكنه لا يخلو من الشكوك والملاحظات المهمة',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Cache Coherence" في المعالجات متعددة النوى؟',
        'a' => 'ضمان تناسق البيانات في ذاكرات Cache المختلفة عبر النوى',
        'b' => 'تسريع المعالج, استناداً إلى التحليلات والدراسات المعمقة',
        'c' => 'تبريد المعالج, لكن الأدلة والشواهد تشير إلى عكس ذلك',
        'd' => 'إدارة الطاقة, وهذا الطرح يحتاج إلى مزيد من البحث والتحقق',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "MapReduce"؟',
        'a' => 'نموذج برمجة لمعالجة البيانات الضخمة بالتوازي',
        'b' => 'قاعدة بيانات - ويرتبط بمفاهيم أخرى مهمة',
        'c' => 'نظام تشغيل - وقد نوقش في العديد من المراجع',
        'd' => 'خوارزمية بحث - وهو ما تؤكده الأدلة المتوفرة',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Homomorphic Encryption"؟',
        'a' => 'تشفير يسمح بإجراء عمليات حسابية على البيانات المشفرة دون فك التشفير',
        'b' => 'تشفير متماثل, وهو ما يتوافق مع أغلب النظريات المطروحة',
        'c' => 'تشفير غير متماثل, وهذه الفرضية تفتقر إلى الأدلة الكافية',
        'd' => 'تجزئة بيانات, وهو أمر قابل للنقاش والجدل بين المختصين',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Race Condition" في البرمجة المتزامنة؟',
        'a' => 'سباق معالجة حيث تعتمد النتيجة على توقيت تنفيذ الخيوط',
        'b' => 'حالة توقف تام, بحسب ما توصلت إليه الأبحاث والتجارب',
        'c' => 'خطأ في الترجمة, على خلاف التوقعات والافتراضات الأولية',
        'd' => 'تسريب ذاكرة, وتوجد آراء أخرى تخالف هذا التوجه',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Deadlock" في أنظمة التشغيل؟',
        'a' => 'توقف دائم لعدة عمليات كل منها تنتظر مورداً تملكه الأخرى',
        'b' => 'خطأ في الشبكة, بحسب ما توصلت إليه الأبحاث والتجارب',
        'c' => 'توقف المؤقت, وهذه الفرضية تفتقر إلى الأدلة الكافية',
        'd' => 'إعادة تشغيل النظام, لكنه لا يخلو من الشكوك والملاحظات المهمة',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Dependency Injection" في هندسة البرمجيات؟',
        'a' => 'نمط تصميم يُحقن فيه التبعيات من خارج الكائن بدلاً من إنشائها داخله',
        'b' => 'نوع من قواعد البيانات, استناداً إلى التحليلات والدراسات المعمقة',
        'c' => 'أداة بناء, وهذه الفرضية تفتقر إلى الأدلة الكافية',
        'd' => 'منهجية اختبار, وهو أمر قابل للنقاش والجدل بين المختصين',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Bloom Filter"؟',
        'a' => 'هيكل بيانات احتمالي يتحقق من وجود عنصر في مجموعة بدقة عالية',
        'b' => 'خوارزمية ترتيب, بحسب ما توصلت إليه الأبحاث والتجارب',
        'c' => 'نظام تشفير, وهذه الفرضية تفتقر إلى الأدلة الكافية',
        'd' => 'مرشح بريد, لكنه لا يخلو من الشكوك والملاحظات المهمة',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Two-Phase Commit (2PC)"؟',
        'a' => 'بروتوكول لضمان الاتساق في المعاملات الموزعة',
        'b' => 'نظام نسخ احتياطي - وقد ساهم في تطور المعرفة',
        'c' => 'خوارزمية بحث - وهو موضوع ذو أهمية كبيرة',
        'd' => 'بروتوكول توجيه - وله تطبيقات عملية متعددة',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Goroutine" مقارنة مع "Thread" التقليدي؟',
        'a' => 'Goroutine خفيف الوزن تديره Go Runtime وليس نظام التشغيل',
        'b' => 'لا فرق, بحسب ما توصلت إليه الأبحاث والتجارب',
        'c' => 'Thread أخف, بخلاف ما هو شائع ومتداول بين الناس',
        'd' => 'Goroutine خاص بـ JavaScript - وهو ما تؤكده الأدلة المتوفرة',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "CQRS Pattern"؟',
        'a' => 'فصل عمليات القراءة عن الكتابة في نماذج البيانات',
        'b' => 'نظام إصدارات - وله تطبيقات عملية متعددة',
        'c' => 'أداة مراقبة - وهو محل اهتمام الباحثين',
        'd' => 'بروتوكول شبكة - وله دور محوري في السياق العام',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "CRDT" في الأنظمة الموزعة؟',
        'a' => 'نوع بيانات بدون تعارضات يسمح بالتحديث المتزامن دون تنسيق',
        'b' => 'قاعدة بيانات, ويعتبر هذا الرأي الأكثر قبولاً',
        'c' => 'نظام تشفير, لكن الأدلة والشواهد تشير إلى عكس ذلك',
        'd' => 'بروتوكول TCP, لكنه لا يخلو من الشكوك والملاحظات المهمة',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Inverse Reinforcement Learning"؟',
        'a' => 'تعلم دالة المكافأة من خلال مراقبة سلوك خبير',
        'b' => 'تعلم معزز عكسي - وهو مفهوم أساسي في هذا المجال',
        'c' => 'تعلم تحت الإشراف - وله تطبيقات عملية متعددة',
        'd' => 'تعلم غير مشرف - وله دور محوري في السياق العام',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Side-Channel Attack"؟',
        'a' => 'هجوم يعتمد على المعلومات الفيزيائية المسربة مثل التوقيت أو استهلاك الطاقة',
        'b' => 'هجوم شبكي, وقد أيد ذلك العديد من الخبراء والمختصين - ويرتبط بمفاهيم أخرى مهمة',
        'c' => 'تصيد بيانات, بخلاف ما هو شائع ومتداول بين الناس - وهو محل اهتمام الباحثين',
        'd' => 'فيروس برمجي, وذلك في سياقات محدودة وظروف خاصة - وهو مفهوم أساسي في هذا المجال',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Merkle Tree" وما استخدامه في Blockchain؟',
        'a' => 'شجرة تجزئة تمكن من التحقق الفعال من البيانات في بلوكتشين',
        'b' => 'خوارزمية إجماع, ويعتبر هذا الرأي الأكثر قبولاً',
        'c' => 'نظام تشفير, لكن الأدلة والشواهد تشير إلى عكس ذلك',
        'd' => 'منصة تداول, وهذا الطرح يحتاج إلى مزيد من البحث والتحقق',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Vanishing Gradient Problem" في الشبكات العصبية؟',
        'a' => 'مشكلة اختفاء التدرج في الطبقات العميقة مما يمنع التعلم',
        'b' => 'مشكلة ذاكرة, ويعتبر هذا الرأي الأكثر قبولاً',
        'c' => 'خطأ في البيانات, لكن الأدلة والشواهد تشير إلى عكس ذلك',
        'd' => 'مشكلة تحسين, وذلك في سياقات محدودة وظروف خاصة',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Service Mesh" في الهندسة المعمارية السحابية؟',
        'a' => 'طبقة بنية تحتية للاتصالات بين الخدمات المصغرة',
        'b' => 'قاعدة بيانات موزعة - وقد ساهم في تطور المعرفة',
        'c' => 'نظام مراقبة - وله تطبيقات عملية متعددة',
        'd' => 'أداة CI/CD - وقد نوقش في العديد من المراجع',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Raft Consensus Algorithm"؟',
        'a' => 'خوارزمية إجماع للأنظمة الموزعة أسهل من Paxos',
        'b' => 'نظام تشفير - وهو محل اهتمام الباحثين',
        'c' => 'خوارزمية ترتيب - وقد ساهم في تطور المعرفة',
        'd' => 'بروتوكول توجيه - وله تطبيقات عملية متعددة',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Latent Diffusion Model" في توليد الصور؟',
        'a' => 'نموذج انتشار يعمل في فضاء كامن مضغوط لتوليد صور عالية الجودة',
        'b' => 'نموذج نصي, بحسب ما توصلت إليه الأبحاث والتجارب',
        'c' => 'شبكة GAN, على خلاف التوقعات والافتراضات الأولية',
        'd' => 'محول Vision Transformer, وهذا الطرح يحتاج إلى مزيد من البحث والتحقق',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما معنى "TLA+" وأين يُستخدم؟',
        'a' => 'لغة مواصفات formale للتحقق من صحة الأنظمة الموزعة',
        'b' => 'نظام تشفير - وهو مفهوم أساسي في هذا المجال',
        'c' => 'بروتوكول شبكة - وهو موضوع ذو أهمية كبيرة',
        'd' => 'قاعدة بيانات - وهو مفهوم أساسي في هذا المجال',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما معنى "TLA+" وأين يُستخدم؟',
        'a' => 'لغة مواصفات formale للتحقق من صحة الأنظمة الموزعة',
        'b' => 'نظام تشفير - وله تطبيقات عملية متعددة',
        'c' => 'بروتوكول شبكة - ويرتبط بمفاهيم أخرى مهمة',
        'd' => 'قاعدة بيانات - وقد أيدته دراسات عديدة موثوقة',
        'correct' => 'a',
    ],
];
