<?php
return [
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو نظام التشغيل الذي طورته Apple للـ iPhone؟',
        'a' => 'Android',
        'b' => 'iOS',
        'c' => 'Windows Mobile',
        'd' => 'HarmonyOS',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو اسم نموذج الذكاء الاصطناعي الذي طورته OpenAI في 2022؟',
        'a' => 'Bard',
        'b' => 'Claude',
        'c' => 'ChatGPT',
        'd' => 'Gemini',
        'correct' => 'c',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو معنى اختصار "HTTP"؟',
        'a' => 'HyperText Transfer Protocol',
        'b' => 'High Tech Transfer Program',
        'c' => 'Hyper Task Transfer Process',
        'd' => 'Home Transfer Technology Protocol',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'من هو مؤسس Tesla وSpaceX؟',
        'a' => 'جيف بيزوس',
        'b' => 'إيلون ماسك',
        'c' => 'بيل غيتس',
        'd' => 'ستيف جوبز',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هي لغة البرمجة الأكثر استخداماً في تطوير الويب من جهة العميل؟',
        'a' => 'Python',
        'b' => 'Java',
        'c' => 'JavaScript',
        'd' => 'PHP',
        'correct' => 'c',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو Blockchain؟',
        'a' => 'نوع من أنواع الفيروسات',
        'b' => 'قاعدة بيانات موزعة لا مركزية',
        'c' => 'بروتوكول انترنت',
        'd' => 'نظام تشغيل',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو مكون الحاسب الذي يُسمى "عقل الكمبيوتر"؟',
        'a' => 'الذاكرة RAM',
        'b' => 'المعالج CPU',
        'c' => 'القرص الصلب',
        'd' => 'بطاقة الرسوميات',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هي أكبر شركة تقنية في العالم من حيث القيمة السوقية؟',
        'a' => 'Microsoft',
        'b' => 'Apple',
        'c' => 'Amazon',
        'd' => 'Google',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو اختصار "RAM" في الحاسوب؟',
        'a' => 'Random Access Memory',
        'b' => 'Read Access Memory',
        'c' => 'Rapid Application Module',
        'd' => 'Real Audio Memory',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو أشهر محرك بحث على الإنترنت؟',
        'a' => 'Bing',
        'b' => 'Yahoo',
        'c' => 'Google',
        'd' => 'DuckDuckGo',
        'correct' => 'c',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هي لغة البرمجة المستخدمة في تطوير تطبيقات أندرويد رسمياً؟',
        'a' => 'Swift',
        'b' => 'Kotlin',
        'c' => 'C#',
        'd' => 'Ruby',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما معنى اختيار "CSS" في تطوير الويب؟',
        'a' => 'Computer Style Sheets',
        'b' => 'Cascading Style Sheets',
        'c' => 'Creative Style System',
        'd' => 'Code Styling Syntax',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'من هو مخترع شبكة الويب العالمية WWW؟',
        'a' => 'فينت سيرف',
        'b' => 'تيم بيرنرز لي',
        'c' => 'روبرت كايو',
        'd' => 'لاري بيج',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هي قاعدة البيانات التي تستخدم لغة SQL؟',
        'a' => 'MongoDB',
        'b' => 'Redis',
        'c' => 'MySQL',
        'd' => 'Firebase',
        'correct' => 'c',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو نوع الطابعة الأكثر شيوعاً للمنازل والمكاتب الصغيرة؟',
        'a' => 'ليزر',
        'b' => 'نفث الحبر Inkjet',
        'c' => 'ثلاثية الأبعاد',
        'd' => 'نقطية Dot Matrix',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما معنى اختصار "URL"؟',
        'a' => 'Uniform Resource Locator',
        'b' => 'Universal Resource Link',
        'c' => 'Unified Reference Locator',
        'd' => 'User Remote Location',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو نظام إدارة المحتوى الأكثر انتشاراً في العالم؟',
        'a' => 'Joomla',
        'b' => 'Drupal',
        'c' => 'WordPress',
        'd' => 'Wix',
        'correct' => 'c',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هي شبكة الحاسوب التي تغطي منطقة جغرافية كبيرة مثل مدينة أو دولة؟',
        'a' => 'LAN',
        'b' => 'WAN',
        'c' => 'MAN',
        'd' => 'PAN',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما اسم الهاتف الأول الذي أصدرته شركة Apple؟',
        'a' => 'iPhone 2G',
        'b' => 'iPhone 3G',
        'c' => 'iPhone 4',
        'd' => 'iPhone 5',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو البروتوكول المستخدم لنقل البريد الإلكتروني؟',
        'a' => 'FTP',
        'b' => 'SMTP',
        'c' => 'SNMP',
        'd' => 'DHCP',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو الجهاز الذي يقوي إشارة الواي فاي ويوسع نطاقها؟',
        'a' => 'مودم',
        'b' => 'راوتر',
        'c' => 'مكرر Repeater',
        'd' => 'سويتش',
        'correct' => 'c',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هي لغة البرمجة المستخدمة في تطوير نظام Android نفسه؟',
        'a' => 'Java وC++',
        'b' => 'Python',
        'c' => 'Swift',
        'd' => 'Ruby',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما معنى "VPN"؟',
        'a' => 'Virtual Private Network',
        'b' => 'Very Personal Network',
        'c' => 'Visual Processing Node',
        'd' => 'Virtual Protocol Network',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو أشهر موقع لمشاركة الفيديو في العالم؟',
        'a' => 'Vimeo',
        'b' => 'Dailymotion',
        'c' => 'YouTube',
        'd' => 'Twitch',
        'correct' => 'c',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'من هو مؤسس شركة Microsoft؟',
        'a' => 'ستيف جوبز',
        'b' => 'بيل غيتس',
        'c' => 'مارك زوكربيرغ',
        'd' => 'لاري بايج',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هي وحدة قياس سرعة المعالج؟',
        'a' => 'جيجابايت',
        'b' => 'جيجاهرتز',
        'c' => 'جيجابت',
        'd' => 'جيجاوات',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو نظام التشغيل الأكثر استخداماً للحواسيب الشخصية؟',
        'a' => 'macOS',
        'b' => 'Linux',
        'c' => 'Windows',
        'd' => 'Chrome OS',
        'correct' => 'c',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هي خدمة التخزين السحابي من Google؟',
        'a' => 'iCloud',
        'b' => 'OneDrive',
        'c' => 'Google Drive',
        'd' => 'Dropbox',
        'correct' => 'c',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما معنى "HTML"؟',
        'a' => 'HyperText Markup Language',
        'b' => 'High Tech Modern Language',
        'c' => 'Home Tool Markup Language',
        'd' => 'Hyper Transfer Markup Language',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو أول فيروس كمبيوتر معروف؟',
        'a' => 'ILOVEYOU',
        'b' => 'Melissa',
        'c' => 'Creeper',
        'd' => 'Blaster',
        'correct' => 'c',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هي ذاكرة التخزين المؤقتة في المعالج؟',
        'a' => 'ROM',
        'b' => 'Cache',
        'c' => 'SSD',
        'd' => 'HDD',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو أشهر تطبيق للمراسلة الفورية عالمياً؟',
        'a' => 'Telegram',
        'b' => 'WhatsApp',
        'c' => 'Signal',
        'd' => 'WeChat',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'medium',
        'question' => 'ما هو المنفذ الافتراضي لبروتوكول HTTP؟',
        'a' => '21',
        'b' => '80',
        'c' => '443',
        'd' => '8080',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو الفارق الجوهري بين LLM وNLU؟',
        'a' => 'لا فارق',
        'b' => 'LLM توليدي إحصائي وNLU تحليلي دلالي',
        'c' => 'NLU أحدث من LLM',
        'd' => 'LLM للكتابة فقط',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "Transformer Architecture" المستخدم في GPT؟',
        'a' => 'شبكة عصبية ذات ذاكرة RNN',
        'b' => 'نموذج attention-based يعالج البيانات متوازياً',
        'c' => 'شبكة CNN للنصوص',
        'd' => 'نظام قواعد منطقية',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو الفارق بين TCP و UDP في شبكات الحاسوب؟',
        'a' => 'TCP أسرع وUDP أكثر موثوقية',
        'b' => 'TCP موثوق ومتسلسل وUDP سريع بدون ضمان التسليم',
        'c' => 'لا فارق تقني',
        'd' => 'UDP فقط للصوت',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "Zero-Day Vulnerability"؟',
        'a' => 'ثغرة معروفة وغير مُصلحة',
        'b' => 'ثغرة مكتشفة حديثاً ولم يصدر لها تصحيح بعد',
        'c' => 'هجوم إلكتروني متكرر',
        'd' => 'برنامج ضار جديد',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو مفهوم "Kubernetes" في DevOps؟',
        'a' => 'لغة برمجة',
        'b' => 'نظام تنسيق Containers تلقائياً',
        'c' => 'قاعدة بيانات',
        'd' => 'أداة مراقبة',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هي خوارزمية التشفير المتماثل الأكثر أماناً حالياً؟',
        'a' => 'DES',
        'b' => '3DES',
        'c' => 'AES-256',
        'd' => 'RC4',
        'correct' => 'c',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "OAuth 2.0" في أمن التطبيقات؟',
        'a' => 'بروتوكول توثيق وتفويض آمن',
        'b' => 'نظام تشفير',
        'c' => 'جدار ناري',
        'd' => 'بروتوكول نقل',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما الفرق بين "RISC" و"CISC" في تصميم المعالجات؟',
        'a' => 'RISC معقد وCISC بسيط',
        'b' => 'RISC مجموعة تعليمات مخفضة وCISC مجموعة تعليمات معقدة',
        'c' => 'لا فرق',
        'd' => 'RISC من Intel وCISC من AMD',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "GraphQL" مقارنة بـ REST؟',
        'a' => 'GraphQL يتيح جلب بيانات محددة بدقة في طلب واحد',
        'b' => 'REST أحدث من GraphQL',
        'c' => 'GraphQL خاص بقواعد البيانات',
        'd' => 'لا فرق',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هي آلية "Garbage Collection" في لغات البرمجة؟',
        'a' => 'حذف الملفات المؤقتة',
        'b' => 'إدارة الذاكرة تلقائياً بتحرير المساحات غير المستخدمة',
        'c' => 'تنظيف قاعدة البيانات',
        'd' => 'تحسين أداء الشبكة',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "Microservices Architecture"؟',
        'a' => 'معمارية تطبيق واحدة كبيرة',
        'b' => 'معمارية تقسم التطبيق إلى خدمات صغيرة مستقلة',
        'c' => 'نوع من قواعد البيانات',
        'd' => 'تصميم واجهات مستخدم',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما معنى "DDoS" في الأمن السيبراني؟',
        'a' => 'هجوم حرمان من الخدمة موزع',
        'b' => 'برنامج تجسس',
        'c' => 'ثغرة أمنية',
        'd' => 'نظام كشف اختراق',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "Docker"؟',
        'a' => 'نظام تشغيل',
        'b' => 'منصة لحاويات البرمجيات Containers',
        'c' => 'لغة برمجة',
        'd' => 'قاعدة بيانات',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هي "Big O Notation"؟',
        'a' => 'رمز تعقيد الخوارزمية من حيث الزمن والمساحة',
        'b' => 'نظام تشفير',
        'c' => 'بروتوكول شبكة',
        'd' => 'منهجية برمجة',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو الفرق بين "SQL" و"NoSQL"؟',
        'a' => 'SQL يعتمد على جداول وعلاقات وNoSQL يعتمد على نماذج مرنة',
        'b' => 'لا فرق',
        'c' => 'SQL أبطأ',
        'd' => 'NoSQL لتخزين الصور فقط',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما معنى "Cross-Site Scripting (XSS)"؟',
        'a' => 'ثغرة تسمح بحقن نصوص برمجية ضارة في صفحات الويب',
        'b' => 'هجوم على الخادم',
        'c' => 'فيروس ينتشر عبر البريد',
        'd' => 'اختراق كلمة المرور',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "TensorFlow"؟',
        'a' => 'مكتبة تعلم آلة مفتوحة المصدر من Google',
        'b' => 'لغة برمجة',
        'c' => 'نظام تشغيل',
        'd' => 'قاعدة بيانات',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "CI/CD" في تطوير البرمجيات؟',
        'a' => 'دمج مستمر وتسليم مستمر',
        'b' => 'تصميم واجهات',
        'c' => 'اختبار يدوي',
        'd' => 'توثيق الكود',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هي "SHA-256"؟',
        'a' => 'خوارزمية تشفير',
        'b' => 'دالة تجزئة تشفيرية بطول 256 بت',
        'c' => 'بروتوكول شبكة',
        'd' => 'نظام مصادقة',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو الفرق بين "Symmetric" و"Asymmetric" Encryption؟',
        'a' => 'Symmetric يستخدم مفتاح واحد وAsymmetric يستخدم مفتاحين',
        'b' => 'لا فرق',
        'c' => 'Symmetric للتشفير فقط',
        'd' => 'Asymmetric أبطأ دائماً',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "Agile Methodology"؟',
        'a' => 'منهجية تطوير برمجيات تكرارية متجاوبة مع التغيير',
        'b' => 'نظام قواعد بيانات',
        'c' => 'لغة برمجة',
        'd' => 'أداة اختبار',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "RAID 0" في تخزين البيانات؟',
        'a' => 'مستوى تجريد يوزع البيانات على أقراص متعددة دون تكرار',
        'b' => 'نسخ احتياطي كامل',
        'c' => 'تشفير البيانات',
        'd' => 'ضغط البيانات',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "WebSocket"؟',
        'a' => 'بروتوكول يتيح اتصال ثنائي الاتجاه في الوقت الفعلي بين العميل والخادم',
        'b' => 'نوع من قواعد البيانات',
        'c' => 'إطار عمل JavaScript',
        'd' => 'خادم ويب',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "RESTful API"؟',
        'a' => 'واجهة برمجية تتبع مبادئ REST لنقل البيانات',
        'b' => 'قاعدة بيانات',
        'c' => 'نظام تشغيل',
        'd' => 'لغة استعلام',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "Object-Oriented Programming"؟',
        'a' => 'برمجة كائنية تعتمد على الكائنات والصنوف',
        'b' => 'برمجة إجرائية',
        'c' => 'برمجة وظيفية',
        'd' => 'برمجة منطقية',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "SSL/TLS"؟',
        'a' => 'بروتوكولات تشفير لتأمين الاتصالات عبر الإنترنت',
        'b' => 'لغة برمجة',
        'c' => 'نظام تشغيل',
        'd' => 'محرك بحث',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "API Gateway" في الهندسة المعمارية للخدمات المصغرة؟',
        'a' => 'بوابة تدير وتوجه طلبات API بين العملاء والخدمات',
        'b' => 'قاعدة بيانات',
        'c' => 'جدار ناري',
        'd' => 'خادم DNS',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما معنى "ACID" في قواعد البيانات؟',
        'a' => 'Atomicity, Consistency, Isolation, Durability',
        'b' => 'نظام تشفير',
        'c' => 'بروتوكول شبكة',
        'd' => 'منهجية برمجة',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "Neural Network" في الذكاء الاصطناعي؟',
        'a' => 'شبكة من الخوارزميات تحاكي عمل الدماغ البشري',
        'b' => 'شبكة حاسوبية',
        'c' => 'نظام تشغيل',
        'd' => 'بروتوكول تواصل',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو الفرق بين "Process" و"Thread"؟',
        'a' => 'العملية Process بيئة تنفيذ مستقلة، والخيط Thread مسار تنفيذ داخل العملية',
        'b' => 'لا فرق',
        'c' => 'الخيط أكبر من العملية',
        'd' => 'العملية خاصة بـ Windows',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما هو "Load Balancing"؟',
        'a' => 'توزيع حركة المرور عبر خوادم متعددة لتحسين الأداء',
        'b' => 'حذف البيانات',
        'c' => 'تشفير الاتصالات',
        'd' => 'تنظيف الذاكرة',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'hard',
        'question' => 'ما معنى "Bloatware"؟',
        'a' => 'برامج مثبتة مسبقاً غير ضرورية تستهلك الموارد',
        'b' => 'برنامج ضار',
        'c' => 'تحديث نظام',
        'd' => 'أداة ضغط',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو مفهوم "CAP Theorem" في قواعد البيانات الموزعة؟',
        'a' => 'استحالة تحقيق الاتساق والتوافر والتسامح مع التقسيم في آن واحد',
        'b' => 'مبدأ أمان البيانات',
        'c' => 'قانون معالجة البيانات',
        'd' => 'نظرية الضغط',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما الفارق الدقيق بين "RLHF" و"RLAIF" في تدريب نماذج الذكاء الاصطناعي؟',
        'a' => 'لا فارق',
        'b' => 'RLHF يستخدم ملاحظات بشرية وRLAIF يستخدم ذكاء اصطناعي كمُقيّم',
        'c' => 'RLAIF أقدم',
        'd' => 'RLHF للنصوص وRLAIF للصور',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Byzantine Fault Tolerance" في الأنظمة الموزعة؟',
        'a' => 'حماية من هجمات الشبكة',
        'b' => 'قدرة النظام على الاستمرار رغم وجود عقد مخادعة أو معطلة',
        'c' => 'بروتوكول نقل بيانات',
        'd' => 'نظام نسخ احتياطي',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Spectre" و"Meltdown" في أمن المعالجات؟',
        'a' => 'فيروسات برمجية',
        'b' => 'ثغرات في البنية التحتية لمعالجات CPU تسمح باختراق الذاكرة المعزولة',
        'c' => 'هجمات شبكية',
        'd' => 'ثغرات في أنظمة التشغيل فقط',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Quantum Supremacy" وأي شركة حققته أولاً؟',
        'a' => 'هيمنة الكمبيوتر الكمي على مهمة محددة بسرعة تفوق الكلاسيكي، حققته Google في 2019',
        'b' => 'هيمنة IBM',
        'c' => 'تفوق Microsoft',
        'd' => 'إنجاز Intel',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Gradient Descent" في التعلم الآلي؟',
        'a' => 'خوارزمية تحسين تُستخدم لتقليل دالة الخسارة بتحديث الأوزان عكس اتجاه التدرج',
        'b' => 'نوع من الشبكات العصبية',
        'c' => 'طريقة لتقسيم البيانات',
        'd' => 'نظام تشفير',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Eventual Consistency" في الأنظمة الموزعة؟',
        'a' => 'الاتساق يحدث فوراً',
        'b' => 'النظام يضمن أن جميع النسخ ستتطابق مع الوقت دون ضمان فوري',
        'c' => 'لا يوجد اتساق',
        'd' => 'اتساق قوي دائماً',
        'correct' => 'b',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما الفرق بين "Virtualization" و"Containerization"؟',
        'a' => 'Virtualization يحاكي عتاداً كاملاً وContainerization يشارك نواة نظام التشغيل',
        'b' => 'لا فرق',
        'c' => 'Containerization أقدم',
        'd' => 'Virtualization للحاويات فقط',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Apache Kafka"؟',
        'a' => 'منصة تدفق أحداث موزعة Event Streaming',
        'b' => 'خادم ويب',
        'c' => 'قاعدة بيانات SQL',
        'd' => 'محرر نصوص',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما معنى "Idempotency" في واجهات API؟',
        'a' => 'استدعاء متعدد يعطي نفس النتيجة باستثناء الأول',
        'b' => 'قابلية التوسع',
        'c' => 'تشفير الطلبات',
        'd' => 'تخزين مؤقت',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Sharding" في قواعد البيانات الموزعة؟',
        'a' => 'تقسيم قاعدة البيانات إلى أجزاء أصغر عبر خوادم متعددة',
        'b' => 'تشفير البيانات',
        'c' => 'نسخ احتياطي',
        'd' => 'فهرسة البيانات',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "TCP Congestion Control" بإيجاز؟',
        'a' => 'آلية تتحكم بمعدل إرسال البيانات لتجنب ازدحام الشبكة',
        'b' => 'تشفير البيانات',
        'c' => 'بروتوكول أمني',
        'd' => 'نظام عنونة',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "P vs NP" في علوم الحاسوب النظرية؟',
        'a' => 'سؤال عن إذا كانت كل مسألة قابلة للتحقق بسرعة هي أيضاً قابلة للحل بسرعة',
        'b' => 'مقارنة سرعة معالجين',
        'c' => 'نظام تشفير',
        'd' => 'خوارزمية ترتيب',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Cache Coherence" في المعالجات متعددة النوى؟',
        'a' => 'ضمان تناسق البيانات في ذاكرات Cache المختلفة عبر النوى',
        'b' => 'تسريع المعالج',
        'c' => 'تبريد المعالج',
        'd' => 'إدارة الطاقة',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "MapReduce"؟',
        'a' => 'نموذج برمجة لمعالجة البيانات الضخمة بالتوازي',
        'b' => 'قاعدة بيانات',
        'c' => 'نظام تشغيل',
        'd' => 'خوارزمية بحث',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Homomorphic Encryption"؟',
        'a' => 'تشفير يسمح بإجراء عمليات حسابية على البيانات المشفرة دون فك التشفير',
        'b' => 'تشفير متماثل',
        'c' => 'تشفير غير متماثل',
        'd' => 'تجزئة بيانات',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Race Condition" في البرمجة المتزامنة؟',
        'a' => 'سباق معالجة حيث تعتمد النتيجة على توقيت تنفيذ الخيوط',
        'b' => 'حالة توقف تام',
        'c' => 'خطأ في الترجمة',
        'd' => 'تسريب ذاكرة',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Deadlock" في أنظمة التشغيل؟',
        'a' => 'توقف دائم لعدة عمليات كل منها تنتظر مورداً تملكه الأخرى',
        'b' => 'خطأ في الشبكة',
        'c' => 'توقف المؤقت',
        'd' => 'إعادة تشغيل النظام',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Dependency Injection" في هندسة البرمجيات؟',
        'a' => 'نمط تصميم يُحقن فيه التبعيات من خارج الكائن بدلاً من إنشائها داخله',
        'b' => 'نوع من قواعد البيانات',
        'c' => 'أداة بناء',
        'd' => 'منهجية اختبار',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Bloom Filter"؟',
        'a' => 'هيكل بيانات احتمالي يتحقق من وجود عنصر في مجموعة بدقة عالية',
        'b' => 'خوارزمية ترتيب',
        'c' => 'نظام تشفير',
        'd' => 'مرشح بريد',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Two-Phase Commit (2PC)"؟',
        'a' => 'بروتوكول لضمان الاتساق في المعاملات الموزعة',
        'b' => 'نظام نسخ احتياطي',
        'c' => 'خوارزمية بحث',
        'd' => 'بروتوكول توجيه',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Goroutine" مقارنة مع "Thread" التقليدي؟',
        'a' => 'Goroutine خفيف الوزن تديره Go Runtime وليس نظام التشغيل',
        'b' => 'لا فرق',
        'c' => 'Thread أخف',
        'd' => 'Goroutine خاص بـ JavaScript',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "CQRS Pattern"؟',
        'a' => 'فصل عمليات القراءة عن الكتابة في نماذج البيانات',
        'b' => 'نظام إصدارات',
        'c' => 'أداة مراقبة',
        'd' => 'بروتوكول شبكة',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "CRDT" في الأنظمة الموزعة؟',
        'a' => 'نوع بيانات بدون تعارضات يسمح بالتحديث المتزامن دون تنسيق',
        'b' => 'قاعدة بيانات',
        'c' => 'نظام تشفير',
        'd' => 'بروتوكول TCP',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Inverse Reinforcement Learning"؟',
        'a' => 'تعلم دالة المكافأة من خلال مراقبة سلوك خبير',
        'b' => 'تعلم معزز عكسي',
        'c' => 'تعلم تحت الإشراف',
        'd' => 'تعلم غير مشرف',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Side-Channel Attack"؟',
        'a' => 'هجوم يعتمد على المعلومات الفيزيائية المسربة مثل التوقيت أو استهلاك الطاقة',
        'b' => 'هجوم شبكي',
        'c' => 'تصيد بيانات',
        'd' => 'فيروس برمجي',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Merkle Tree" وما استخدامه في Blockchain؟',
        'a' => 'شجرة تجزئة تمكن من التحقق الفعال من البيانات في بلوكتشين',
        'b' => 'خوارزمية إجماع',
        'c' => 'نظام تشفير',
        'd' => 'منصة تداول',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Vanishing Gradient Problem" في الشبكات العصبية؟',
        'a' => 'مشكلة اختفاء التدرج في الطبقات العميقة مما يمنع التعلم',
        'b' => 'مشكلة ذاكرة',
        'c' => 'خطأ في البيانات',
        'd' => 'مشكلة تحسين',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Service Mesh" في الهندسة المعمارية السحابية؟',
        'a' => 'طبقة بنية تحتية للاتصالات بين الخدمات المصغرة',
        'b' => 'قاعدة بيانات موزعة',
        'c' => 'نظام مراقبة',
        'd' => 'أداة CI/CD',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Raft Consensus Algorithm"؟',
        'a' => 'خوارزمية إجماع للأنظمة الموزعة أسهل من Paxos',
        'b' => 'نظام تشفير',
        'c' => 'خوارزمية ترتيب',
        'd' => 'بروتوكول توجيه',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما هو "Latent Diffusion Model" في توليد الصور؟',
        'a' => 'نموذج انتشار يعمل في فضاء كامن مضغوط لتوليد صور عالية الجودة',
        'b' => 'نموذج نصي',
        'c' => 'شبكة GAN',
        'd' => 'محول Vision Transformer',
        'correct' => 'a',
    ],
    [
        'category' => 'technology',
        'difficulty' => 'very_hard',
        'question' => 'ما معنى "TLA+" وأين يُستخدم؟',
        'a' => 'لغة مواصفات formale للتحقق من صحة الأنظمة الموزعة',
        'b' => 'نظام تشفير',
        'c' => 'بروتوكول شبكة',
        'd' => 'قاعدة بيانات',
        'correct' => 'a',
    ],
];
