<?php

return [
    [
        'category' => 'the-walking-dead',
        'difficulty' => 'medium',
        'question' => 'من هو بطل مسلسل "The Walking Dead"؟',
        'a' => 'داريل ديكسون',
        'b' => 'ريك غرايمز',
        'c' => 'ميشون',
        'd' => 'غلين',
        'correct' => 'b',
    ],
    [
        'category' => 'the-walking-dead',
        'difficulty' => 'medium',
        'question' => 'ما هو اسم ابن ريك غرايمز في المسلسل؟',
        'a' => 'هنري',
        'b' => 'كارل',
        'c' => 'جوديث',
        'd' => 'كريس',
        'correct' => 'b',
    ],
    [
        'category' => 'the-walking-dead',
        'difficulty' => 'medium',
        'question' => 'ما هو اسم المستعمرة الأولى التي ينضم إليها ريك بعد خروجه من المستشفى؟',
        'a' => 'وودبيري',
        'b' => 'ألكساندريا',
        'c' => 'مخيم أتلانتا',
        'd' => 'المنطقة الآمنة',
        'correct' => 'c',
    ],
    [
        'category' => 'the-walking-dead',
        'difficulty' => 'hard',
        'question' => 'من هو الشرير الرئيسي في الموسم الثالث المعروف بـ "الحاكم"؟',
        'a' => 'نيكولاس',
        'b' => 'فيليب بليك',
        'c' => 'غاريث',
        'd' => 'داون',
        'correct' => 'b',
    ],
    [
        'category' => 'the-walking-dead',
        'difficulty' => 'hard',
        'question' => 'ما هو اسم المجموعة المعادية التي يقودها نيغان؟',
        'a' => 'المنقذون',
        'b' => 'الذئاب',
        'c' => 'الصيادون',
        'd' => 'المبتلعون',
        'correct' => 'a',
    ],
    [
        'category' => 'the-walking-dead',
        'difficulty' => 'hard',
        'question' => 'ما هي أداة داريل ديكسون المميزة؟',
        'a' => 'سيف كاتانا',
        'b' => 'قوس ونشاب',
        'c' => 'مضرب بيسبول مسامير',
        'd' => 'مسدس',
        'correct' => 'b',
    ],
    [
        'category' => 'the-walking-dead',
        'difficulty' => 'very_hard',
        'question' => 'في أي عام عُرضت الحلقة الأولى من المسلسل؟',
        'a' => '2009',
        'b' => '2010',
        'c' => '2011',
        'd' => '2012',
        'correct' => 'b',
    ],
    [
        'category' => 'the-walking-dead',
        'difficulty' => 'very_hard',
        'question' => 'كم عدد مواسم المسلسل الأصلية (حتى نهاية 2023)؟',
        'a' => '10',
        'b' => '12',
        'c' => '11',
        'd' => '9',
        'correct' => 'c',
    ],
    [
        'category' => 'the-walking-dead',
        'difficulty' => 'very_hard',
        'question' => 'ما هو اسم السيف الذي تستخدمه ميشون؟',
        'a' => 'سيف الشرف',
        'b' => 'كاتانا الساموراي',
        'c' => 'نصل الظل',
        'd' => 'سيف العزلة',
        'correct' => 'b',
    ],
    [
        'category' => 'the-walking-dead',
        'difficulty' => 'medium',
        'question' => 'من هي زوجة ريك غرايمز في بداية المسلسل؟',
        'a' => 'ميشون',
        'b' => 'لوري',
        'c' => 'ماغي',
        'd' => 'كارول',
        'correct' => 'b',
    ],
];
